// POM2 Apple II Emulator
// Copyright (C) 2026

#include "DiskIICard.h"
#include "FloppySoundSink.h"
#include "Logger.h"
#include "M6502.h"

#include <algorithm>
#include <cstdlib>
#include <cstring>
#include <fstream>

namespace {
// ~32 CPU cycles per nibble = 4 µs bit cells × 8 bits at 1.0227 MHz. Real
// hardware varies with the LSS state, but DOS 3.3 / ProDOS only need
// average-rate accuracy because they re-sync on every D5-AA prologue.
constexpr int kCyclesPerNibble  = 32;
constexpr int kQuarterTrackMax  = (DiskImage::kTracks - 1) * 4;  // 136

// Default contents of the Apple Disk II P6 PROM (341-0028-A, 16-sector
// variant) — MAME-layout, indexed by the scrambled 8-bit address scheme
// of `wozfdc.cpp lss_sync()`:
//
//   bit 7 = state[3]   bit 4 = !PULSE   bit 1 = QA
//   bit 6 = state[2]   bit 3 = Q7       bit 0 = state[1]
//   bit 5 = state[0]   bit 2 = Q6
//
// These 256 bytes are derived from apple2js's `SEQUENCER_ROM_16` table
// (rooted in Sather's "Understanding the Apple //e" Fig. 9.11) by
// applying MAME's PROM-pin permutation — same content, different index.
// Generated by `scripts/permute_p6_rom.py`; re-run if either side moves.
//
// Used as the fallback when `roms/diskii_p6.rom` is missing — POM2 keeps
// the LSS path active out of the box without depending on a dumped PROM
// file. `loadLssRom()` overrides this default with a verified dump
// (which must also be in MAME layout — see scripts/permute_p6_rom.py).
constexpr uint8_t kP6RomDefault[256] = {
    0x18, 0xD8, 0x18, 0x08, 0x0A, 0x0A, 0x0A, 0x0A, 0x18, 0x39, 0x18, 0x39, 0x18, 0x3B, 0x18, 0x3B, // row 0
    0x18, 0x38, 0x18, 0x28, 0x0A, 0x0A, 0x0A, 0x0A, 0x18, 0x39, 0x18, 0x39, 0x18, 0x3B, 0x18, 0x3B, // row 1
    0x2D, 0xD8, 0x38, 0x48, 0x0A, 0x0A, 0x0A, 0x0A, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, // row 2
    0x2D, 0x48, 0x38, 0x48, 0x0A, 0x0A, 0x0A, 0x0A, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, // row 3
    0xD8, 0xD8, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, // row 4
    0x58, 0x78, 0x58, 0x78, 0x0A, 0x0A, 0x0A, 0x0A, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, // row 5
    0xD8, 0xD8, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0x68, 0x08, 0x68, 0x88, 0x68, 0x08, 0x68, 0x88, // row 6
    0x68, 0x88, 0x68, 0x88, 0x0A, 0x0A, 0x0A, 0x0A, 0x68, 0x08, 0x68, 0x88, 0x68, 0x08, 0x68, 0x88, // row 7
    0xD8, 0xCD, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0x98, 0xB9, 0x98, 0xB9, 0x98, 0xBB, 0x98, 0xBB, // row 8
    0x98, 0xBD, 0x98, 0xB8, 0x0A, 0x0A, 0x0A, 0x0A, 0x98, 0xB9, 0x98, 0xB9, 0x98, 0xBB, 0x98, 0xBB, // row 9
    0xD8, 0xD9, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, // row A
    0x29, 0x59, 0xA8, 0xC8, 0x0A, 0x0A, 0x0A, 0x0A, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, // row B
    0xD9, 0xFD, 0xD8, 0xF8, 0x0A, 0x0A, 0x0A, 0x0A, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, // row C
    0xD9, 0xFD, 0xA0, 0xF8, 0x0A, 0x0A, 0x0A, 0x0A, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, // row D
    0xD8, 0xDD, 0xE8, 0xE0, 0x0A, 0x0A, 0x0A, 0x0A, 0xE8, 0x88, 0xE8, 0x08, 0xE8, 0x88, 0xE8, 0x08, // row E
    0x08, 0x4D, 0xE8, 0xE0, 0x0A, 0x0A, 0x0A, 0x0A, 0xE8, 0x88, 0xE8, 0x08, 0xE8, 0x88, 0xE8, 0x08, // row F
};

// Opt-in diagnostic — set POM2_DEBUG_DISK=1 to see one-shot lines marking
// each milestone of the Disk II boot sequence. Cheap when off (one bool
// check on hot-path reads, but only inside the diagnostic state struct's
// guard).
bool debugEnabled()
{
    static const bool on = []{
        const char* v = std::getenv("POM2_DEBUG_DISK");
        return v && *v && *v != '0';
    }();
    return on;
}

}  // namespace

DiskIICard::DiskIICard(int slot)
    : slot_(slot)
{
    bootRom.fill(0xFF);
    // Pre-fill with the published 16-sector P6 PROM so the LSS path
    // works out-of-the-box. `loadLssRom()` can override this with a
    // verified dump from `roms/diskii_p6.rom`. `p6RomLoaded` stays
    // false until an explicit load — when false, `useBitLss` also
    // stays false (legacy gate path) so cycle accounting and test
    // expectations match the pre-LSS behaviour.
    std::memcpy(p6Rom.data(), kP6RomDefault, sizeof(kP6RomDefault));
}

bool DiskIICard::loadBootRom(const std::string& path)
{
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        pom2::log().warn("Disk II", "Cannot open boot PROM: " + path);
        return false;
    }
    f.seekg(0, std::ios::end);
    const auto size = static_cast<size_t>(f.tellg());
    f.seekg(0, std::ios::beg);
    if (size != 256) {
        pom2::log().warn("Disk II",
            "Boot PROM must be 256 bytes, got " + std::to_string(size));
        return false;
    }
    f.read(reinterpret_cast<char*>(bootRom.data()), 256);
    if (!f) {
        pom2::log().warn("Disk II", "Short read on " + path);
        return false;
    }
    bootRomLoaded = true;
    pom2::log().info("Disk II", "Boot PROM loaded: " + path);
    return true;
}

bool DiskIICard::loadLssRom(const std::string& path)
{
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        pom2::log().info("Disk II",
            "P6 LSS PROM not found at " + path +
            " — using legacy 32-cycle gate");
        return false;
    }
    f.seekg(0, std::ios::end);
    const auto size = static_cast<size_t>(f.tellg());
    f.seekg(0, std::ios::beg);
    if (size != 256) {
        pom2::log().warn("Disk II",
            "P6 LSS PROM must be 256 bytes, got " + std::to_string(size) +
            " — using legacy 32-cycle gate");
        return false;
    }
    f.read(reinterpret_cast<char*>(p6Rom.data()), 256);
    if (!f) {
        pom2::log().warn("Disk II", "Short read on " + path);
        return false;
    }
    p6RomLoaded = true;
    pom2::log().info("Disk II", "P6 LSS PROM loaded: " + path);
    return true;
}

bool DiskIICard::insertDisk(int drive, const std::string& path)
{
    if (drive < 0 || drive >= kDriveCount) {
        pom2::log().warn("Disk II",
            "insertDisk: invalid drive index " + std::to_string(drive));
        return false;
    }
    DiskImage& img = images[drive];
    // Save any pending writes from the previous image before we drop it.
    if (img.isLoaded() && img.hasUnsavedChanges()) {
        if (!img.saveDirty()) {
            pom2::log().warn("Disk II",
                "Save-on-swap failed: " + img.getLastError());
        }
    }
    if (!img.loadFile(path)) {
        pom2::log().warn("Disk II", "Insert failed: " + img.getLastError());
        return false;
    }
    img.setWriteBackEnabled(writeBackEnabled);
    trackPos[drive] = 0;
    cycleAccum      = 0;
    writeLatch      = 0xFF;
    // Reset MAME wozfdc state. The default P6 ROM is in p6Rom (see
    // constructor) so the LSS path works without the optional
    // roms/diskii_p6.rom override. We still gate on `p6RomLoaded` so
    // the user can opt out by removing the file. (Done unconditionally
    // here so a drive-2 insert mid-session also resyncs the LSS rather
    // than carrying over flux state from the prior drive-1 image.)
    address         = 0x10;          // !PULSE high (no pulse), state=0
    lssData         = 0;
    writePosition   = 0;
    writeLineActive = false;
    writeStartTime  = 0;
    // Active iff P6 PROM file was loaded explicitly via loadLssRom.
    // The embedded default is also valid (and MAME-layout) but the
    // gating keeps the legacy 32-cycle gate available for tests that
    // pin pre-LSS behaviour until they're updated. Plus: any drive
    // holding a .woz image *forces* the LSS path. WOZ stores raw bit
    // cells, the legacy 32-cycle nibble gate cannot decode them, and
    // the embedded default P6 PROM in p6Rom is sufficient — so this
    // override works even without roms/diskii_p6.rom on disk.
    useBitLss       = p6RomLoaded;
    for (int d = 0; d < kDriveCount; ++d) {
        if (images[d].isWoz()) { useBitLss = true; break; }
    }
    // No click here — fires at user-initiated insert via UI / CLI only.
    // Auto-restore of the previous-session disk path calls insertDisk
    // during MainWindow construction; firing the click there would
    // surprise the user with a mechanical thunk on every startup.
    return true;
}

void DiskIICard::ejectDisk(int drive)
{
    if (drive < 0 || drive >= kDriveCount) return;
    DiskImage& img = images[drive];
    if (img.isLoaded() && img.hasUnsavedChanges()) {
        if (!img.saveDirty()) {
            pom2::log().warn("Disk II",
                "Save-on-eject failed: " + img.getLastError());
        }
    }
    img.eject();
    trackPos[drive] = 0;
    writeLatch      = 0xFF;
    // No click here — symmetric with insertDisk; UI / CLI sites fire
    // their own click when the user triggers the eject.
}

uint8_t DiskIICard::slotRomRead(uint8_t low8)
{
    if (debugEnabled() && !trace.sawSlotRom) {
        trace.sawSlotRom = true;
        char buf[64];
        std::snprintf(buf, sizeof(buf),
            "PROM entered (first slot ROM read at offset $%02X)", low8);
        pom2::log().info("Disk II", buf);
    }
    return bootRom[low8];
}

void DiskIICard::dumpRecentReads(size_t maxEntries) const
{
    const size_t n = std::min(readLog_.size(), maxEntries);
    if (n == 0) {
        std::fprintf(stderr, "DiskII read log: empty (set POM2_DEBUG_DISK_READS=1)\n");
        return;
    }
    std::fprintf(stderr, "DiskII recent $C0EC reads (last %zu of %zu):\n",
                 n, readLog_.size());
    const size_t start = (readLog_.size() > n) ? (readLog_.size() - n) : 0;
    for (size_t i = start; i < readLog_.size(); ++i) {
        const auto& e = readLog_[i];
        std::fprintf(stderr, "  [%4zu] cycle=%llu qt=%2u data=$%02X\n",
                     i,
                     static_cast<unsigned long long>(e.cycle),
                     unsigned(e.qt), unsigned(e.data));
    }
}

void DiskIICard::onReset()
{
    motorOn   = false;
    motorOffDelay = 0;
    writeMode = false;
    loadMode  = false;
    phaseOn   = {};
    cycleAccum = 0;
    dataLatch  = 0;
    byteReady  = false;
    active    = MODE_IDLE;
    // LSS state. Real Disk II hardware does NOT lose the head's bit-
    // stream alignment on a soft (Ctrl-Reset) — the disk keeps spinning
    // and the LSS shift register settles back to a stable value within
    // the next sync gap. We zero the address (state=0, QA=0) and data
    // register to start from a clean PROM state, with bit 4 of address
    // (!PULSE) high — no pulse pending. lssCycle survives (the PROM
    // re-syncs naturally on the next sync run).
    address          = 0x10;
    lssData          = 0;
    writePosition    = 0;
    writeLineActive  = false;
    // Active is now MODE_IDLE on both drives — the equivalent of MAME
    // `floppy_image_device::mon_w(true)`, which sets
    // `m_revolution_start_time = attotime::never`. The next lssStart
    // re-anchors the active drive's `revolutionStartLssCycle` to "now".
    revolutionStartLssCycle[0] = kNeverRev;
    revolutionStartLssCycle[1] = kNeverRev;
    trace = {};
    // Head position and trackPos are intentionally NOT reset — a real
    // Disk II loses neither when the host CPU is reset; the boot PROM
    // re-recalibrates by stepping phase 0 a bunch of times anyway.
}

void DiskIICard::seekPhaseW(int phases)
{
    // Verbatim port of MAME `floppy_image_device::seek_phase_w` — looks
    // at the *full* 4-bit phase mask and drops the head into the well
    // of whichever 1- or 2-magnet pattern is energized, with motion
    // capped at ±4 quarter-tracks per call. This replaces the prior
    // edge-detection model, which only stepped on rising edges and
    // missed sub-half-track positions used by Copy II Plus's analyzer
    // and by quarter-track copy protection schemes.
    //
    // Phase-mask -> well position (8 wells per "phase cycle"; each cycle
    // covers 2 tracks of head travel — 4 quarter-tracks per track):
    //   0x1 -> 0   0x3 -> 1   0x2 -> 2   0x6 -> 3
    //   0x4 -> 4   0xC -> 5   0x8 -> 6   0x9 -> 7
    // Anything else (no magnet, opposing magnets like 0x5 / 0xA, or 3+
    // simultaneously) leaves the head where it was.
    static constexpr int reqPosTable[16] = {
        -1, /*0x0 idle*/
         0, /*0x1*/
         2, /*0x2*/
         1, /*0x3*/
         4, /*0x4*/
        -1, /*0x5 opposing 0+2*/
         3, /*0x6*/
        -1, /*0x7 three magnets*/
         6, /*0x8*/
         7, /*0x9*/
        -1, /*0xA opposing 1+3*/
        -1, /*0xB three magnets*/
         5, /*0xC*/
        -1, /*0xD three magnets*/
        -1, /*0xE three magnets*/
        -1, /*0xF all four*/
    };
    const int req = reqPosTable[phases & 0xF];
    if (req < 0) return;

    // Move only the active drive's head. The phase magnets are wired to
    // the controller; only the selected drive's stepper responds.
    int& head = headQuarterTrack[activeDrive];
    const int cur = head;
    // Opposite-phase pattern (e.g. cur in well 0 and req=4): head sits
    // between two opposing magnets and doesn't move.
    if (((cur ^ req) & 7) == 4) return;

    int next = (cur & ~7) | req;
    if (next < cur - 4) next += 8;
    else if (next > cur + 4) next -= 8;
    next = std::clamp(next, 0, kQuarterTrackMax);
    const bool moved = (next != cur);
    head = next;
    // One mechanical "click" per quarter-track of head travel. DOS 3.3
    // does a 4-phase sweep (~4 step pulses per track); fast-seeking
    // utilities issue these back-to-back, which trips the audio source's
    // gap-< 100 ms classifier into seek mode automatically. We pass
    // `cpuCycleTotal` (emulated cycles) so the audio thread can measure
    // step cadence in emulated time — wall-clock measurement breaks
    // under disk turbo (all 80 phase-sweep steps land in one audio
    // buffer when the CPU runs ~60× real-time).
    if (moved && sound_) sound_->step(head / 4, cpuCycleTotal);
}

void DiskIICard::advanceCycles(int cycles)
{
    cpuCycleTotal += static_cast<uint64_t>(cycles);

    // Either path no-ops cleanly when the active drive has no media —
    // the LSS path bails after updating lssCycle, the legacy path bails
    // on motor-off below.
    if (!images[activeDrive].isLoaded()) {
        return;
    }

    if (!useBitLss) {
        if (!motorOn) return;
        legacyAdvance(cycles);
    } else {
        // MAME wozfdc: catch up the LSS to the new CPU time. lss_sync
        // skips when active == MODE_IDLE so a stopped drive is cheap.
        lssSync();
    }

    // Tick the spin-down delay. When it expires the motor truly stops
    // (active drops to MODE_IDLE).
    if (motorOffDelay > 0) {
        motorOffDelay -= cycles;
        if (motorOffDelay <= 0) {
            motorOffDelay = 0;
            motorOn       = false;
            if (active == MODE_DELAY) {
                active = MODE_IDLE;
                // MAME `floppy_image_device::mon_w(true)`: when the
                // controller actually stops driving the spindle, the
                // drive's revolution timestamp becomes `attotime::never`.
                // POM2's equivalent: clear the anchor so a subsequent
                // motor-on event re-zeros it from the new spin-up.
                revolutionStartLssCycle[activeDrive] = kNeverRev;
            }
            if (sound_) sound_->motor(false, images[activeDrive].isLoaded());
        }
    }
}

void DiskIICard::legacyAdvance(int cycles)
{
    DiskImage& img = images[activeDrive];
    int& pos       = trackPos[activeDrive];
    // Legacy 32-cycle gate operates on whole-track nibble buffers
    // (.dsk/.do/.po/.nib formats only — WOZ disks force the LSS path
    // via `useBitLss=true` on insert). Quarter-track granularity isn't
    // meaningful on the legacy gate; snap to the containing whole
    // track.
    const int track = headQuarterTrack[activeDrive] / 4;
    cycleAccum += cycles;
    while (cycleAccum >= kCyclesPerNibble) {
        cycleAccum -= kCyclesPerNibble;
        pos = (pos + 1) % DiskImage::kNibblesPerTrack;
        if (writeMode) {
            // Write the most-recently-latched nibble onto the track.
            // Real hardware streams bits through the LSS shift register;
            // we model one nibble per ~32 CPU cycles, matching the read
            // pacing. The CPU latches the next nibble via a soft-switch
            // store (see deviceSelectWrite). Honour writeBackEnabled
            // symmetrically with the LSS path — the user toggle off
            // must keep host files intact regardless of which gate is
            // active.
            if (writeBackEnabled) {
                img.writeNibbleAt(track, pos, writeLatch);
                ++writeFlushCount;
            }
        } else {
            dataLatch = img.nibbleAt(track, pos);
            byteReady = true;
        }
    }
}

// MAME `wozfdc_device::lss_start` — called from control() when the motor
// transitions to MODE_ACTIVE. Resets the LSS bookkeeping so we don't
// carry stale state from the last spin-up. Note we explicitly do NOT
// re-pin the data register on a MODE_DELAY → MODE_ACTIVE transition
// (real hardware preserves it across the spin-down window).
//
// This also models MAME's `floppy_image_device::mon_w(false)` for the
// currently-selected drive: anchor its `revolution_start_time` to "now"
// so the disk's angular position reads as zero immediately after spin-up.
// The other drive (if any) keeps whatever `revolutionStartLssCycle` it
// had — MAME never touches an idle drive's revolution state from the
// controller side.
void DiskIICard::lssStart()
{
    DiskImage& img = images[activeDrive];
    lssCycle        = cpuCycleTotal * 2;
    lssData         = 0;
    address         = static_cast<uint8_t>(address & ~0x0E);
    writePosition   = 0;
    writeStartTime  = writeMode ? static_cast<int64_t>(lssCycle) : 0;
    writeLineActive = false;
    revolutionStartLssCycle[activeDrive] = static_cast<int64_t>(lssCycle);
    if (writeMode && img.isLoaded()) {
        img.setWriteSplice(headQuarterTrack[activeDrive], writeStartTime);
    }
}

// MAME `wozfdc_device::lss_sync(extra_cycles)` — verbatim port. The LSS
// runs at 2× CPU clock; one PROM lookup per LSS cycle. We catch up from
// the persistent `lssCycle` counter to a target derived from the CPU
// total, optionally with an `extra` LSS-cycle bump to model the read-
// pipe latency on $C0nC reads. PULSE is set for exactly one LSS cycle
// when the head crosses a flux transition, fed from
// DiskImage::getNextTransition (the flux model port).
void DiskIICard::lssSync(uint64_t extraCycles)
{
    if (active == MODE_IDLE) return;
    DiskImage& img = images[activeDrive];
    if (!img.isLoaded()) {
        lssCycle = cpuCycleTotal * 2 + extraCycles;
        return;
    }

    // Quarter-track index drives every LSS-side image access — WOZ
    // images expose a distinct flux stream per quarter-track (Spiradisc
    // / RWTS18 / Locksmith protections rely on this); non-WOZ aliases
    // four quarter-tracks per whole-track inside DiskImage.
    const int qt = headQuarterTrack[activeDrive];

    // MAME passes `cycles_to_time(cycles - 1)` to `get_next_transition`, but
    // that's NOT a "look one cycle into the past" — it's compensating for
    // MAME's `cycles_to_time` ⇄ `time_to_cycles` round-trip having a +1
    // LSS-tick offset baked into both halves (see `time_to_cycles` body in
    // `wozfdc.cpp` line 331). In MAME's reference frame, `cycles_to_time(c)`
    // returns a time *strictly after* the floppy-stored time of the event at
    // MAME cycle c — so passing `c-1` finds the event at c (or later), never
    // at c-1.
    //
    // Our port stores flux events as raw LSS-cycle indexes (`cell*8 + 4` per
    // `expandTrackFlux`), so we don't need — and must not apply — the
    // compensation. Pass `lssCycle` directly: `getNextTransition` has
    // lower-bound semantics, returning the event at lssCycle if there is
    // one and the next one otherwise.
    //
    // Subtracting 1 here was a misapplied transcription of MAME's compensation.
    // It made `getNextTransition` return the *previous* event (the one we
    // just processed) whenever lssSync re-entered at `prev_nextFluxDown`.
    // The loop then computed `cyclesNextTrans = cyclesLimit` (since both
    // `lssCycle < nextFlux` and `lssCycle < nextFluxDown` were false for a
    // past event), ran the inner loop straight to cyclesLimit, and silently
    // skipped every flux event in the open interval (prev_event, cyclesLimit].
    // The skipped events were dropped permanently — the next call's
    // `getNextTransition` rolled past them too. With ~1.0227 MHz CPU and
    // ~125 KB/s read rate, that worked out to lost cells under sustained
    // reads, surfacing as DOS / ProDOS I/O errors and RWTS retries on real
    // disks even though the boot-prologue smoke test (which only validates
    // a single D5 AA 96 match in a 5-revolution scan) couldn't see it.
    //
    // Pinned by `tests/diskii_lss_smoke_test.cpp::testFullSectorReadback`
    // (added with this fix).
    const int64_t revStart = revolutionStartLssCycle[activeDrive];
    int64_t nextFlux = img.getNextTransition(qt,
                          static_cast<int64_t>(lssCycle), revStart);
    int64_t nextFluxDown = (nextFlux != DiskImage::kFluxNever)
                              ? nextFlux + 1
                              : DiskImage::kFluxNever;

    // Initial PULSE state: address bit 4 low for the LSS-cycle range
    // [nextFlux, nextFluxDown), high otherwise. (MAME: `if(cycles >= cycles_next_flux && cycles < cycles_next_flux_down) address &= ~0x10; else address |= 0x10;`)
    if (static_cast<int64_t>(lssCycle) >= nextFlux
        && static_cast<int64_t>(lssCycle) < nextFluxDown) {
        address = static_cast<uint8_t>(address & ~0x10);
    } else {
        address = static_cast<uint8_t>(address | 0x10);
    }

    const uint64_t cyclesLimit = cpuCycleTotal * 2 + extraCycles;
    if (lssCycle > cyclesLimit) return;        // safety: never go back

    while (lssCycle < cyclesLimit) {
        // Advance to the next "transition" — either the catch-up limit,
        // the next flux rising edge, or the falling edge after it.
        int64_t cyclesNextTrans = static_cast<int64_t>(cyclesLimit);
        if (cyclesNextTrans > nextFlux
            && static_cast<int64_t>(lssCycle) < nextFlux) {
            cyclesNextTrans = nextFlux;
        }
        if (cyclesNextTrans > nextFluxDown
            && static_cast<int64_t>(lssCycle) < nextFluxDown) {
            cyclesNextTrans = nextFluxDown;
        }

        while (static_cast<int64_t>(lssCycle) < cyclesNextTrans) {
            const uint8_t op = p6Rom[address];

            // Write side: edge-detect on WRITE_DATA (= address bit 7).
            // Each toggle becomes one flux event in the splice buffer,
            // timestamped at the current LSS cycle. When the buffer
            // approaches its 32-entry capacity, pre-emptively flush via
            // image.writeFlux so we never miss a transition.
            if (writeMode) {
                const bool prev = writeLineActive;
                const bool curr = (address & 0x80) != 0;
                if (prev != curr) {
                    writeLineActive = curr;
                    if (writePosition < kWriteBufferSize) {
                        writeBuffer[writePosition++] =
                            static_cast<int64_t>(lssCycle);
                    }
                } else if (writePosition >= 30) {
                    const int64_t now = static_cast<int64_t>(lssCycle);
                    if (writeBackEnabled) {
                        img.writeFlux(qt, writeStartTime, now,
                                      writePosition, writeBuffer);
                        ++writeFlushCount;
                    }
                    writeStartTime = now;
                    writePosition  = 0;
                }
            }

            // Update state bits of address (7,6,5,0) from opcode bits
            // (7,6,4,5) using MAME's exact PROM-pin pack.
            address = static_cast<uint8_t>((address & 0x1E)
                    | (op & 0xC0)
                    | ((op & 0x20) >> 5)
                    | ((op & 0x10) << 1));

            // ALU dispatch — MAME's full opcode range, no fall-through.
            switch (op & 0x0F) {
                case 0x0: case 0x1: case 0x2: case 0x3:
                case 0x4: case 0x5: case 0x6: case 0x7:
                    lssData = 0;
                    break;
                case 0x8: case 0xC:
                    break;
                case 0x9:
                    lssData = static_cast<uint8_t>(lssData << 1);
                    break;
                case 0xA: case 0xE:
                    lssData = static_cast<uint8_t>((lssData >> 1)
                        | (img.isWriteProtected() ? 0x80 : 0x00));
                    break;
                case 0xB: case 0xF:
                    lssData = writeLatch;
                    break;
                case 0xD:
                    lssData = static_cast<uint8_t>((lssData << 1) | 0x01);
                    break;
            }

            // QA = data MSB.
            if (lssData & 0x80) address |= 0x02; else address &= ~0x02;
            ++lssCycle;
        }

        // Cross the flux transition. PULSE goes low at nextFlux and
        // high again at nextFluxDown; advance the flux cursor when we
        // exit the high region.
        if (static_cast<int64_t>(lssCycle) == nextFlux) {
            address = static_cast<uint8_t>(address & ~0x10);
        } else if (static_cast<int64_t>(lssCycle) == nextFluxDown) {
            address = static_cast<uint8_t>(address | 0x10);
            nextFlux = img.getNextTransition(qt,
                          static_cast<int64_t>(lssCycle), revStart);
            nextFluxDown = (nextFlux != DiskImage::kFluxNever)
                               ? nextFlux + 1
                               : DiskImage::kFluxNever;
        }
    }

    if (debugEnabled() && (lssData & 0x80) && !trace.sawFirstNibble) {
        trace.sawFirstNibble = true;
        char buf[96];
        std::snprintf(buf, sizeof(buf),
            "first GCR nibble served: $%02X (LSS, qt %d / track %d)",
            lssData, qt, qt / 4);
        pom2::log().info("Disk II", buf);
    }
}

// MAME `wozfdc_device::control()` cases 0xa/0xb — drive_select switch.
// When motor is active, mon_w(true) is sent to the old drive (commits
// in-flight writes, freezes the flux cursor; sets
// `revolution_start_time = attotime::never`) and mon_w(false) to the
// new drive (revolution_start_time = now, restart spin). The equivalent
// in POM2's model:
//   1. If `writeMode` and there are pending events in the write buffer,
//      flush them to the OLD drive's track at the current LSS cycle.
//      (Real silicon: the write head stops driving the surface; any
//      flux events captured since the last splice land in the track.)
//   2. Mark the OLD drive's `revolutionStartLssCycle` as `kNeverRev`
//      (MAME's `attotime::never`) — its disk stops contributing to flux
//      reads. Leave the controller's `lssCycle` alone; MAME keeps
//      `cycles` running across drive swaps.
//   3. Anchor the NEW drive's `revolutionStartLssCycle` to the current
//      `lssCycle`. MAME `floppy_image_device::mon_w(false)` sets
//      `m_revolution_start_time = machine().time()`; the new spin-up
//      conceptually starts now. (For a single-drive system this is
//      academic — the only motor-on transition came from `lssStart`
//      itself, which already set the anchor — but the multi-drive
//      $C0EA / $C0EB swap path must do it explicitly.)
//   4. Re-init the write-state cursor for the new drive so a write that
//      survives the drive swap (rare but legal: WRITE mode + drive swap
//      mid-burst) splices into the right track at the right LSS cycle.
//   5. Clear PULSE in the LSS address — the new drive's flux stream is
//      fresh, the previous-drive's pending pulse no longer applies.
//
// Reference: MAME `wozfdc.cpp:219-241`,
// `floppy.cpp:809-839` (mon_w).
void DiskIICard::selectDrive(int newDrive)
{
    if (newDrive == activeDrive) return;
    const int oldDrive = activeDrive;
    if (active != MODE_IDLE) {
        // Flush in-flight writes to OLD drive (mon_w(true) → commit_image).
        DiskImage& oldImg = images[oldDrive];
        if (writeMode && oldImg.isLoaded() && writeBackEnabled
            && writePosition > 0) {
            oldImg.writeFlux(headQuarterTrack[oldDrive],
                             writeStartTime,
                             static_cast<int64_t>(lssCycle),
                             writePosition, writeBuffer);
            ++writeFlushCount;
        }
        writePosition   = 0;
        writeLineActive = false;

        // OLD drive: mon_w(true). Disk angular position is now undefined
        // — flux reads against it would return nothing. MAME uses
        // `attotime::never` for the same effect.
        revolutionStartLssCycle[oldDrive] = kNeverRev;

        // Switch drives. Do NOT reset `lssCycle` — MAME's `cycles` keeps
        // running continuously across the swap (`a3_update_drive_sel`
        // calls `lss_sync()` but never touches the controller's clock).
        activeDrive = newDrive;
        // NEW drive: mon_w(false). Anchor angular position to "now".
        revolutionStartLssCycle[newDrive] = static_cast<int64_t>(lssCycle);
        address  = static_cast<uint8_t>(address | 0x10);   // PULSE = no pulse
        writeStartTime = writeMode ? static_cast<int64_t>(lssCycle) : 0;
        if (writeMode && images[newDrive].isLoaded()) {
            images[newDrive].setWriteSplice(
                headQuarterTrack[newDrive], writeStartTime);
        }
    } else {
        // Motor off — no mon_w transition to model. Just remember the
        // selection for the next motor-on event.
        activeDrive = newDrive;
    }
}

// MAME `wozfdc_device::control(offset)` — verbatim port. Only POM2-
// specific bits: we lack the F9334 phaselatch device, so we expand the
// `m_phaselatch->write_bit(phase, on)` path inline (sets phaseOn[i] and
// invokes seekPhaseW with the resulting 4-bit mask).
void DiskIICard::control(int offset)
{
    if (offset < 8) {
        const int  phase = offset >> 1;
        const bool on    = (offset & 1) != 0;
        phaseOn[phase]   = on;
        int mask = 0;
        for (int i = 0; i < 4; ++i) if (phaseOn[i]) mask |= (1 << i);
        if (active) seekPhaseW(mask);
        return;
    }

    switch (offset) {
        case 0x8:
            if (active == MODE_ACTIVE) {
                motorOffDelay = 1'022'727;   // 1 sec @ 1.0227 MHz
                active = MODE_DELAY;
            }
            break;
        case 0x9:
            switch (active) {
                case MODE_IDLE:
                    motorOn = true;
                    active  = MODE_ACTIVE;
                    if (images[activeDrive].isLoaded()) lssStart();
                    if (sound_) sound_->motor(true, images[activeDrive].isLoaded());
                    if (debugEnabled() && !trace.sawMotorOn) {
                        trace.sawMotorOn = true;
                        char buf[96];
                        std::snprintf(buf, sizeof(buf),
                            "motor ON (drive %d, head at quarter-track %d, disk %s)",
                            activeDrive + 1,
                            headQuarterTrack[activeDrive],
                            images[activeDrive].isLoaded() ? "loaded" : "MISSING");
                        pom2::log().info("Disk II", buf);
                    }
                    break;
                case MODE_DELAY:
                    active        = MODE_ACTIVE;
                    motorOffDelay = 0;
                    motorOn       = true;
                    break;
                case MODE_ACTIVE:
                    break;
            }
            break;
        case 0xa:
            // Drive 1 select. MAME `wozfdc.cpp:219-227`: when active,
            // mon_w(true) on the old drive (commit writes, freeze flux)
            // + mon_w(false) on the new drive (revolution_start_time =
            // now). `selectDrive()` models both halves of the swap.
            selectDrive(0);
            break;
        case 0xb:
            // Drive 2 select. MAME `wozfdc.cpp:229-241`. Same as 0xa
            // but onto images[1]. The TODO regression we fix here: the
            // previous `activeDrive = 1` direct assignment left the LSS
            // cycle base unchanged, so drive 2 was reading flux at the
            // shared lssCycle modulo its track period — not from
            // position 0 of its current track the way MAME models it.
            // Multi-drive copy protections (Locksmith, Copy II Plus)
            // that switch drive mid-spin depend on this.
            selectDrive(1);
            break;
        case 0xc:
            if (loadMode) {
                if (active) address = static_cast<uint8_t>(address & ~0x04);
                loadMode = false;
            }
            break;
        case 0xd:
            if (!loadMode) {
                if (active) address = static_cast<uint8_t>(address | 0x04);
                loadMode = true;
            }
            break;
        case 0xe:
            if (writeMode) {
                if (active) address = static_cast<uint8_t>(address & ~0x08);
                writeMode = false;
                // MAME: `floppy->write_flux(write_start_time, now,
                // write_position, write_buffer);` — splice the in-flight
                // events into the track on Q7 falling edge.
                DiskImage& img = images[activeDrive];
                if (img.isLoaded() && writeBackEnabled
                    && writePosition > 0) {
                    img.writeFlux(headQuarterTrack[activeDrive],
                                  writeStartTime,
                                  static_cast<int64_t>(lssCycle),
                                  writePosition, writeBuffer);
                    ++writeFlushCount;
                }
                writePosition = 0;
                // MAME `iwm.cpp:199` — Q7 falling edge while active
                // clears whd bit 6 ("in write mode" indicator).
                iwmWhd &= ~0x40;
            }
            break;
        case 0xf:
            if (!writeMode) {
                if (active) {
                    address = static_cast<uint8_t>(address | 0x08);
                    writeStartTime = static_cast<int64_t>(lssCycle);
                    writePosition  = 0;
                    DiskImage& img = images[activeDrive];
                    if (img.isLoaded()) {
                        img.setWriteSplice(headQuarterTrack[activeDrive],
                                           writeStartTime);
                    }
                }
                writeMode = true;
                // MAME `iwm.cpp:183` — Q7 rising edge while active sets
                // whd bit 6 to flag "controller now in write mode".
                iwmWhd |= 0x40;
            }
            break;
        default: break;
    }
}

void DiskIICard::handleSwitchAccess(uint8_t low4)
{
    if (debugEnabled() && !trace.sawDevSelect) {
        trace.sawDevSelect = true;
        char buf[64];
        std::snprintf(buf, sizeof(buf),
            "first soft switch hit (low4=$%X)", low4);
        pom2::log().info("Disk II", buf);
    }

    if (!useBitLss) {
        // Legacy gate behaviour — preserved verbatim from pre-MAME-port
        // code so disk_boot_smoke / dos33_save_smoke / prodos_save tests
        // (which don't load the P6 ROM) keep their pinned semantics.
        if (low4 < 8) {
            const int  phase = low4 >> 1;
            const bool on    = (low4 & 1) != 0;
            phaseOn[phase]   = on;
            int mask = 0;
            for (int i = 0; i < 4; ++i) if (phaseOn[i]) mask |= (1 << i);
            seekPhaseW(mask);
            return;
        }
        switch (low4) {
            case 0x8:
                if (motorOn && sound_)
                    sound_->motor(false, images[activeDrive].isLoaded());
                motorOn = false;
                motorOffDelay = 0;
                break;
            case 0x9:
                if (!motorOn) {
                    cycleAccum = 0;
                    if (sound_) sound_->motor(true, images[activeDrive].isLoaded());
                    if (debugEnabled() && !trace.sawMotorOn) {
                        trace.sawMotorOn = true;
                        char buf[96];
                        std::snprintf(buf, sizeof(buf),
                            "motor ON (drive %d, head at quarter-track %d, disk %s)",
                            activeDrive + 1,
                            headQuarterTrack[activeDrive],
                            images[activeDrive].isLoaded() ? "loaded" : "MISSING");
                        pom2::log().info("Disk II", buf);
                    }
                }
                motorOn = true;
                motorOffDelay = 0;
                break;
            // $C0nA / $C0nB: drive_select. Both code paths (LSS and
            // legacy gate) honour the same activeDrive so the legacy
            // tests can exercise drive 2 too. The legacy 32-cycle gate
            // doesn't model a per-drive flux phase, so the mon_w
            // transition is a near-no-op here — selectDrive() still
            // flushes any pending write buffer (defence in depth, even
            // though the legacy path doesn't populate it).
            case 0xA: selectDrive(0); break;
            case 0xB: selectDrive(1); break;
            case 0xC: loadMode  = false; break;
            case 0xD: loadMode  = true;  break;
            case 0xE: writeMode = false; break;
            case 0xF: writeMode = true;  break;
            default: break;
        }
        return;
    }

    // MAME path: control() handles every soft-switch effect.
    control(low4);
}

// ─── Sub-instruction cycle accuracy ────────────────────────────────────
//
// MMIO accesses from the 6502 happen at a specific cycle within the
// instruction (e.g. `LDA $C0EC`'s data fetch is the 4th of 4 cycles).
// MAME's `m6502.cpp` is a per-cycle state machine — its `wozfdc_device`
// observes each access at the precise sub-instruction time.
//
// POM2's M6502 batches the whole instruction's cycles into a single
// `memory->advanceCycles(N)` after `executeOpcode` returns; during
// execution, `cpuCycleTotal` reflects the START of the instruction. For
// stock DOS / ProDOS RWTS the difference is invisible — the LSS lands
// the same nibbles either way. But cycle-precise copy protections that
// time their reads against the LSS state ARE off by a few cycles.
//
// The fix is to query `cpu->getCurrentInstructionCycles()` at the
// access point: that's the count of cycles already elapsed within the
// current instruction (e.g. 3 at the data fetch of `LDA abs`). We
// temporarily inflate `cpuCycleTotal` by this delta during the access,
// run `lssSync` against the inflated value, and restore on the way out
// (so the post-instruction `advanceCycles(N)` accounts for the right
// total). The RAII guard below makes this exception-safe and keeps the
// save/restore out of every code path of `deviceSelectRead/Write`.
//
// Mid-instruction inflation pattern:
//   cpuCycleTotal_before_inst = X
//   in deviceSelectRead: cpuCycleTotal += subCycles  (X + 3 for LDA $C0EC)
//                        lssSync(0) catches LSS to 2*(X+3)
//                        lssSync(1) catches to 2*(X+3) + 1
//                        cpuCycleTotal restored to X (RAII dtor)
//   after instruction: advanceCycles(4) → cpuCycleTotal = X + 4
//                      lssSync(0) catches LSS to 2*(X+4) = 2*(X+3) + 2
//
// Net: LSS runs 8 cycles per instruction (same as before), but the data
// register is sampled at the correct sub-cycle within the instruction.
struct SubInstructionScope
{
    uint64_t& target;
    uint64_t saved;
    SubInstructionScope(uint64_t& counter, uint64_t add)
        : target(counter), saved(counter) { target += add; }
    ~SubInstructionScope() { target = saved; }
};

uint8_t DiskIICard::deviceSelectRead(uint8_t low4)
{
    if (useBitLss) {
        // MAME `wozfdc_device::read(offset)`:
        //   lss_sync();
        //   control(offset);
        //   if(!(offset & 1)) { lss_sync(1); return data_reg; }
        //   return 0xff;
        SubInstructionScope sub(cpuCycleTotal,
            cpu_ ? static_cast<uint64_t>(cpu_->getCurrentInstructionCycles()) : 0);
        lssSync(0);
        const bool wasQ6 = loadMode;
        handleSwitchAccess(low4);
        // IWM status read hook (MAME `iwm.cpp:107-109`, case 0x40):
        //   read $C0nE with Q6 high + Q7 low (this access clears Q7 but
        //   Q6 was already on) → return (status & 0x7F) | (wpt ? 0x80 : 0).
        //   status low 5 = mode low 5 (MAME `iwm.cpp:259`). The Apple //c+
        //   alt firmware probes this; without it the boot loop at $E51B
        //   (BEQ on `Y EOR status & $1F`) never falls through and the
        //   Monitor hangs before clearing the text page.
        if (low4 == 0xE && wasQ6) {
            DiskImage& img = images[activeDrive];
            const uint8_t wpt = (!img.isLoaded() || img.isWriteProtected()) ? 0x80 : 0x00;
            return static_cast<uint8_t>(wpt | (iwmMode & 0x1F));
        }
        // IWM write-handshake read hook (MAME `iwm.cpp:107-110`, case
        // 0x80): read $C0nC with Q7 high + Q6 low → return m_whd. The
        // //c+ alt firmware's write loop at `$C8A6: BIT $C0EC / BPL`
        // waits for whd bit 7 ("ready") to be set; without this it
        // sees the raw LSS data byte (often bit-7-clear) and spins.
        if (low4 == 0xC && writeMode) {
            return iwmWhd;
        }
        if (!(low4 & 1)) {
            lssSync(1);
            // Debug log: capture (cycle, byte, qt) for hero_probe to dump.
            static const bool kLogReads = std::getenv("POM2_DEBUG_DISK_READS") != nullptr;
            if (kLogReads && low4 == 0xC) {
                if (readLog_.size() < kReadLogCap) {
                    readLog_.push_back({cpuCycleTotal, lssData,
                        static_cast<uint8_t>(headQuarterTrack[activeDrive])});
                } else {
                    readLog_[readLogCursor_++ % kReadLogCap] =
                        {cpuCycleTotal, lssData,
                         static_cast<uint8_t>(headQuarterTrack[activeDrive])};
                }
            }
            // Optional CSV stream log for post-mortem LSS analysis. Open
            // once on first hit when `POM2_DEBUG_DISK_STREAM=path` is set;
            // each $C0EC read appends `cycle,qt,data` so a Python pass can
            // reconstruct exactly what the controller delivered to the
            // CPU. Lifetime tied to process exit (FILE leaked
            // intentionally — flush-on-exit via stdio shutdown handler).
            static FILE* g_streamLog = []() -> FILE* {
                const char* path = std::getenv("POM2_DEBUG_DISK_STREAM");
                if (!path) return nullptr;
                FILE* f = std::fopen(path, "w");
                if (f) std::fprintf(f, "cycle,qt,data\n");
                return f;
            }();
            if (g_streamLog && low4 == 0xC) {
                std::fprintf(g_streamLog, "%llu,%d,%02x\n",
                    static_cast<unsigned long long>(cpuCycleTotal),
                    headQuarterTrack[activeDrive],
                    lssData);
            }
            return lssData;
        }
        // For odd offsets MAME returns 0xFF (open bus), but POM2 still
        // needs the write-protect probe at $C0nD (low4=0xD, !writeMode).
        if (low4 == 0xD && !writeMode) {
            DiskImage& img = images[activeDrive];
            if (!img.isLoaded()) return 0x00;
            return img.isWriteProtected() ? 0x80 : 0x00;
        }
        return 0xFF;
    }

    // Legacy gate path.
    const bool wasQ6Legacy = loadMode;
    handleSwitchAccess(low4);
    // IWM status read hook (same as the bit-LSS path above). Mirrored
    // here because POM2's test-rig and pre-disk-insert state both pin
    // `useBitLss = false` until a WOZ image or P6 PROM is in flight —
    // and the //c+ alt firmware probes $C0EE *before* the user clicks
    // a disk in the library.
    if (low4 == 0xE && wasQ6Legacy) {
        DiskImage& img = images[activeDrive];
        const uint8_t wpt = (!img.isLoaded() || img.isWriteProtected()) ? 0x80 : 0x00;
        return static_cast<uint8_t>(wpt | (iwmMode & 0x1F));
    }
    if (low4 == 0xC && writeMode) {
        return iwmWhd;
    }
    DiskImage& img = images[activeDrive];
    if (low4 == 0xC && !writeMode && !loadMode) {
        if (!img.isLoaded() || !motorOn) return 0xFF;
        const uint8_t out = byteReady ? dataLatch : (dataLatch & 0x7F);
        if (debugEnabled() && byteReady && !trace.sawFirstNibble) {
            trace.sawFirstNibble = true;
            char buf[96];
            std::snprintf(buf, sizeof(buf),
                "first GCR nibble served: $%02X (drive %d, track %d, pos %d)",
                dataLatch, activeDrive + 1,
                headQuarterTrack[activeDrive] / 4,
                trackPos[activeDrive]);
            pom2::log().info("Disk II", buf);
        }
        byteReady = false;
        return out;
    }
    if (low4 == 0xD && !writeMode) {
        if (!img.isLoaded()) return 0x00;
        return img.isWriteProtected() ? 0x80 : 0x00;
    }
    return 0;
}

void DiskIICard::deviceSelectWrite(uint8_t low4, uint8_t v)
{
    if (useBitLss) {
        // MAME `wozfdc_device::write(offset, data)`:
        //   lss_sync();
        //   control(offset);
        //   last_6502_write = data;
        SubInstructionScope sub(cpuCycleTotal,
            cpu_ ? static_cast<uint64_t>(cpu_->getCurrentInstructionCycles()) : 0);
        lssSync(0);
        const bool wasQ6 = loadMode;
        handleSwitchAccess(low4);
        // IWM mode_w hook (MAME `iwm.cpp:248-253`): writes to $C0nF when
        // Q6 was already high latch the mode register. Real wozfdc has
        // no such register so the //c+ alt-firmware probe at $E512-$E522
        // (in bank 1) spins forever without this.
        if (low4 == 0xF && wasQ6) {
            iwmMode = v;
        }
        writeLatch = v;
        return;
    }

    // Legacy gate path. Mirror MAME wozfdc's `last_6502_write = data` —
    // latch every $C0Ex write regardless of low nibble, so a write to
    // any switch in the range (Q6 toggle, drive select, …) refreshes
    // the byte the next nibble flush will emit. The legacy advance
    // still consumes `writeLatch` only when `writeMode` is on, so
    // unconditional latching is harmless in read mode.
    const bool wasQ6LegacyW = loadMode;
    handleSwitchAccess(low4);
    // IWM mode_w shadow (matches the bit-LSS branch above). Required
    // for the //c+ alt-firmware probe before any disk is mounted.
    if (low4 == 0xF && wasQ6LegacyW) {
        iwmMode = v;
    }
    writeLatch = v;
    if (writeMode && low4 == 0xD) {
        cycleAccum = 0;
    }
}
