// POM2 Apple II Emulator
// Copyright (C) 2026

#include "DiskIICard.h"
#include "Logger.h"

#include <algorithm>
#include <cstdlib>
#include <cstring>
#include <fstream>

namespace {
// ~32 CPU cycles per nibble = 4 µs bit cells × 8 bits at 1.0227 MHz. Real
// hardware varies with the LSS state, but DOS 3.3 / ProDOS only need
// average-rate accuracy because they re-sync on every D5-AA prologue.
constexpr int kCyclesPerNibble  = 32;
constexpr int kQuarterTrackMax  = (DiskImage::kTracks - 1) * 4;  // 136

// Default contents of the Apple Disk II P6 PROM (341-0028-A, 16-sector
// variant) — MAME-layout, indexed by the scrambled 8-bit address scheme
// of `wozfdc.cpp lss_sync()`:
//
//   bit 7 = state[3]   bit 4 = !PULSE   bit 1 = QA
//   bit 6 = state[2]   bit 3 = Q7       bit 0 = state[1]
//   bit 5 = state[0]   bit 2 = Q6
//
// These 256 bytes are derived from apple2js's `SEQUENCER_ROM_16` table
// (rooted in Sather's "Understanding the Apple //e" Fig. 9.11) by
// applying MAME's PROM-pin permutation — same content, different index.
// Generated by `scripts/permute_p6_rom.py`; re-run if either side moves.
//
// Used as the fallback when `roms/diskii_p6.rom` is missing — POM2 keeps
// the LSS path active out of the box without depending on a dumped PROM
// file. `loadLssRom()` overrides this default with a verified dump
// (which must also be in MAME layout — see scripts/permute_p6_rom.py).
constexpr uint8_t kP6RomDefault[256] = {
    0x18, 0xD8, 0x18, 0x08, 0x0A, 0x0A, 0x0A, 0x0A, 0x18, 0x39, 0x18, 0x39, 0x18, 0x3B, 0x18, 0x3B, // row 0
    0x18, 0x38, 0x18, 0x28, 0x0A, 0x0A, 0x0A, 0x0A, 0x18, 0x39, 0x18, 0x39, 0x18, 0x3B, 0x18, 0x3B, // row 1
    0x2D, 0xD8, 0x38, 0x48, 0x0A, 0x0A, 0x0A, 0x0A, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, // row 2
    0x2D, 0x48, 0x38, 0x48, 0x0A, 0x0A, 0x0A, 0x0A, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, // row 3
    0xD8, 0xD8, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, // row 4
    0x58, 0x78, 0x58, 0x78, 0x0A, 0x0A, 0x0A, 0x0A, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, // row 5
    0xD8, 0xD8, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0x68, 0x08, 0x68, 0x88, 0x68, 0x08, 0x68, 0x88, // row 6
    0x68, 0x88, 0x68, 0x88, 0x0A, 0x0A, 0x0A, 0x0A, 0x68, 0x08, 0x68, 0x88, 0x68, 0x08, 0x68, 0x88, // row 7
    0xD8, 0xCD, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0x98, 0xB9, 0x98, 0xB9, 0x98, 0xBB, 0x98, 0xBB, // row 8
    0x98, 0xBD, 0x98, 0xB8, 0x0A, 0x0A, 0x0A, 0x0A, 0x98, 0xB9, 0x98, 0xB9, 0x98, 0xBB, 0x98, 0xBB, // row 9
    0xD8, 0xD9, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, // row A
    0x29, 0x59, 0xA8, 0xC8, 0x0A, 0x0A, 0x0A, 0x0A, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, // row B
    0xD9, 0xFD, 0xD8, 0xF8, 0x0A, 0x0A, 0x0A, 0x0A, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, // row C
    0xD9, 0xFD, 0xA0, 0xF8, 0x0A, 0x0A, 0x0A, 0x0A, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, // row D
    0xD8, 0xDD, 0xE8, 0xE0, 0x0A, 0x0A, 0x0A, 0x0A, 0xE8, 0x88, 0xE8, 0x08, 0xE8, 0x88, 0xE8, 0x08, // row E
    0x08, 0x4D, 0xE8, 0xE0, 0x0A, 0x0A, 0x0A, 0x0A, 0xE8, 0x88, 0xE8, 0x08, 0xE8, 0x88, 0xE8, 0x08, // row F
};

// Opt-in diagnostic — set POM2_DEBUG_DISK=1 to see one-shot lines marking
// each milestone of the Disk II boot sequence. Cheap when off (one bool
// check on hot-path reads, but only inside the diagnostic state struct's
// guard).
bool debugEnabled()
{
    static const bool on = []{
        const char* v = std::getenv("POM2_DEBUG_DISK");
        return v && *v && *v != '0';
    }();
    return on;
}

}  // namespace

DiskIICard::DiskIICard()
{
    bootRom.fill(0xFF);
    // Pre-fill with the published 16-sector P6 PROM so the LSS path
    // works out-of-the-box. `loadLssRom()` can override this with a
    // verified dump from `roms/diskii_p6.rom`. `p6RomLoaded` stays
    // false until an explicit load — when false, `useBitLss` also
    // stays false (legacy gate path) so cycle accounting and test
    // expectations match the pre-LSS behaviour.
    std::memcpy(p6Rom.data(), kP6RomDefault, sizeof(kP6RomDefault));
}

bool DiskIICard::loadBootRom(const std::string& path)
{
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        pom2::log().warn("Disk II", "Cannot open boot PROM: " + path);
        return false;
    }
    f.seekg(0, std::ios::end);
    const auto size = static_cast<size_t>(f.tellg());
    f.seekg(0, std::ios::beg);
    if (size != 256) {
        pom2::log().warn("Disk II",
            "Boot PROM must be 256 bytes, got " + std::to_string(size));
        return false;
    }
    f.read(reinterpret_cast<char*>(bootRom.data()), 256);
    if (!f) {
        pom2::log().warn("Disk II", "Short read on " + path);
        return false;
    }
    bootRomLoaded = true;
    pom2::log().info("Disk II", "Boot PROM loaded: " + path);
    return true;
}

bool DiskIICard::loadLssRom(const std::string& path)
{
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        pom2::log().info("Disk II",
            "P6 LSS PROM not found at " + path +
            " — using legacy 32-cycle gate");
        return false;
    }
    f.seekg(0, std::ios::end);
    const auto size = static_cast<size_t>(f.tellg());
    f.seekg(0, std::ios::beg);
    if (size != 256) {
        pom2::log().warn("Disk II",
            "P6 LSS PROM must be 256 bytes, got " + std::to_string(size) +
            " — using legacy 32-cycle gate");
        return false;
    }
    f.read(reinterpret_cast<char*>(p6Rom.data()), 256);
    if (!f) {
        pom2::log().warn("Disk II", "Short read on " + path);
        return false;
    }
    p6RomLoaded = true;
    pom2::log().info("Disk II", "P6 LSS PROM loaded: " + path);
    return true;
}

bool DiskIICard::insertDisk(const std::string& path)
{
    // Save any pending writes from the previous image before we drop it.
    if (image.isLoaded() && image.hasUnsavedChanges()) {
        if (!image.saveDirty()) {
            pom2::log().warn("Disk II",
                "Save-on-swap failed: " + image.getLastError());
        }
    }
    if (!image.loadFile(path)) {
        pom2::log().warn("Disk II", "Insert failed: " + image.getLastError());
        return false;
    }
    image.setWriteBackEnabled(writeBackEnabled);
    trackPos    = 0;
    cycleAccum  = 0;
    writeLatch  = 0xFF;
    // Reset LSS bit-stream cursor + state. The default P6 ROM is in
    // p6Rom (see constructor) so the LSS path works without the
    // optional roms/diskii_p6.rom override. We still gate on
    // `p6RomLoaded` so the user can opt out by removing the file.
    bitPos           = 0;
    subCellTick      = 0;
    address          = 0x10;          // !PULSE high (no pulse), state=0
    lssData          = 0;
    writeShifter     = 0;
    writeShifterBits = 0;
    // Active iff P6 PROM file was loaded explicitly via loadLssRom.
    // The embedded default is also valid (and MAME-layout) but the
    // gating keeps the legacy 32-cycle gate available for tests until
    // the LSS write path matches MAME's flux model end-to-end (Phase
    // 2/3 work, then Phase 6 deletes the legacy fallback).
    useBitLss        = p6RomLoaded;
    return true;
}

void DiskIICard::ejectDisk()
{
    if (image.isLoaded() && image.hasUnsavedChanges()) {
        if (!image.saveDirty()) {
            pom2::log().warn("Disk II",
                "Save-on-eject failed: " + image.getLastError());
        }
    }
    image.eject();
    trackPos = 0;
    writeLatch = 0xFF;
}

uint8_t DiskIICard::slotRomRead(uint8_t low8)
{
    if (debugEnabled() && !trace.sawSlotRom) {
        trace.sawSlotRom = true;
        char buf[64];
        std::snprintf(buf, sizeof(buf),
            "PROM entered (first slot ROM read at offset $%02X)", low8);
        pom2::log().info("Disk II", buf);
    }
    return bootRom[low8];
}

void DiskIICard::onReset()
{
    motorOn   = false;
    motorOffDelay = 0;
    writeMode = false;
    loadMode  = false;
    phaseOn   = {};
    cycleAccum = 0;
    dataLatch  = 0;
    byteReady  = false;
    // LSS state. Real Disk II hardware does NOT lose the head's bit-
    // stream alignment on a soft (Ctrl-Reset) — the disk keeps spinning
    // and the LSS shift register settles back to a stable value within
    // the next sync gap. We zero the address (state=0, QA=0) and data
    // register to start from a clean PROM state, with bit 4 of address
    // (!PULSE) high — no pulse pending. bitPos / subCellTick survive
    // (the PROM re-syncs naturally on the next sync run).
    address          = 0x10;
    lssData          = 0;
    writeShifter     = 0;
    writeShifterBits = 0;
    trace = {};
    // Head position and trackPos are intentionally NOT reset — a real
    // Disk II loses neither when the host CPU is reset; the boot PROM
    // re-recalibrates by stepping phase 0 a bunch of times anyway.
}

void DiskIICard::seekPhaseW(int phases)
{
    // Verbatim port of MAME `floppy_image_device::seek_phase_w` — looks
    // at the *full* 4-bit phase mask and drops the head into the well
    // of whichever 1- or 2-magnet pattern is energized, with motion
    // capped at ±4 quarter-tracks per call. This replaces the prior
    // edge-detection model, which only stepped on rising edges and
    // missed sub-half-track positions used by Copy II Plus's analyzer
    // and by quarter-track copy protection schemes.
    //
    // Phase-mask -> well position (8 wells per "phase cycle"; each cycle
    // covers 2 tracks of head travel — 4 quarter-tracks per track):
    //   0x1 -> 0   0x3 -> 1   0x2 -> 2   0x6 -> 3
    //   0x4 -> 4   0xC -> 5   0x8 -> 6   0x9 -> 7
    // Anything else (no magnet, opposing magnets like 0x5 / 0xA, or 3+
    // simultaneously) leaves the head where it was.
    static constexpr int reqPosTable[16] = {
        -1, /*0x0 idle*/
         0, /*0x1*/
         2, /*0x2*/
         1, /*0x3*/
         4, /*0x4*/
        -1, /*0x5 opposing 0+2*/
         3, /*0x6*/
        -1, /*0x7 three magnets*/
         6, /*0x8*/
         7, /*0x9*/
        -1, /*0xA opposing 1+3*/
        -1, /*0xB three magnets*/
         5, /*0xC*/
        -1, /*0xD three magnets*/
        -1, /*0xE three magnets*/
        -1, /*0xF all four*/
    };
    const int req = reqPosTable[phases & 0xF];
    if (req < 0) return;

    const int cur = headQuarterTrack;
    // Opposite-phase pattern (e.g. cur in well 0 and req=4): head sits
    // between two opposing magnets and doesn't move.
    if (((cur ^ req) & 7) == 4) return;

    int next = (cur & ~7) | req;
    if (next < cur - 4) next += 8;
    else if (next > cur + 4) next -= 8;
    headQuarterTrack = std::clamp(next, 0, kQuarterTrackMax);
}

void DiskIICard::advanceCycles(int cycles)
{
    if (!motorOn || !image.isLoaded()) return;

    // Run the LSS for the cycle slice while the motor is providing data
    // (whether ACTIVE or in MODE_DELAY spin-down — both feed the LSS).
    // Real hardware: 2 LSS ticks per CPU cycle (LSS clock = 2.04 MHz,
    // CPU clock = 1.02 MHz). Each LSS tick runs one PROM lookup + ALU
    // op on the data register and consumes 1/8 of a bit cell.
    if (!useBitLss) {
        legacyAdvance(cycles);
    } else {
        int ticks = cycles * 2;
        while (ticks-- > 0) lssTick();
    }

    // Tick the spin-down delay. When it expires the motor truly stops.
    if (motorOffDelay > 0) {
        motorOffDelay -= cycles;
        if (motorOffDelay <= 0) {
            motorOffDelay = 0;
            motorOn       = false;
        }
    }
}

void DiskIICard::legacyAdvance(int cycles)
{
    cycleAccum += cycles;
    while (cycleAccum >= kCyclesPerNibble) {
        cycleAccum -= kCyclesPerNibble;
        trackPos  = (trackPos + 1) % DiskImage::kNibblesPerTrack;
        if (writeMode) {
            // Write the most-recently-latched nibble onto the track.
            // Real hardware streams bits through the LSS shift register;
            // we model one nibble per ~32 CPU cycles, matching the read
            // pacing. The CPU latches the next nibble via a soft-switch
            // store (see deviceSelectWrite).
            image.writeNibbleAt(headQuarterTrack / 4, trackPos, writeLatch);
            ++writeFlushCount;
        } else {
            dataLatch = image.nibbleAt(headQuarterTrack / 4, trackPos);
            byteReady = true;
        }
    }
}

// One LSS tick = 0.5 µs = 1/8 of a bit cell. Verbatim algorithm port of
// MAME `wozfdc.cpp lss_sync()` — the persistent `address` register
// shuffles state bits into PROM-pin positions exactly as the real
// 341-0028-A is wired:
//
//   (address & 0x1E) | (op & 0xC0) | ((op & 0x20) >> 5) | ((op & 0x10) << 1)
//
// preserving Q7/Q6/QA/!PULSE while injecting state[3,2,1,0] into address
// bits [7,6,0,5]. The PROM byte's high nibble re-encodes via the same
// pack on the next iteration; the low nibble is the ALU op on the data
// register. Below, PULSE detection still uses POM2's discrete bit-cell
// sampling (subCellTick==4); MAME's flux-event model arrives in Phase 2.
void DiskIICard::lssTick()
{
    if (!image.isLoaded()) return;

    const int track = headQuarterTrack / 4;
    const int len   = image.trackBitLength(track);

    // 1. Sample PULSE for the current sub-cell. A "1" cell carries a
    //    single PULSE at sub-tick 4; all other sub-ticks see PULSE=0.
    int pulse = 0;
    if (subCellTick == 4 && len > 0) {
        pulse = image.bitAt(track, bitPos) ? 1 : 0;
    }

    // 2. Refresh the externally-driven bits of the address register for
    //    THIS lookup: !PULSE (bit 4), Q7 (bit 3), Q6 (bit 2). The state
    //    bits (7,6,5,0) and QA (bit 1) carry forward from the bottom of
    //    the previous tick. Re-pinning Q6/Q7 each tick is defensive —
    //    handleSwitchAccess also keeps them aligned on soft-switch hits.
    address = static_cast<uint8_t>((address & ~0x1C)
            | (pulse ? 0x00 : 0x10)
            | (writeMode ? 0x08 : 0x00)
            | (loadMode  ? 0x04 : 0x00));

    // 3. PROM lookup at MAME's scrambled address.
    const uint8_t op = p6Rom[address];

    // 4. Dispatch low nibble = ALU op on data register. MAME's full
    //    range — every bit pattern is accounted for, so a stray opcode
    //    nibble can never silently fall through:
    //      0x0..0x7 CLR    data ← 0
    //      0x8, 0xC NOP
    //      0x9      SL0    data ← (data << 1)
    //      0xA, 0xE SR     data ← (data >> 1) | (WP ? 0x80 : 0)
    //      0xB, 0xF LD     data ← writeLatch
    //      0xD      SL1    data ← (data << 1) | 1
    switch (op & 0x0F) {
        case 0x0: case 0x1: case 0x2: case 0x3:
        case 0x4: case 0x5: case 0x6: case 0x7:
            lssData = 0;
            break;
        case 0x8: case 0xC:
            break;
        case 0x9:
            lssData = static_cast<uint8_t>(lssData << 1);
            break;
        case 0xA: case 0xE:
            lssData = static_cast<uint8_t>((lssData >> 1)
                | (image.isWriteProtected() ? 0x80 : 0x00));
            break;
        case 0xB: case 0xF:
            lssData = writeLatch;
            break;
        case 0xD:
            lssData = static_cast<uint8_t>((lssData << 1) | 0x01);
            break;
        default:
            break;
    }

    // 5. Update the state bits of address (7,6,5,0) from the opcode
    //    bits (7,6,4,5) using MAME's exact PROM-pin pack, and refresh
    //    QA (bit 1) from the new data MSB.
    address = static_cast<uint8_t>((address & 0x1E)
            | (op & 0xC0)
            | ((op & 0x20) >> 5)
            | ((op & 0x10) << 1));
    if (lssData & 0x80) address |= 0x02; else address &= ~0x02;

    // 6. Sub-cell tick advance, write accumulation, bit-cell wrap. Phase 1
    //    keeps the existing nibble-buffer write path: at each cell
    //    boundary, sample WRITE_DATA = address bit 7 (= new state[3] =
    //    opcode bit 7) and shift it into writeShifter; flush a complete
    //    nibble every 8 cells. Phase 3 will replace this with a flux
    //    transition buffer feeding image.writeFlux().
    if (++subCellTick == 8) {
        subCellTick = 0;
        if (writeMode) {
            const bool writeBit = (address & 0x80) != 0;
            writeShifter = static_cast<uint8_t>((writeShifter << 1)
                | (writeBit ? 1 : 0));
            if (++writeShifterBits == 8) {
                if (writeBackEnabled) {
                    image.writeNibbleAt(track, trackPos, writeShifter);
                    ++writeFlushCount;
                }
                trackPos = (trackPos + 1) % DiskImage::kNibblesPerTrack;
                writeShifterBits = 0;
            }
        }
        if (len > 0) bitPos = (bitPos + 1) % len;
    }
}

void DiskIICard::handleSwitchAccess(uint8_t low4)
{
    if (debugEnabled() && !trace.sawDevSelect) {
        trace.sawDevSelect = true;
        char buf[64];
        std::snprintf(buf, sizeof(buf),
            "first soft switch hit (low4=$%X)", low4);
        pom2::log().info("Disk II", buf);
    }

    if (low4 < 8) {
        const int  phase = low4 >> 1;
        const bool on    = (low4 & 1) != 0;
        phaseOn[phase]   = on;
        // Pack the 4-bit magnet mask and let the MAME-faithful stepper
        // settle the head into the matching well. Calling on every
        // soft-switch hit (rising AND falling) is what gives quarter-
        // track resolution — edge-detection alone would miss patterns
        // like "phase 0 alone" -> "phases 0+1 together" -> "phase 1 alone"
        // which Copy II Plus uses to land on odd quarter-tracks.
        int mask = 0;
        for (int i = 0; i < 4; ++i) if (phaseOn[i]) mask |= (1 << i);
        seekPhaseW(mask);
        return;
    }
    switch (low4) {
        case 0x8:
            // MAME's MODE_DELAY: schedule the motor to actually stop in
            // ~1 second of cycles. Data keeps flowing in the meantime;
            // a fresh motor-on within the window cancels the spin-down
            // and avoids paying re-spin-up latency. Re-arming an already
            // running countdown would extend it; only arm if idle.
            //
            // Gated on useBitLss because the legacy 32-cycle gate is a
            // deterministic clock model with no flux-time concept — its
            // trackPos walks unconditionally per CPU cycle, so extending
            // the "motor on" window puts it out of sync with DOS RWTS
            // motor-off-during-processing. The MAME flux model in
            // Phase 2/3 will retire this branch (and the gate itself).
            if (useBitLss) {
                if (motorOn && motorOffDelay == 0) {
                    motorOffDelay = 1'022'727;  // 1 sec @ 1.0227 MHz
                }
            } else {
                motorOn       = false;
                motorOffDelay = 0;
            }
            break;
        case 0x9:
            if (!motorOn) {
                cycleAccum = 0;
                if (debugEnabled() && !trace.sawMotorOn) {
                    trace.sawMotorOn = true;
                    char buf[96];
                    std::snprintf(buf, sizeof(buf),
                        "motor ON (head at quarter-track %d, disk %s)",
                        headQuarterTrack,
                        image.isLoaded() ? "loaded" : "MISSING");
                    pom2::log().info("Disk II", buf);
                }
            }
            motorOn = true;
            motorOffDelay = 0;       // cancel any pending spin-down
            break;
        case 0xA: /* drive 1 select — only drive modelled */ break;
        case 0xB: /* drive 2 select — silently ignored      */ break;
        case 0xC: loadMode  = false; break;     // Q6L
        case 0xD: loadMode  = true;  break;     // Q6H
        case 0xE: writeMode = false; break;     // Q7L
        case 0xF: writeMode = true;  break;     // Q7H (no-op for read-only)
        default: break;
    }
}

uint8_t DiskIICard::deviceSelectRead(uint8_t low4)
{
    handleSwitchAccess(low4);

    // $C0nC in (Q6 low, Q7 low) = read mode → return current track nibble.
    // The DOS 3.3 fast read loop is `LDA $C0EC ; BPL loop` — every valid
    // GCR nibble has bit-7 set, so the BPL terminates immediately.
    if (low4 == 0xC && !writeMode && !loadMode) {
        if (!image.isLoaded() || !motorOn) return 0xFF;
        if (useBitLss) {
            // MAME's `read_data_register` ticks the LSS once *before*
            // sampling the data register — this models the real read-
            // pipe latency where the latched value the CPU sees was
            // valid one LSS clock ago. Without this, address marks
            // arrive one bit early in the BPL spin.
            lssTick();
            if (debugEnabled() && (lssData & 0x80) && !trace.sawFirstNibble) {
                trace.sawFirstNibble = true;
                char buf[96];
                std::snprintf(buf, sizeof(buf),
                    "first GCR nibble served: $%02X (LSS, track %d, bit %d)",
                    lssData, headQuarterTrack / 4, bitPos);
                pom2::log().info("Disk II", buf);
            }
            return lssData;
        }
        // Legacy gate. Bit-7 of the data register goes high only after a
        // full nibble has shifted in. While `byteReady` is false, the PROM
        // sees a "still assembling" value — bit-7 clear keeps the BPL spin
        // running until advanceCycles latches the next nibble. After one
        // successful read the latch stays valid (real hardware doesn't
        // clear it on read), but `byteReady` drops back to false so the
        // next LDA waits the full 32-cycle window.
        const uint8_t out = byteReady ? dataLatch : (dataLatch & 0x7F);
        if (debugEnabled() && byteReady && !trace.sawFirstNibble) {
            trace.sawFirstNibble = true;
            char buf[96];
            std::snprintf(buf, sizeof(buf),
                "first GCR nibble served: $%02X (track %d, pos %d)",
                dataLatch, headQuarterTrack / 4, trackPos);
            pom2::log().info("Disk II", buf);
        }
        byteReady = false;
        return out;
    }
    // $C0nD in (Q6 high, Q7 low) = write-protect probe. Bit-7 set means
    // protected; reflects the user's write-back opt-in. When write-back
    // is OFF (default) we return protected, so DOS will SAVE-error
    // before scrambling the in-memory nibble buffer. Once the user opts
    // in, the disk reports writable and updates land back in the file.
    if (low4 == 0xD && !writeMode) {
        if (!image.isLoaded()) return 0x00;
        return image.isWriteProtected() ? 0x80 : 0x00;
    }
    // MAME open-bus semantic: every other slot in $C0E0..$C0EF leaves
    // the data bus floating, and the last value the controller drove
    // there is the data register. Software like Bag of Tricks polls
    // these slots assuming the data register's high bit reflects the
    // most recent nibble. POM2 used to return 0 (== "ready, no nibble"),
    // which broke that probe pattern.
    return useBitLss ? lssData : 0;
}

void DiskIICard::deviceSelectWrite(uint8_t low4, uint8_t v)
{
    // Apple II soft switches respond to writes too — DOS 3.3 occasionally
    // pokes them via STA. We only need the side-effect, not the value
    // for control switches; for $C0nD in WRITE mode (Q6H + Q7H) the store
    // loads the LSS data latch. $C0nC stores are SHIFT strobes on real
    // hardware (Sather "Understanding the Apple II" 9-13) — they do not
    // load the latch register.
    handleSwitchAccess(low4);
    if (writeMode && low4 == 0xD) {
        writeLatch = v;
        // Realign the LSS to the CPU's store cadence. Real Disk II
        // hardware reloads its WRITE shift register from the data latch
        // at the start of every 8-bit cell; if the CPU's store-to-store
        // interval drifts a few cycles past 32 (DOS RWTS WRITE6 has
        // small gaps between the data prologue and the first secondary
        // nibble — bookkeeping, not part of the inner write loop), our
        // free-running cycleAccum would overflow and flush a duplicate
        // of the still-stale latch into the next nibble slot. That
        // extra nibble shifts the running-XOR checksum and DOS reports
        // I/O ERROR. Resetting cycleAccum here pins each flush to
        // exactly 32 cycles after the most recent latch load — which
        // matches DOS's intent and AppleWin's per-access LSS sync
        // (Disk_t::DataLatchWriteWOZ → UpdateBitStreamOffsets).
        cycleAccum = 0;
    }
}
