# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gistarcade/src/POM2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gistarcade/src/POM2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gistarcade/src/POM2/CMakeFiles /home/gistarcade/src/POM2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gistarcade/src/POM2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pom2_imgui

# Build rule for target.
pom2_imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pom2_imgui
.PHONY : pom2_imgui

# fast build rule for target.
pom2_imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/build
.PHONY : pom2_imgui/fast

#=============================================================================
# Target rules for targets named pom2_headless

# Build rule for target.
pom2_headless: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pom2_headless
.PHONY : pom2_headless

# fast build rule for target.
pom2_headless/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/build
.PHONY : pom2_headless/fast

#=============================================================================
# Target rules for targets named test_klaus_6502

# Build rule for target.
test_klaus_6502: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_klaus_6502
.PHONY : test_klaus_6502

# fast build rule for target.
test_klaus_6502/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_klaus_6502.dir/build.make tests/CMakeFiles/test_klaus_6502.dir/build
.PHONY : test_klaus_6502/fast

#=============================================================================
# Target rules for targets named test_klaus_65c02

# Build rule for target.
test_klaus_65c02: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_klaus_65c02
.PHONY : test_klaus_65c02

# fast build rule for target.
test_klaus_65c02/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_klaus_65c02.dir/build.make tests/CMakeFiles/test_klaus_65c02.dir/build
.PHONY : test_klaus_65c02/fast

#=============================================================================
# Target rules for targets named test_system_profile

# Build rule for target.
test_system_profile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_system_profile
.PHONY : test_system_profile

# fast build rule for target.
test_system_profile/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_system_profile.dir/build.make tests/CMakeFiles/test_system_profile.dir/build
.PHONY : test_system_profile/fast

#=============================================================================
# Target rules for targets named test_snapshot_io

# Build rule for target.
test_snapshot_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_snapshot_io
.PHONY : test_snapshot_io

# fast build rule for target.
test_snapshot_io/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_snapshot_io.dir/build.make tests/CMakeFiles/test_snapshot_io.dir/build
.PHONY : test_snapshot_io/fast

#=============================================================================
# Target rules for targets named test_slot_bus

# Build rule for target.
test_slot_bus: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_slot_bus
.PHONY : test_slot_bus

# fast build rule for target.
test_slot_bus/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_slot_bus.dir/build.make tests/CMakeFiles/test_slot_bus.dir/build
.PHONY : test_slot_bus/fast

#=============================================================================
# Target rules for targets named test_paste

# Build rule for target.
test_paste: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_paste
.PHONY : test_paste

# fast build rule for target.
test_paste/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_paste.dir/build.make tests/CMakeFiles/test_paste.dir/build
.PHONY : test_paste/fast

#=============================================================================
# Target rules for targets named test_language_card

# Build rule for target.
test_language_card: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_language_card
.PHONY : test_language_card

# fast build rule for target.
test_language_card/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_language_card.dir/build.make tests/CMakeFiles/test_language_card.dir/build
.PHONY : test_language_card/fast

#=============================================================================
# Target rules for targets named test_hdv_card

# Build rule for target.
test_hdv_card: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hdv_card
.PHONY : test_hdv_card

# fast build rule for target.
test_hdv_card/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_hdv_card.dir/build.make tests/CMakeFiles/test_hdv_card.dir/build
.PHONY : test_hdv_card/fast

#=============================================================================
# Target rules for targets named test_hdv_writeback

# Build rule for target.
test_hdv_writeback: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hdv_writeback
.PHONY : test_hdv_writeback

# fast build rule for target.
test_hdv_writeback/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_hdv_writeback.dir/build.make tests/CMakeFiles/test_hdv_writeback.dir/build
.PHONY : test_hdv_writeback/fast

#=============================================================================
# Target rules for targets named test_prodos_volume

# Build rule for target.
test_prodos_volume: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_prodos_volume
.PHONY : test_prodos_volume

# fast build rule for target.
test_prodos_volume/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_prodos_volume.dir/build.make tests/CMakeFiles/test_prodos_volume.dir/build
.PHONY : test_prodos_volume/fast

#=============================================================================
# Target rules for targets named test_vbl

# Build rule for target.
test_vbl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_vbl
.PHONY : test_vbl

# fast build rule for target.
test_vbl/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_vbl.dir/build.make tests/CMakeFiles/test_vbl.dir/build
.PHONY : test_vbl/fast

#=============================================================================
# Target rules for targets named test_speaker

# Build rule for target.
test_speaker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_speaker
.PHONY : test_speaker

# fast build rule for target.
test_speaker/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_speaker.dir/build.make tests/CMakeFiles/test_speaker.dir/build
.PHONY : test_speaker/fast

#=============================================================================
# Target rules for targets named test_hgr_render

# Build rule for target.
test_hgr_render: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hgr_render
.PHONY : test_hgr_render

# fast build rule for target.
test_hgr_render/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_hgr_render.dir/build.make tests/CMakeFiles/test_hgr_render.dir/build
.PHONY : test_hgr_render/fast

#=============================================================================
# Target rules for targets named test_le_chat_mauve

# Build rule for target.
test_le_chat_mauve: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_le_chat_mauve
.PHONY : test_le_chat_mauve

# fast build rule for target.
test_le_chat_mauve/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_le_chat_mauve.dir/build.make tests/CMakeFiles/test_le_chat_mauve.dir/build
.PHONY : test_le_chat_mauve/fast

#=============================================================================
# Target rules for targets named test_disk_image

# Build rule for target.
test_disk_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_disk_image
.PHONY : test_disk_image

# fast build rule for target.
test_disk_image/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_disk_image.dir/build.make tests/CMakeFiles/test_disk_image.dir/build
.PHONY : test_disk_image/fast

#=============================================================================
# Target rules for targets named test_diskii_lss

# Build rule for target.
test_diskii_lss: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_diskii_lss
.PHONY : test_diskii_lss

# fast build rule for target.
test_diskii_lss/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_diskii_lss.dir/build.make tests/CMakeFiles/test_diskii_lss.dir/build
.PHONY : test_diskii_lss/fast

#=============================================================================
# Target rules for targets named test_mame_lss_parity

# Build rule for target.
test_mame_lss_parity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mame_lss_parity
.PHONY : test_mame_lss_parity

# fast build rule for target.
test_mame_lss_parity/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mame_lss_parity.dir/build.make tests/CMakeFiles/test_mame_lss_parity.dir/build
.PHONY : test_mame_lss_parity/fast

#=============================================================================
# Target rules for targets named test_disk_writeback

# Build rule for target.
test_disk_writeback: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_disk_writeback
.PHONY : test_disk_writeback

# fast build rule for target.
test_disk_writeback/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_disk_writeback.dir/build.make tests/CMakeFiles/test_disk_writeback.dir/build
.PHONY : test_disk_writeback/fast

#=============================================================================
# Target rules for targets named test_disk_write_controller

# Build rule for target.
test_disk_write_controller: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_disk_write_controller
.PHONY : test_disk_write_controller

# fast build rule for target.
test_disk_write_controller/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_disk_write_controller.dir/build.make tests/CMakeFiles/test_disk_write_controller.dir/build
.PHONY : test_disk_write_controller/fast

#=============================================================================
# Target rules for targets named test_woz_load

# Build rule for target.
test_woz_load: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_woz_load
.PHONY : test_woz_load

# fast build rule for target.
test_woz_load/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_woz_load.dir/build.make tests/CMakeFiles/test_woz_load.dir/build
.PHONY : test_woz_load/fast

#=============================================================================
# Target rules for targets named test_disk_drive2

# Build rule for target.
test_disk_drive2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_disk_drive2
.PHONY : test_disk_drive2

# fast build rule for target.
test_disk_drive2/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_disk_drive2.dir/build.make tests/CMakeFiles/test_disk_drive2.dir/build
.PHONY : test_disk_drive2/fast

#=============================================================================
# Target rules for targets named test_disk_boot

# Build rule for target.
test_disk_boot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_disk_boot
.PHONY : test_disk_boot

# fast build rule for target.
test_disk_boot/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_disk_boot.dir/build.make tests/CMakeFiles/test_disk_boot.dir/build
.PHONY : test_disk_boot/fast

#=============================================================================
# Target rules for targets named test_dos33_save

# Build rule for target.
test_dos33_save: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dos33_save
.PHONY : test_dos33_save

# fast build rule for target.
test_dos33_save/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_dos33_save.dir/build.make tests/CMakeFiles/test_dos33_save.dir/build
.PHONY : test_dos33_save/fast

#=============================================================================
# Target rules for targets named test_prodos_save

# Build rule for target.
test_prodos_save: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_prodos_save
.PHONY : test_prodos_save

# fast build rule for target.
test_prodos_save/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_prodos_save.dir/build.make tests/CMakeFiles/test_prodos_save.dir/build
.PHONY : test_prodos_save/fast

#=============================================================================
# Target rules for targets named c2plus_boot_probe

# Build rule for target.
c2plus_boot_probe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c2plus_boot_probe
.PHONY : c2plus_boot_probe

# fast build rule for target.
c2plus_boot_probe/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/c2plus_boot_probe.dir/build.make tests/CMakeFiles/c2plus_boot_probe.dir/build
.PHONY : c2plus_boot_probe/fast

#=============================================================================
# Target rules for targets named copy2plus_boot_dump

# Build rule for target.
copy2plus_boot_dump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 copy2plus_boot_dump
.PHONY : copy2plus_boot_dump

# fast build rule for target.
copy2plus_boot_dump/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/copy2plus_boot_dump.dir/build.make tests/CMakeFiles/copy2plus_boot_dump.dir/build
.PHONY : copy2plus_boot_dump/fast

#=============================================================================
# Target rules for targets named test_iie_memory

# Build rule for target.
test_iie_memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_iie_memory
.PHONY : test_iie_memory

# fast build rule for target.
test_iie_memory/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_iie_memory.dir/build.make tests/CMakeFiles/test_iie_memory.dir/build
.PHONY : test_iie_memory/fast

#=============================================================================
# Target rules for targets named test_iie_lc_paging

# Build rule for target.
test_iie_lc_paging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_iie_lc_paging
.PHONY : test_iie_lc_paging

# fast build rule for target.
test_iie_lc_paging/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_iie_lc_paging.dir/build.make tests/CMakeFiles/test_iie_lc_paging.dir/build
.PHONY : test_iie_lc_paging/fast

#=============================================================================
# Target rules for targets named test_dhgr_render

# Build rule for target.
test_dhgr_render: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_dhgr_render
.PHONY : test_dhgr_render

# fast build rule for target.
test_dhgr_render/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_dhgr_render.dir/build.make tests/CMakeFiles/test_dhgr_render.dir/build
.PHONY : test_dhgr_render/fast

#=============================================================================
# Target rules for targets named test_cmos_6502

# Build rule for target.
test_cmos_6502: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cmos_6502
.PHONY : test_cmos_6502

# fast build rule for target.
test_cmos_6502/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cmos_6502.dir/build.make tests/CMakeFiles/test_cmos_6502.dir/build
.PHONY : test_cmos_6502/fast

#=============================================================================
# Target rules for targets named test_m68705_decode

# Build rule for target.
test_m68705_decode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_m68705_decode
.PHONY : test_m68705_decode

# fast build rule for target.
test_m68705_decode/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_m68705_decode.dir/build.make tests/CMakeFiles/test_m68705_decode.dir/build
.PHONY : test_m68705_decode/fast

#=============================================================================
# Target rules for targets named test_mc6821

# Build rule for target.
test_mc6821: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mc6821
.PHONY : test_mc6821

# fast build rule for target.
test_mc6821/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mc6821.dir/build.make tests/CMakeFiles/test_mc6821.dir/build
.PHONY : test_mc6821/fast

#=============================================================================
# Target rules for targets named test_mouse_card

# Build rule for target.
test_mouse_card: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mouse_card
.PHONY : test_mouse_card

# fast build rule for target.
test_mouse_card/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mouse_card.dir/build.make tests/CMakeFiles/test_mouse_card.dir/build
.PHONY : test_mouse_card/fast

#=============================================================================
# Target rules for targets named test_mouse_card_quadrature

# Build rule for target.
test_mouse_card_quadrature: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mouse_card_quadrature
.PHONY : test_mouse_card_quadrature

# fast build rule for target.
test_mouse_card_quadrature/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mouse_card_quadrature.dir/build.make tests/CMakeFiles/test_mouse_card_quadrature.dir/build
.PHONY : test_mouse_card_quadrature/fast

#=============================================================================
# Target rules for targets named test_slot_config

# Build rule for target.
test_slot_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_slot_config
.PHONY : test_slot_config

# fast build rule for target.
test_slot_config/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_slot_config.dir/build.make tests/CMakeFiles/test_slot_config.dir/build
.PHONY : test_slot_config/fast

#=============================================================================
# Target rules for targets named test_clock_card

# Build rule for target.
test_clock_card: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_clock_card
.PHONY : test_clock_card

# fast build rule for target.
test_clock_card/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_clock_card.dir/build.make tests/CMakeFiles/test_clock_card.dir/build
.PHONY : test_clock_card/fast

#=============================================================================
# Target rules for targets named test_mockingboard

# Build rule for target.
test_mockingboard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mockingboard
.PHONY : test_mockingboard

# fast build rule for target.
test_mockingboard/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mockingboard.dir/build.make tests/CMakeFiles/test_mockingboard.dir/build
.PHONY : test_mockingboard/fast

#=============================================================================
# Target rules for targets named test_ssc_acia

# Build rule for target.
test_ssc_acia: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ssc_acia
.PHONY : test_ssc_acia

# fast build rule for target.
test_ssc_acia/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ssc_acia.dir/build.make tests/CMakeFiles/test_ssc_acia.dir/build
.PHONY : test_ssc_acia/fast

#=============================================================================
# Target rules for targets named test_woz_writeback

# Build rule for target.
test_woz_writeback: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_woz_writeback
.PHONY : test_woz_writeback

# fast build rule for target.
test_woz_writeback/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_woz_writeback.dir/build.make tests/CMakeFiles/test_woz_writeback.dir/build
.PHONY : test_woz_writeback/fast

#=============================================================================
# Target rules for targets named hero_probe

# Build rule for target.
hero_probe: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hero_probe
.PHONY : hero_probe

# fast build rule for target.
hero_probe/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/hero_probe.dir/build.make tests/CMakeFiles/hero_probe.dir/build
.PHONY : hero_probe/fast

Apple2Display.o: Apple2Display.cpp.o
.PHONY : Apple2Display.o

# target to build an object file
Apple2Display.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Apple2Display.cpp.o
.PHONY : Apple2Display.cpp.o

Apple2Display.i: Apple2Display.cpp.i
.PHONY : Apple2Display.i

# target to preprocess a source file
Apple2Display.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Apple2Display.cpp.i
.PHONY : Apple2Display.cpp.i

Apple2Display.s: Apple2Display.cpp.s
.PHONY : Apple2Display.s

# target to generate assembly for a file
Apple2Display.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Apple2Display.cpp.s
.PHONY : Apple2Display.cpp.s

AudioDevice.o: AudioDevice.cpp.o
.PHONY : AudioDevice.o

# target to build an object file
AudioDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/AudioDevice.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/AudioDevice.cpp.o
.PHONY : AudioDevice.cpp.o

AudioDevice.i: AudioDevice.cpp.i
.PHONY : AudioDevice.i

# target to preprocess a source file
AudioDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/AudioDevice.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/AudioDevice.cpp.i
.PHONY : AudioDevice.cpp.i

AudioDevice.s: AudioDevice.cpp.s
.PHONY : AudioDevice.s

# target to generate assembly for a file
AudioDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/AudioDevice.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/AudioDevice.cpp.s
.PHONY : AudioDevice.cpp.s

CassetteDeck_ImGui.o: CassetteDeck_ImGui.cpp.o
.PHONY : CassetteDeck_ImGui.o

# target to build an object file
CassetteDeck_ImGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/CassetteDeck_ImGui.cpp.o
.PHONY : CassetteDeck_ImGui.cpp.o

CassetteDeck_ImGui.i: CassetteDeck_ImGui.cpp.i
.PHONY : CassetteDeck_ImGui.i

# target to preprocess a source file
CassetteDeck_ImGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/CassetteDeck_ImGui.cpp.i
.PHONY : CassetteDeck_ImGui.cpp.i

CassetteDeck_ImGui.s: CassetteDeck_ImGui.cpp.s
.PHONY : CassetteDeck_ImGui.s

# target to generate assembly for a file
CassetteDeck_ImGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/CassetteDeck_ImGui.cpp.s
.PHONY : CassetteDeck_ImGui.cpp.s

CassetteDevice.o: CassetteDevice.cpp.o
.PHONY : CassetteDevice.o

# target to build an object file
CassetteDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/CassetteDevice.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/CassetteDevice.cpp.o
.PHONY : CassetteDevice.cpp.o

CassetteDevice.i: CassetteDevice.cpp.i
.PHONY : CassetteDevice.i

# target to preprocess a source file
CassetteDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/CassetteDevice.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/CassetteDevice.cpp.i
.PHONY : CassetteDevice.cpp.i

CassetteDevice.s: CassetteDevice.cpp.s
.PHONY : CassetteDevice.s

# target to generate assembly for a file
CassetteDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/CassetteDevice.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/CassetteDevice.cpp.s
.PHONY : CassetteDevice.cpp.s

CliDispatcher.o: CliDispatcher.cpp.o
.PHONY : CliDispatcher.o

# target to build an object file
CliDispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/CliDispatcher.cpp.o
.PHONY : CliDispatcher.cpp.o

CliDispatcher.i: CliDispatcher.cpp.i
.PHONY : CliDispatcher.i

# target to preprocess a source file
CliDispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/CliDispatcher.cpp.i
.PHONY : CliDispatcher.cpp.i

CliDispatcher.s: CliDispatcher.cpp.s
.PHONY : CliDispatcher.s

# target to generate assembly for a file
CliDispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/CliDispatcher.cpp.s
.PHONY : CliDispatcher.cpp.s

ClockCard.o: ClockCard.cpp.o
.PHONY : ClockCard.o

# target to build an object file
ClockCard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/ClockCard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/ClockCard.cpp.o
.PHONY : ClockCard.cpp.o

ClockCard.i: ClockCard.cpp.i
.PHONY : ClockCard.i

# target to preprocess a source file
ClockCard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/ClockCard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/ClockCard.cpp.i
.PHONY : ClockCard.cpp.i

ClockCard.s: ClockCard.cpp.s
.PHONY : ClockCard.s

# target to generate assembly for a file
ClockCard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/ClockCard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/ClockCard.cpp.s
.PHONY : ClockCard.cpp.s

Disassembler6502.o: Disassembler6502.cpp.o
.PHONY : Disassembler6502.o

# target to build an object file
Disassembler6502.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Disassembler6502.cpp.o
.PHONY : Disassembler6502.cpp.o

Disassembler6502.i: Disassembler6502.cpp.i
.PHONY : Disassembler6502.i

# target to preprocess a source file
Disassembler6502.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Disassembler6502.cpp.i
.PHONY : Disassembler6502.cpp.i

Disassembler6502.s: Disassembler6502.cpp.s
.PHONY : Disassembler6502.s

# target to generate assembly for a file
Disassembler6502.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Disassembler6502.cpp.s
.PHONY : Disassembler6502.cpp.s

DiskController_ImGui.o: DiskController_ImGui.cpp.o
.PHONY : DiskController_ImGui.o

# target to build an object file
DiskController_ImGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/DiskController_ImGui.cpp.o
.PHONY : DiskController_ImGui.cpp.o

DiskController_ImGui.i: DiskController_ImGui.cpp.i
.PHONY : DiskController_ImGui.i

# target to preprocess a source file
DiskController_ImGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/DiskController_ImGui.cpp.i
.PHONY : DiskController_ImGui.cpp.i

DiskController_ImGui.s: DiskController_ImGui.cpp.s
.PHONY : DiskController_ImGui.s

# target to generate assembly for a file
DiskController_ImGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/DiskController_ImGui.cpp.s
.PHONY : DiskController_ImGui.cpp.s

DiskIICard.o: DiskIICard.cpp.o
.PHONY : DiskIICard.o

# target to build an object file
DiskIICard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/DiskIICard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/DiskIICard.cpp.o
.PHONY : DiskIICard.cpp.o

DiskIICard.i: DiskIICard.cpp.i
.PHONY : DiskIICard.i

# target to preprocess a source file
DiskIICard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/DiskIICard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/DiskIICard.cpp.i
.PHONY : DiskIICard.cpp.i

DiskIICard.s: DiskIICard.cpp.s
.PHONY : DiskIICard.s

# target to generate assembly for a file
DiskIICard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/DiskIICard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/DiskIICard.cpp.s
.PHONY : DiskIICard.cpp.s

DiskImage.o: DiskImage.cpp.o
.PHONY : DiskImage.o

# target to build an object file
DiskImage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/DiskImage.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/DiskImage.cpp.o
.PHONY : DiskImage.cpp.o

DiskImage.i: DiskImage.cpp.i
.PHONY : DiskImage.i

# target to preprocess a source file
DiskImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/DiskImage.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/DiskImage.cpp.i
.PHONY : DiskImage.cpp.i

DiskImage.s: DiskImage.cpp.s
.PHONY : DiskImage.s

# target to generate assembly for a file
DiskImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/DiskImage.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/DiskImage.cpp.s
.PHONY : DiskImage.cpp.s

EmulationController.o: EmulationController.cpp.o
.PHONY : EmulationController.o

# target to build an object file
EmulationController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/EmulationController.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/EmulationController.cpp.o
.PHONY : EmulationController.cpp.o

EmulationController.i: EmulationController.cpp.i
.PHONY : EmulationController.i

# target to preprocess a source file
EmulationController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/EmulationController.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/EmulationController.cpp.i
.PHONY : EmulationController.cpp.i

EmulationController.s: EmulationController.cpp.s
.PHONY : EmulationController.s

# target to generate assembly for a file
EmulationController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/EmulationController.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/EmulationController.cpp.s
.PHONY : EmulationController.cpp.s

HdvController_ImGui.o: HdvController_ImGui.cpp.o
.PHONY : HdvController_ImGui.o

# target to build an object file
HdvController_ImGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/HdvController_ImGui.cpp.o
.PHONY : HdvController_ImGui.cpp.o

HdvController_ImGui.i: HdvController_ImGui.cpp.i
.PHONY : HdvController_ImGui.i

# target to preprocess a source file
HdvController_ImGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/HdvController_ImGui.cpp.i
.PHONY : HdvController_ImGui.cpp.i

HdvController_ImGui.s: HdvController_ImGui.cpp.s
.PHONY : HdvController_ImGui.s

# target to generate assembly for a file
HdvController_ImGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/HdvController_ImGui.cpp.s
.PHONY : HdvController_ImGui.cpp.s

JoystickInput.o: JoystickInput.cpp.o
.PHONY : JoystickInput.o

# target to build an object file
JoystickInput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/JoystickInput.cpp.o
.PHONY : JoystickInput.cpp.o

JoystickInput.i: JoystickInput.cpp.i
.PHONY : JoystickInput.i

# target to preprocess a source file
JoystickInput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/JoystickInput.cpp.i
.PHONY : JoystickInput.cpp.i

JoystickInput.s: JoystickInput.cpp.s
.PHONY : JoystickInput.s

# target to generate assembly for a file
JoystickInput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/JoystickInput.cpp.s
.PHONY : JoystickInput.cpp.s

JoystickPanel_ImGui.o: JoystickPanel_ImGui.cpp.o
.PHONY : JoystickPanel_ImGui.o

# target to build an object file
JoystickPanel_ImGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/JoystickPanel_ImGui.cpp.o
.PHONY : JoystickPanel_ImGui.cpp.o

JoystickPanel_ImGui.i: JoystickPanel_ImGui.cpp.i
.PHONY : JoystickPanel_ImGui.i

# target to preprocess a source file
JoystickPanel_ImGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/JoystickPanel_ImGui.cpp.i
.PHONY : JoystickPanel_ImGui.cpp.i

JoystickPanel_ImGui.s: JoystickPanel_ImGui.cpp.s
.PHONY : JoystickPanel_ImGui.s

# target to generate assembly for a file
JoystickPanel_ImGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/JoystickPanel_ImGui.cpp.s
.PHONY : JoystickPanel_ImGui.cpp.s

LeChatMauveCard.o: LeChatMauveCard.cpp.o
.PHONY : LeChatMauveCard.o

# target to build an object file
LeChatMauveCard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/LeChatMauveCard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/LeChatMauveCard.cpp.o
.PHONY : LeChatMauveCard.cpp.o

LeChatMauveCard.i: LeChatMauveCard.cpp.i
.PHONY : LeChatMauveCard.i

# target to preprocess a source file
LeChatMauveCard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/LeChatMauveCard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/LeChatMauveCard.cpp.i
.PHONY : LeChatMauveCard.cpp.i

LeChatMauveCard.s: LeChatMauveCard.cpp.s
.PHONY : LeChatMauveCard.s

# target to generate assembly for a file
LeChatMauveCard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/LeChatMauveCard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/LeChatMauveCard.cpp.s
.PHONY : LeChatMauveCard.cpp.s

LeChatMauve_ImGui.o: LeChatMauve_ImGui.cpp.o
.PHONY : LeChatMauve_ImGui.o

# target to build an object file
LeChatMauve_ImGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/LeChatMauve_ImGui.cpp.o
.PHONY : LeChatMauve_ImGui.cpp.o

LeChatMauve_ImGui.i: LeChatMauve_ImGui.cpp.i
.PHONY : LeChatMauve_ImGui.i

# target to preprocess a source file
LeChatMauve_ImGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/LeChatMauve_ImGui.cpp.i
.PHONY : LeChatMauve_ImGui.cpp.i

LeChatMauve_ImGui.s: LeChatMauve_ImGui.cpp.s
.PHONY : LeChatMauve_ImGui.s

# target to generate assembly for a file
LeChatMauve_ImGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/LeChatMauve_ImGui.cpp.s
.PHONY : LeChatMauve_ImGui.cpp.s

M6502.o: M6502.cpp.o
.PHONY : M6502.o

# target to build an object file
M6502.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/M6502.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/M6502.cpp.o
.PHONY : M6502.cpp.o

M6502.i: M6502.cpp.i
.PHONY : M6502.i

# target to preprocess a source file
M6502.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/M6502.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/M6502.cpp.i
.PHONY : M6502.cpp.i

M6502.s: M6502.cpp.s
.PHONY : M6502.s

# target to generate assembly for a file
M6502.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/M6502.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/M6502.cpp.s
.PHONY : M6502.cpp.s

M68705P3.o: M68705P3.cpp.o
.PHONY : M68705P3.o

# target to build an object file
M68705P3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/M68705P3.cpp.o
.PHONY : M68705P3.cpp.o

M68705P3.i: M68705P3.cpp.i
.PHONY : M68705P3.i

# target to preprocess a source file
M68705P3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/M68705P3.cpp.i
.PHONY : M68705P3.cpp.i

M68705P3.s: M68705P3.cpp.s
.PHONY : M68705P3.s

# target to generate assembly for a file
M68705P3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/M68705P3.cpp.s
.PHONY : M68705P3.cpp.s

MC6821.o: MC6821.cpp.o
.PHONY : MC6821.o

# target to build an object file
MC6821.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MC6821.cpp.o
.PHONY : MC6821.cpp.o

MC6821.i: MC6821.cpp.i
.PHONY : MC6821.i

# target to preprocess a source file
MC6821.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MC6821.cpp.i
.PHONY : MC6821.cpp.i

MC6821.s: MC6821.cpp.s
.PHONY : MC6821.s

# target to generate assembly for a file
MC6821.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MC6821.cpp.s
.PHONY : MC6821.cpp.s

MainWindow.o: MainWindow.cpp.o
.PHONY : MainWindow.o

# target to build an object file
MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MainWindow.cpp.o
.PHONY : MainWindow.cpp.o

MainWindow.i: MainWindow.cpp.i
.PHONY : MainWindow.i

# target to preprocess a source file
MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MainWindow.cpp.i
.PHONY : MainWindow.cpp.i

MainWindow.s: MainWindow.cpp.s
.PHONY : MainWindow.s

# target to generate assembly for a file
MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MainWindow.cpp.s
.PHONY : MainWindow.cpp.s

MainWindow_MemoryMaps.o: MainWindow_MemoryMaps.cpp.o
.PHONY : MainWindow_MemoryMaps.o

# target to build an object file
MainWindow_MemoryMaps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MainWindow_MemoryMaps.cpp.o
.PHONY : MainWindow_MemoryMaps.cpp.o

MainWindow_MemoryMaps.i: MainWindow_MemoryMaps.cpp.i
.PHONY : MainWindow_MemoryMaps.i

# target to preprocess a source file
MainWindow_MemoryMaps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MainWindow_MemoryMaps.cpp.i
.PHONY : MainWindow_MemoryMaps.cpp.i

MainWindow_MemoryMaps.s: MainWindow_MemoryMaps.cpp.s
.PHONY : MainWindow_MemoryMaps.s

# target to generate assembly for a file
MainWindow_MemoryMaps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MainWindow_MemoryMaps.cpp.s
.PHONY : MainWindow_MemoryMaps.cpp.s

MainWindow_Slots.o: MainWindow_Slots.cpp.o
.PHONY : MainWindow_Slots.o

# target to build an object file
MainWindow_Slots.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MainWindow_Slots.cpp.o
.PHONY : MainWindow_Slots.cpp.o

MainWindow_Slots.i: MainWindow_Slots.cpp.i
.PHONY : MainWindow_Slots.i

# target to preprocess a source file
MainWindow_Slots.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MainWindow_Slots.cpp.i
.PHONY : MainWindow_Slots.cpp.i

MainWindow_Slots.s: MainWindow_Slots.cpp.s
.PHONY : MainWindow_Slots.s

# target to generate assembly for a file
MainWindow_Slots.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MainWindow_Slots.cpp.s
.PHONY : MainWindow_Slots.cpp.s

Memory.o: Memory.cpp.o
.PHONY : Memory.o

# target to build an object file
Memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Memory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/Memory.cpp.o
.PHONY : Memory.cpp.o

Memory.i: Memory.cpp.i
.PHONY : Memory.i

# target to preprocess a source file
Memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Memory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/Memory.cpp.i
.PHONY : Memory.cpp.i

Memory.s: Memory.cpp.s
.PHONY : Memory.s

# target to generate assembly for a file
Memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Memory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/Memory.cpp.s
.PHONY : Memory.cpp.s

MemoryViewer_ImGui.o: MemoryViewer_ImGui.cpp.o
.PHONY : MemoryViewer_ImGui.o

# target to build an object file
MemoryViewer_ImGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MemoryViewer_ImGui.cpp.o
.PHONY : MemoryViewer_ImGui.cpp.o

MemoryViewer_ImGui.i: MemoryViewer_ImGui.cpp.i
.PHONY : MemoryViewer_ImGui.i

# target to preprocess a source file
MemoryViewer_ImGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MemoryViewer_ImGui.cpp.i
.PHONY : MemoryViewer_ImGui.cpp.i

MemoryViewer_ImGui.s: MemoryViewer_ImGui.cpp.s
.PHONY : MemoryViewer_ImGui.s

# target to generate assembly for a file
MemoryViewer_ImGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MemoryViewer_ImGui.cpp.s
.PHONY : MemoryViewer_ImGui.cpp.s

Mockingboard.o: Mockingboard.cpp.o
.PHONY : Mockingboard.o

# target to build an object file
Mockingboard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Mockingboard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/Mockingboard.cpp.o
.PHONY : Mockingboard.cpp.o

Mockingboard.i: Mockingboard.cpp.i
.PHONY : Mockingboard.i

# target to preprocess a source file
Mockingboard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Mockingboard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/Mockingboard.cpp.i
.PHONY : Mockingboard.cpp.i

Mockingboard.s: Mockingboard.cpp.s
.PHONY : Mockingboard.s

# target to generate assembly for a file
Mockingboard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Mockingboard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/Mockingboard.cpp.s
.PHONY : Mockingboard.cpp.s

MouseCard.o: MouseCard.cpp.o
.PHONY : MouseCard.o

# target to build an object file
MouseCard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MouseCard.cpp.o
.PHONY : MouseCard.cpp.o

MouseCard.i: MouseCard.cpp.i
.PHONY : MouseCard.i

# target to preprocess a source file
MouseCard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MouseCard.cpp.i
.PHONY : MouseCard.cpp.i

MouseCard.s: MouseCard.cpp.s
.PHONY : MouseCard.s

# target to generate assembly for a file
MouseCard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/MouseCard.cpp.s
.PHONY : MouseCard.cpp.s

ProDOSHardDiskCard.o: ProDOSHardDiskCard.cpp.o
.PHONY : ProDOSHardDiskCard.o

# target to build an object file
ProDOSHardDiskCard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/ProDOSHardDiskCard.cpp.o
.PHONY : ProDOSHardDiskCard.cpp.o

ProDOSHardDiskCard.i: ProDOSHardDiskCard.cpp.i
.PHONY : ProDOSHardDiskCard.i

# target to preprocess a source file
ProDOSHardDiskCard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/ProDOSHardDiskCard.cpp.i
.PHONY : ProDOSHardDiskCard.cpp.i

ProDOSHardDiskCard.s: ProDOSHardDiskCard.cpp.s
.PHONY : ProDOSHardDiskCard.s

# target to generate assembly for a file
ProDOSHardDiskCard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/ProDOSHardDiskCard.cpp.s
.PHONY : ProDOSHardDiskCard.cpp.s

ProDOSVolume.o: ProDOSVolume.cpp.o
.PHONY : ProDOSVolume.o

# target to build an object file
ProDOSVolume.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/ProDOSVolume.cpp.o
.PHONY : ProDOSVolume.cpp.o

ProDOSVolume.i: ProDOSVolume.cpp.i
.PHONY : ProDOSVolume.i

# target to preprocess a source file
ProDOSVolume.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/ProDOSVolume.cpp.i
.PHONY : ProDOSVolume.cpp.i

ProDOSVolume.s: ProDOSVolume.cpp.s
.PHONY : ProDOSVolume.s

# target to generate assembly for a file
ProDOSVolume.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/ProDOSVolume.cpp.s
.PHONY : ProDOSVolume.cpp.s

RomLoader.o: RomLoader.cpp.o
.PHONY : RomLoader.o

# target to build an object file
RomLoader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/RomLoader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/RomLoader.cpp.o
.PHONY : RomLoader.cpp.o

RomLoader.i: RomLoader.cpp.i
.PHONY : RomLoader.i

# target to preprocess a source file
RomLoader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/RomLoader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/RomLoader.cpp.i
.PHONY : RomLoader.cpp.i

RomLoader.s: RomLoader.cpp.s
.PHONY : RomLoader.s

# target to generate assembly for a file
RomLoader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/RomLoader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/RomLoader.cpp.s
.PHONY : RomLoader.cpp.s

Settings.o: Settings.cpp.o
.PHONY : Settings.o

# target to build an object file
Settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Settings.cpp.o
.PHONY : Settings.cpp.o

Settings.i: Settings.cpp.i
.PHONY : Settings.i

# target to preprocess a source file
Settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Settings.cpp.i
.PHONY : Settings.cpp.i

Settings.s: Settings.cpp.s
.PHONY : Settings.s

# target to generate assembly for a file
Settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/Settings.cpp.s
.PHONY : Settings.cpp.s

SlotBus.o: SlotBus.cpp.o
.PHONY : SlotBus.o

# target to build an object file
SlotBus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SlotBus.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SlotBus.cpp.o
.PHONY : SlotBus.cpp.o

SlotBus.i: SlotBus.cpp.i
.PHONY : SlotBus.i

# target to preprocess a source file
SlotBus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SlotBus.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SlotBus.cpp.i
.PHONY : SlotBus.cpp.i

SlotBus.s: SlotBus.cpp.s
.PHONY : SlotBus.s

# target to generate assembly for a file
SlotBus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SlotBus.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SlotBus.cpp.s
.PHONY : SlotBus.cpp.s

SnapshotIO.o: SnapshotIO.cpp.o
.PHONY : SnapshotIO.o

# target to build an object file
SnapshotIO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SnapshotIO.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SnapshotIO.cpp.o
.PHONY : SnapshotIO.cpp.o

SnapshotIO.i: SnapshotIO.cpp.i
.PHONY : SnapshotIO.i

# target to preprocess a source file
SnapshotIO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SnapshotIO.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SnapshotIO.cpp.i
.PHONY : SnapshotIO.cpp.i

SnapshotIO.s: SnapshotIO.cpp.s
.PHONY : SnapshotIO.s

# target to generate assembly for a file
SnapshotIO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SnapshotIO.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SnapshotIO.cpp.s
.PHONY : SnapshotIO.cpp.s

SpeakerDevice.o: SpeakerDevice.cpp.o
.PHONY : SpeakerDevice.o

# target to build an object file
SpeakerDevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SpeakerDevice.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SpeakerDevice.cpp.o
.PHONY : SpeakerDevice.cpp.o

SpeakerDevice.i: SpeakerDevice.cpp.i
.PHONY : SpeakerDevice.i

# target to preprocess a source file
SpeakerDevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SpeakerDevice.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SpeakerDevice.cpp.i
.PHONY : SpeakerDevice.cpp.i

SpeakerDevice.s: SpeakerDevice.cpp.s
.PHONY : SpeakerDevice.s

# target to generate assembly for a file
SpeakerDevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SpeakerDevice.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SpeakerDevice.cpp.s
.PHONY : SpeakerDevice.cpp.s

SuperSerialCard.o: SuperSerialCard.cpp.o
.PHONY : SuperSerialCard.o

# target to build an object file
SuperSerialCard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SuperSerialCard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SuperSerialCard.cpp.o
.PHONY : SuperSerialCard.cpp.o

SuperSerialCard.i: SuperSerialCard.cpp.i
.PHONY : SuperSerialCard.i

# target to preprocess a source file
SuperSerialCard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SuperSerialCard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SuperSerialCard.cpp.i
.PHONY : SuperSerialCard.cpp.i

SuperSerialCard.s: SuperSerialCard.cpp.s
.PHONY : SuperSerialCard.s

# target to generate assembly for a file
SuperSerialCard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SuperSerialCard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SuperSerialCard.cpp.s
.PHONY : SuperSerialCard.cpp.s

SystemProfile.o: SystemProfile.cpp.o
.PHONY : SystemProfile.o

# target to build an object file
SystemProfile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SystemProfile.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SystemProfile.cpp.o
.PHONY : SystemProfile.cpp.o

SystemProfile.i: SystemProfile.cpp.i
.PHONY : SystemProfile.i

# target to preprocess a source file
SystemProfile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SystemProfile.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SystemProfile.cpp.i
.PHONY : SystemProfile.cpp.i

SystemProfile.s: SystemProfile.cpp.s
.PHONY : SystemProfile.s

# target to generate assembly for a file
SystemProfile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/SystemProfile.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/SystemProfile.cpp.s
.PHONY : SystemProfile.cpp.s

imgui/backends/imgui_impl_glfw.o: imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui/backends/imgui_impl_glfw.o

# target to build an object file
imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : imgui/backends/imgui_impl_glfw.cpp.o

imgui/backends/imgui_impl_glfw.i: imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : imgui/backends/imgui_impl_glfw.cpp.i

imgui/backends/imgui_impl_glfw.s: imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : imgui/backends/imgui_impl_glfw.cpp.s

imgui/backends/imgui_impl_opengl3.o: imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl3.o

# target to build an object file
imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.o

imgui/backends/imgui_impl_opengl3.i: imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.i

imgui/backends/imgui_impl_opengl3.s: imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : imgui/backends/imgui_impl_opengl3.cpp.s

imgui/imgui.o: imgui/imgui.cpp.o
.PHONY : imgui/imgui.o

# target to build an object file
imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui.cpp.o
.PHONY : imgui/imgui.cpp.o

imgui/imgui.i: imgui/imgui.cpp.i
.PHONY : imgui/imgui.i

# target to preprocess a source file
imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui.cpp.i
.PHONY : imgui/imgui.cpp.i

imgui/imgui.s: imgui/imgui.cpp.s
.PHONY : imgui/imgui.s

# target to generate assembly for a file
imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui.cpp.s
.PHONY : imgui/imgui.cpp.s

imgui/imgui_demo.o: imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.o

# target to build an object file
imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_demo.cpp.o
.PHONY : imgui/imgui_demo.cpp.o

imgui/imgui_demo.i: imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.i

# target to preprocess a source file
imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_demo.cpp.i
.PHONY : imgui/imgui_demo.cpp.i

imgui/imgui_demo.s: imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.s

# target to generate assembly for a file
imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_demo.cpp.s
.PHONY : imgui/imgui_demo.cpp.s

imgui/imgui_draw.o: imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.o

# target to build an object file
imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_draw.cpp.o
.PHONY : imgui/imgui_draw.cpp.o

imgui/imgui_draw.i: imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.i

# target to preprocess a source file
imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_draw.cpp.i
.PHONY : imgui/imgui_draw.cpp.i

imgui/imgui_draw.s: imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.s

# target to generate assembly for a file
imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_draw.cpp.s
.PHONY : imgui/imgui_draw.cpp.s

imgui/imgui_tables.o: imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.o

# target to build an object file
imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_tables.cpp.o
.PHONY : imgui/imgui_tables.cpp.o

imgui/imgui_tables.i: imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.i

# target to preprocess a source file
imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_tables.cpp.i
.PHONY : imgui/imgui_tables.cpp.i

imgui/imgui_tables.s: imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.s

# target to generate assembly for a file
imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_tables.cpp.s
.PHONY : imgui/imgui_tables.cpp.s

imgui/imgui_widgets.o: imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.o

# target to build an object file
imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_widgets.cpp.o
.PHONY : imgui/imgui_widgets.cpp.o

imgui/imgui_widgets.i: imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.i

# target to preprocess a source file
imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_widgets.cpp.i
.PHONY : imgui/imgui_widgets.cpp.i

imgui/imgui_widgets.s: imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.s

# target to generate assembly for a file
imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/imgui/imgui_widgets.cpp.s
.PHONY : imgui/imgui_widgets.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_imgui.dir/build.make CMakeFiles/pom2_imgui.dir/main.cpp.s
.PHONY : main.cpp.s

pom2_headless.o: pom2_headless.cpp.o
.PHONY : pom2_headless.o

# target to build an object file
pom2_headless.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/pom2_headless.cpp.o
.PHONY : pom2_headless.cpp.o

pom2_headless.i: pom2_headless.cpp.i
.PHONY : pom2_headless.i

# target to preprocess a source file
pom2_headless.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/pom2_headless.cpp.i
.PHONY : pom2_headless.cpp.i

pom2_headless.s: pom2_headless.cpp.s
.PHONY : pom2_headless.s

# target to generate assembly for a file
pom2_headless.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pom2_headless.dir/build.make CMakeFiles/pom2_headless.dir/pom2_headless.cpp.s
.PHONY : pom2_headless.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... c2plus_boot_probe"
	@echo "... copy2plus_boot_dump"
	@echo "... hero_probe"
	@echo "... pom2_headless"
	@echo "... pom2_imgui"
	@echo "... test_clock_card"
	@echo "... test_cmos_6502"
	@echo "... test_dhgr_render"
	@echo "... test_disk_boot"
	@echo "... test_disk_drive2"
	@echo "... test_disk_image"
	@echo "... test_disk_write_controller"
	@echo "... test_disk_writeback"
	@echo "... test_diskii_lss"
	@echo "... test_dos33_save"
	@echo "... test_hdv_card"
	@echo "... test_hdv_writeback"
	@echo "... test_hgr_render"
	@echo "... test_iie_lc_paging"
	@echo "... test_iie_memory"
	@echo "... test_klaus_6502"
	@echo "... test_klaus_65c02"
	@echo "... test_language_card"
	@echo "... test_le_chat_mauve"
	@echo "... test_m68705_decode"
	@echo "... test_mame_lss_parity"
	@echo "... test_mc6821"
	@echo "... test_mockingboard"
	@echo "... test_mouse_card"
	@echo "... test_mouse_card_quadrature"
	@echo "... test_paste"
	@echo "... test_prodos_save"
	@echo "... test_prodos_volume"
	@echo "... test_slot_bus"
	@echo "... test_slot_config"
	@echo "... test_snapshot_io"
	@echo "... test_speaker"
	@echo "... test_ssc_acia"
	@echo "... test_system_profile"
	@echo "... test_vbl"
	@echo "... test_woz_load"
	@echo "... test_woz_writeback"
	@echo "... Apple2Display.o"
	@echo "... Apple2Display.i"
	@echo "... Apple2Display.s"
	@echo "... AudioDevice.o"
	@echo "... AudioDevice.i"
	@echo "... AudioDevice.s"
	@echo "... CassetteDeck_ImGui.o"
	@echo "... CassetteDeck_ImGui.i"
	@echo "... CassetteDeck_ImGui.s"
	@echo "... CassetteDevice.o"
	@echo "... CassetteDevice.i"
	@echo "... CassetteDevice.s"
	@echo "... CliDispatcher.o"
	@echo "... CliDispatcher.i"
	@echo "... CliDispatcher.s"
	@echo "... ClockCard.o"
	@echo "... ClockCard.i"
	@echo "... ClockCard.s"
	@echo "... Disassembler6502.o"
	@echo "... Disassembler6502.i"
	@echo "... Disassembler6502.s"
	@echo "... DiskController_ImGui.o"
	@echo "... DiskController_ImGui.i"
	@echo "... DiskController_ImGui.s"
	@echo "... DiskIICard.o"
	@echo "... DiskIICard.i"
	@echo "... DiskIICard.s"
	@echo "... DiskImage.o"
	@echo "... DiskImage.i"
	@echo "... DiskImage.s"
	@echo "... EmulationController.o"
	@echo "... EmulationController.i"
	@echo "... EmulationController.s"
	@echo "... HdvController_ImGui.o"
	@echo "... HdvController_ImGui.i"
	@echo "... HdvController_ImGui.s"
	@echo "... JoystickInput.o"
	@echo "... JoystickInput.i"
	@echo "... JoystickInput.s"
	@echo "... JoystickPanel_ImGui.o"
	@echo "... JoystickPanel_ImGui.i"
	@echo "... JoystickPanel_ImGui.s"
	@echo "... LeChatMauveCard.o"
	@echo "... LeChatMauveCard.i"
	@echo "... LeChatMauveCard.s"
	@echo "... LeChatMauve_ImGui.o"
	@echo "... LeChatMauve_ImGui.i"
	@echo "... LeChatMauve_ImGui.s"
	@echo "... M6502.o"
	@echo "... M6502.i"
	@echo "... M6502.s"
	@echo "... M68705P3.o"
	@echo "... M68705P3.i"
	@echo "... M68705P3.s"
	@echo "... MC6821.o"
	@echo "... MC6821.i"
	@echo "... MC6821.s"
	@echo "... MainWindow.o"
	@echo "... MainWindow.i"
	@echo "... MainWindow.s"
	@echo "... MainWindow_MemoryMaps.o"
	@echo "... MainWindow_MemoryMaps.i"
	@echo "... MainWindow_MemoryMaps.s"
	@echo "... MainWindow_Slots.o"
	@echo "... MainWindow_Slots.i"
	@echo "... MainWindow_Slots.s"
	@echo "... Memory.o"
	@echo "... Memory.i"
	@echo "... Memory.s"
	@echo "... MemoryViewer_ImGui.o"
	@echo "... MemoryViewer_ImGui.i"
	@echo "... MemoryViewer_ImGui.s"
	@echo "... Mockingboard.o"
	@echo "... Mockingboard.i"
	@echo "... Mockingboard.s"
	@echo "... MouseCard.o"
	@echo "... MouseCard.i"
	@echo "... MouseCard.s"
	@echo "... ProDOSHardDiskCard.o"
	@echo "... ProDOSHardDiskCard.i"
	@echo "... ProDOSHardDiskCard.s"
	@echo "... ProDOSVolume.o"
	@echo "... ProDOSVolume.i"
	@echo "... ProDOSVolume.s"
	@echo "... RomLoader.o"
	@echo "... RomLoader.i"
	@echo "... RomLoader.s"
	@echo "... Settings.o"
	@echo "... Settings.i"
	@echo "... Settings.s"
	@echo "... SlotBus.o"
	@echo "... SlotBus.i"
	@echo "... SlotBus.s"
	@echo "... SnapshotIO.o"
	@echo "... SnapshotIO.i"
	@echo "... SnapshotIO.s"
	@echo "... SpeakerDevice.o"
	@echo "... SpeakerDevice.i"
	@echo "... SpeakerDevice.s"
	@echo "... SuperSerialCard.o"
	@echo "... SuperSerialCard.i"
	@echo "... SuperSerialCard.s"
	@echo "... SystemProfile.o"
	@echo "... SystemProfile.i"
	@echo "... SystemProfile.s"
	@echo "... imgui/backends/imgui_impl_glfw.o"
	@echo "... imgui/backends/imgui_impl_glfw.i"
	@echo "... imgui/backends/imgui_impl_glfw.s"
	@echo "... imgui/backends/imgui_impl_opengl3.o"
	@echo "... imgui/backends/imgui_impl_opengl3.i"
	@echo "... imgui/backends/imgui_impl_opengl3.s"
	@echo "... imgui/imgui.o"
	@echo "... imgui/imgui.i"
	@echo "... imgui/imgui.s"
	@echo "... imgui/imgui_demo.o"
	@echo "... imgui/imgui_demo.i"
	@echo "... imgui/imgui_demo.s"
	@echo "... imgui/imgui_draw.o"
	@echo "... imgui/imgui_draw.i"
	@echo "... imgui/imgui_draw.s"
	@echo "... imgui/imgui_tables.o"
	@echo "... imgui/imgui_tables.i"
	@echo "... imgui/imgui_tables.s"
	@echo "... imgui/imgui_widgets.o"
	@echo "... imgui/imgui_widgets.i"
	@echo "... imgui/imgui_widgets.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... pom2_headless.o"
	@echo "... pom2_headless.i"
	@echo "... pom2_headless.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

