# CMake generated Testfile for 
# Source directory: /home/gistarcade/src/POM2/tests
# Build directory: /home/gistarcade/src/POM2/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(klaus_6502_functional "/home/gistarcade/src/POM2/tests/test_klaus_6502" "/home/gistarcade/src/POM2/tests/klaus_6502_functional_test.bin")
set_tests_properties(klaus_6502_functional PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;73;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(klaus_65c02_extended "/home/gistarcade/src/POM2/tests/test_klaus_65c02" "/home/gistarcade/src/POM2/tests/65C02_extended_opcodes_test.bin")
set_tests_properties(klaus_65c02_extended PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;129;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(system_profile_smoke "/home/gistarcade/src/POM2/tests/test_system_profile")
set_tests_properties(system_profile_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;158;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(snapshot_io_smoke "/home/gistarcade/src/POM2/tests/test_snapshot_io")
set_tests_properties(snapshot_io_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;173;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(slot_bus_smoke "/home/gistarcade/src/POM2/tests/test_slot_bus")
set_tests_properties(slot_bus_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;187;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(paste_smoke "/home/gistarcade/src/POM2/tests/test_paste")
set_tests_properties(paste_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;211;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(language_card_smoke "/home/gistarcade/src/POM2/tests/test_language_card")
set_tests_properties(language_card_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;235;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(hdv_card_smoke "/home/gistarcade/src/POM2/tests/test_hdv_card")
set_tests_properties(hdv_card_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;261;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(hdv_writeback_smoke "/home/gistarcade/src/POM2/tests/test_hdv_writeback")
set_tests_properties(hdv_writeback_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;289;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(prodos_volume_smoke "/home/gistarcade/src/POM2/tests/test_prodos_volume")
set_tests_properties(prodos_volume_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;305;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(vbl_smoke "/home/gistarcade/src/POM2/tests/test_vbl")
set_tests_properties(vbl_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;330;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(irq_aggregator_smoke "/home/gistarcade/src/POM2/tests/test_irq_aggregator")
set_tests_properties(irq_aggregator_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;356;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(speaker_smoke "/home/gistarcade/src/POM2/tests/test_speaker")
set_tests_properties(speaker_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;369;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(hgr_render_smoke "/home/gistarcade/src/POM2/tests/test_hgr_render")
set_tests_properties(hgr_render_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;395;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(le_chat_mauve_smoke "/home/gistarcade/src/POM2/tests/test_le_chat_mauve")
set_tests_properties(le_chat_mauve_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;426;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(disk_image_smoke "/home/gistarcade/src/POM2/tests/test_disk_image")
set_tests_properties(disk_image_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;443;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(diskii_lss_smoke "/home/gistarcade/src/POM2/tests/test_diskii_lss")
set_tests_properties(diskii_lss_smoke PROPERTIES  TIMEOUT "10" WORKING_DIRECTORY "/home/gistarcade/src/POM2" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;478;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(mame_lss_parity_smoke "/home/gistarcade/src/POM2/tests/test_mame_lss_parity")
set_tests_properties(mame_lss_parity_smoke PROPERTIES  TIMEOUT "10" WORKING_DIRECTORY "/home/gistarcade/src/POM2" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;509;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(disk_writeback_smoke "/home/gistarcade/src/POM2/tests/test_disk_writeback")
set_tests_properties(disk_writeback_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;523;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(disk_write_controller_smoke "/home/gistarcade/src/POM2/tests/test_disk_write_controller")
set_tests_properties(disk_write_controller_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;542;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(woz_load_smoke "/home/gistarcade/src/POM2/tests/test_woz_load")
set_tests_properties(woz_load_smoke PROPERTIES  TIMEOUT "10" WORKING_DIRECTORY "/home/gistarcade/src/POM2" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;571;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(disk_drive2_smoke "/home/gistarcade/src/POM2/tests/test_disk_drive2")
set_tests_properties(disk_drive2_smoke PROPERTIES  TIMEOUT "10" WORKING_DIRECTORY "/home/gistarcade/src/POM2" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;599;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(disk_boot_smoke "/home/gistarcade/src/POM2/tests/test_disk_boot")
set_tests_properties(disk_boot_smoke PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;630;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(dos33_save_smoke "/home/gistarcade/src/POM2/tests/test_dos33_save")
set_tests_properties(dos33_save_smoke PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;659;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(prodos_save_smoke "/home/gistarcade/src/POM2/tests/test_prodos_save")
set_tests_properties(prodos_save_smoke PROPERTIES  TIMEOUT "90" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;687;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(iie_memory_smoke "/home/gistarcade/src/POM2/tests/test_iie_memory")
set_tests_properties(iie_memory_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;762;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(iie_lc_paging_smoke "/home/gistarcade/src/POM2/tests/test_iie_lc_paging")
set_tests_properties(iie_lc_paging_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;789;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(dhgr_render_smoke "/home/gistarcade/src/POM2/tests/test_dhgr_render")
set_tests_properties(dhgr_render_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;817;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(cmos_6502_smoke "/home/gistarcade/src/POM2/tests/test_cmos_6502")
set_tests_properties(cmos_6502_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;844;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(m68705_decode_smoke "/home/gistarcade/src/POM2/tests/test_m68705_decode")
set_tests_properties(m68705_decode_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;871;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(mc6821_smoke "/home/gistarcade/src/POM2/tests/test_mc6821")
set_tests_properties(mc6821_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;886;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(mouse_card_smoke "/home/gistarcade/src/POM2/tests/test_mouse_card")
set_tests_properties(mouse_card_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;915;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(mouse_card_quadrature_smoke "/home/gistarcade/src/POM2/tests/test_mouse_card_quadrature")
set_tests_properties(mouse_card_quadrature_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;944;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(slot_config_smoke "/home/gistarcade/src/POM2/tests/test_slot_config")
set_tests_properties(slot_config_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;978;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(clock_card_smoke "/home/gistarcade/src/POM2/tests/test_clock_card")
set_tests_properties(clock_card_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;1005;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(mockingboard_smoke "/home/gistarcade/src/POM2/tests/test_mockingboard")
set_tests_properties(mockingboard_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;1040;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(ssc_acia_smoke "/home/gistarcade/src/POM2/tests/test_ssc_acia")
set_tests_properties(ssc_acia_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;1070;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
add_test(woz_writeback_smoke "/home/gistarcade/src/POM2/tests/test_woz_writeback")
set_tests_properties(woz_writeback_smoke PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/gistarcade/src/POM2/tests/CMakeLists.txt;1087;add_test;/home/gistarcade/src/POM2/tests/CMakeLists.txt;0;")
