#!/usr/bin/env bash
# POM2 — file-size ratchet.
#
# TODO.md carries a standing architectural rule: "do not grow the god-objects",
# target < 3000 lines per file. It had no mechanism, and the measurement says
# what a rule without a mechanism is worth — src/MainWindow.cpp went 5590 →
# 6622 (the audit that set the target) → 11511, +74 % AFTER the rule was
# written down. This script is the mechanism.
#
# It is a ratchet, not a limit. Every first-party file already above the WATCH
# threshold is listed in tools/file_size_budget.txt with its size at the time
# it was recorded. That number may go DOWN freely; it may not go up. A file not
# in the list that crosses the threshold is a new god-object and also fails.
#
# So the rule becomes reviewable: growing MainWindow.cpp now requires editing
# the budget file in the same commit, which is exactly the moment someone
# should be asked whether the new code belongs in a new translation unit.
#
#   tools/check_file_sizes.sh            # check (CI mode: non-zero on failure)
#   tools/check_file_sizes.sh --update   # re-record every ceiling from disk
#
# Generated tables and vendored third-party sources are exempt — see EXEMPT.

set -uo pipefail

cd "$(dirname "$0")/.."

BUDGET="tools/file_size_budget.txt"
WATCH=2000          # files at or above this must carry a ceiling
LIMIT=3000          # a file crossing this without a ceiling is a new offender

# Vendored or machine-generated: their size is not an architectural signal.
is_exempt() {
    case "$1" in
        src/third_party/*)              return 0 ;;
        src/stb_image.h)                return 0 ;;   # vendored, public domain
        src/stb_image_write.h)          return 0 ;;   # vendored, public domain
        src/IconsFontAwesome6.h)        return 0 ;;   # generated by IconFontCppHeaders
        src/Ssi263PhonemeData.cpp)      return 0 ;;   # generated phoneme tables
        src/ImageWriterRom.h)           return 0 ;;   # generated from the char ROMs
        src/AppleIIeKeyboardLayout.cpp) return 0 ;;   # tools/gen_keyboard_layout.py
        src/AppleIIeKeyboardLayout.h)   return 0 ;;   # tools/gen_keyboard_layout.py
    esac
    return 1
}

# tests/ is scanned too. A test file is first-party code with the same failure
# mode — imagewriter_smoke_test.cpp is already 1375 lines — and leaving it out
# meant the one directory whose files are ADDED to fastest had no ceiling at
# all. (tests/CMakeLists.txt, 6800 lines, is not covered: it is a build
# manifest, not a translation unit, and the ratchet only speaks about .cpp/.h.)
list_sources() {
    find src tests -type f \( -name '*.cpp' -o -name '*.h' \) | sort
}

# ── --update: rewrite the budget from what is on disk ─────────────────────
if [ "${1:-}" = "--update" ]; then
    {
        echo "# POM2 file-size budget — see tools/check_file_sizes.sh"
        echo "#"
        echo "# Ceilings for every first-party file at or above ${WATCH} lines."
        echo "# A number here may go DOWN (record the win); it may not go up."
        echo "# Growing one of these means editing this file in the same commit."
        echo "#"
        echo "# Regenerate with: tools/check_file_sizes.sh --update"
        echo ""
    } > "$BUDGET"
    while read -r f; do
        is_exempt "$f" && continue
        n=$(wc -l < "$f")
        [ "$n" -ge "$WATCH" ] && printf "%-40s %d\n" "$f" "$n" >> "$BUDGET"
    done < <(list_sources)
    echo "Wrote $BUDGET:"
    grep -v '^#' "$BUDGET" | grep -v '^$' | sed 's/^/  /'
    exit 0
fi

# ── check ─────────────────────────────────────────────────────────────────
if [ ! -f "$BUDGET" ]; then
    echo "check_file_sizes: $BUDGET is missing — run '$0 --update'" >&2
    exit 2
fi

# NO ASSOCIATIVE ARRAYS. `declare -A` is bash 4, macOS ships bash 3.2, and
# `#!/usr/bin/env bash` finds /bin/bash there. The previous version therefore
# aborted with "declare: -A: invalid option" on every Mac — and, because the
# abort happened inside a `while read` with no `set -e`, it aborted with EXIT
# STATUS 0. The ratchet reported success while checking nothing, on the
# machine where the code is actually written; it only ever ran on CI's Ubuntu,
# so a violation was discovered after the push instead of before it.
#
# A ceiling is looked up by scanning the budget file instead. It holds a few
# dozen lines and the source tree a few hundred files, so the quadratic shape
# is not worth a data structure.
ceiling_for() {
    awk -v want="$1" '$1 == want { print $2; exit }' "$BUDGET"
}

# Guard against the class of failure above: a budget that parses to nothing is
# a broken ratchet, not an empty one, and must not pass quietly.
budget_entries=$(grep -c -v -e '^[[:space:]]*#' -e '^[[:space:]]*$' "$BUDGET" || true)
if [ "${budget_entries:-0}" -eq 0 ]; then
    echo "check_file_sizes: $BUDGET parsed to zero ceilings — run '$0 --update'" >&2
    exit 2
fi

fail=0
slack_report=""
checked_list=$(mktemp)
trap 'rm -f "$checked_list"' EXIT

while read -r f; do
    is_exempt "$f" && continue
    echo "$f" >> "$checked_list"
    n=$(wc -l < "$f")
    cap=$(ceiling_for "$f")

    if [ -n "$cap" ]; then
        if [ "$n" -gt "$cap" ]; then
            echo "FAIL  $f: $n lines, ceiling $cap (+$((n - cap)))" >&2
            fail=1
        elif [ $((cap - n)) -ge 100 ]; then
            slack_report="${slack_report}      $f: $n lines, ceiling $cap — lower it by $((cap - n))
"
        fi
    elif [ "$n" -ge "$LIMIT" ]; then
        echo "FAIL  $f: $n lines and no ceiling — a new file over $LIMIT lines." >&2
        echo "      Split it, or record the ceiling with '$0 --update' and say why." >&2
        fail=1
    elif [ "$n" -ge "$WATCH" ]; then
        # The WATCH band was documented ("every first-party file at or above
        # this must carry a ceiling") but never enforced: only --update used
        # WATCH, so a file that grew 1999 -> 2999 passed in silence and only
        # became visible the day it crossed LIMIT. That is a 1000-line hole in
        # the exact direction the ratchet exists to stop.
        echo "FAIL  $f: $n lines and no ceiling — at or above the $WATCH-line" >&2
        echo "      watch threshold. Record it with '$0 --update' (and say in" >&2
        echo "      the commit why it belongs in one TU), or split it now." >&2
        fail=1
    fi
done < <(list_sources)

# A ceiling whose file is gone (renamed, split, deleted) is stale.
while read -r path _limit_value _rest; do
    case "$path" in ''|\#*) continue ;; esac
    if ! grep -Fxq "$path" "$checked_list"; then
        echo "FAIL  $BUDGET lists $path, which no longer exists — run '$0 --update'" >&2
        fail=1
    fi
done < "$BUDGET"

if [ "$fail" -ne 0 ]; then
    echo "" >&2
    echo "The rule is TODO.md's: do not grow the god-objects (target < $LIMIT lines)." >&2
    echo "New code for an existing window group belongs in its own translation unit." >&2
    exit 1
fi

if [ -n "$slack_report" ]; then
    echo "check_file_sizes: passed, with ceilings that can be tightened:"
    printf '%s' "$slack_report"
else
    echo "check_file_sizes: passed."
fi
exit 0
