// POM2 Apple II Emulator
// Copyright (C) 2026 VERHILLE Arnaud
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

#include "DiskIICard.h"
#include "FloppySoundSink.h"
#include "IWMDevice.h"
#include "Logger.h"
#include "M6502.h"

#include <algorithm>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <memory>

namespace {
// ~32 CPU cycles per nibble = 4 µs bit cells × 8 bits at 1.0227 MHz. Real
// hardware varies with the LSS state, but DOS 3.3 / ProDOS only need
// average-rate accuracy because they re-sync on every D5-AA prologue.
constexpr int kCyclesPerNibble  = 32;
constexpr int kQuarterTrackMax  = (DiskImage::kTracks - 1) * 4;  // 136

// Default contents of the Apple Disk II P6 PROM (341-0028-A, 16-sector
// variant) — MAME-layout, indexed by the scrambled 8-bit address scheme
// of `wozfdc.cpp lss_sync()`:
//
//   bit 7 = state[3]   bit 4 = !PULSE   bit 1 = QA
//   bit 6 = state[2]   bit 3 = Q7       bit 0 = state[1]
//   bit 5 = state[0]   bit 2 = Q6
//
// These 256 bytes are derived from apple2js's `SEQUENCER_ROM_16` table
// (rooted in Sather's "Understanding the Apple //e" Fig. 9.11) by
// applying MAME's PROM-pin permutation — same content, different index.
// Generated by `scripts/permute_p6_rom.py`; re-run if either side moves.
//
// Used as the fallback when `roms/diskii_p6.rom` is missing — POM2 keeps
// the LSS path active out of the box without depending on a dumped PROM
// file. `loadLssRom()` overrides this default with a verified dump
// (which must also be in MAME layout — see scripts/permute_p6_rom.py).
// Apple Disk II boot PROM (Apple part 341-0027-A, "P5"). 256 bytes,
// CRC32 ce7144f6, SHA1 d4181c9f046aafc3fb326b381baac809d9e38d16. Same
// bytes MAME loads at `a2diskiing.cpp:42-45`. Embedded so POM2 boots
// out-of-the-box without requiring `roms/disk2.rom`. `loadBootRom()`
// still overrides this when a user-supplied dump is present.
constexpr uint8_t kBootPromDefault[256] = {
    0xA2, 0x20, 0xA0, 0x00, 0xA2, 0x03, 0x86, 0x3C, 0x8A, 0x0A, 0x24, 0x3C, 0xF0, 0x10, 0x05, 0x3C,
    0x49, 0xFF, 0x29, 0x7E, 0xB0, 0x08, 0x4A, 0xD0, 0xFB, 0x98, 0x9D, 0x56, 0x03, 0xC8, 0xE8, 0x10,
    0xE5, 0x20, 0x58, 0xFF, 0xBA, 0xBD, 0x00, 0x01, 0x0A, 0x0A, 0x0A, 0x0A, 0x85, 0x2B, 0xAA, 0xBD,
    0x8E, 0xC0, 0xBD, 0x8C, 0xC0, 0xBD, 0x8A, 0xC0, 0xBD, 0x89, 0xC0, 0xA0, 0x50, 0xBD, 0x80, 0xC0,
    0x98, 0x29, 0x03, 0x0A, 0x05, 0x2B, 0xAA, 0xBD, 0x81, 0xC0, 0xA9, 0x56, 0x20, 0xA8, 0xFC, 0x88,
    0x10, 0xEB, 0x85, 0x26, 0x85, 0x3D, 0x85, 0x41, 0xA9, 0x08, 0x85, 0x27, 0x18, 0x08, 0xBD, 0x8C,
    0xC0, 0x10, 0xFB, 0x49, 0xD5, 0xD0, 0xF7, 0xBD, 0x8C, 0xC0, 0x10, 0xFB, 0xC9, 0xAA, 0xD0, 0xF3,
    0xEA, 0xBD, 0x8C, 0xC0, 0x10, 0xFB, 0xC9, 0x96, 0xF0, 0x09, 0x28, 0x90, 0xDF, 0x49, 0xAD, 0xF0,
    0x25, 0xD0, 0xD9, 0xA0, 0x03, 0x85, 0x40, 0xBD, 0x8C, 0xC0, 0x10, 0xFB, 0x2A, 0x85, 0x3C, 0xBD,
    0x8C, 0xC0, 0x10, 0xFB, 0x25, 0x3C, 0x88, 0xD0, 0xEC, 0x28, 0xC5, 0x3D, 0xD0, 0xBE, 0xA5, 0x40,
    0xC5, 0x41, 0xD0, 0xB8, 0xB0, 0xB7, 0xA0, 0x56, 0x84, 0x3C, 0xBC, 0x8C, 0xC0, 0x10, 0xFB, 0x59,
    0xD6, 0x02, 0xA4, 0x3C, 0x88, 0x99, 0x00, 0x03, 0xD0, 0xEE, 0x84, 0x3C, 0xBC, 0x8C, 0xC0, 0x10,
    0xFB, 0x59, 0xD6, 0x02, 0xA4, 0x3C, 0x91, 0x26, 0xC8, 0xD0, 0xEF, 0xBC, 0x8C, 0xC0, 0x10, 0xFB,
    0x59, 0xD6, 0x02, 0xD0, 0x87, 0xA0, 0x00, 0xA2, 0x56, 0xCA, 0x30, 0xFB, 0xB1, 0x26, 0x5E, 0x00,
    0x03, 0x2A, 0x5E, 0x00, 0x03, 0x2A, 0x91, 0x26, 0xC8, 0xD0, 0xEE, 0xE6, 0x27, 0xE6, 0x3D, 0xA5,
    0x3D, 0xCD, 0x00, 0x08, 0xA6, 0x2B, 0x90, 0xDB, 0x4C, 0x01, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00,
};

constexpr uint8_t kP6RomDefault[256] = {
    0x18, 0xD8, 0x18, 0x08, 0x0A, 0x0A, 0x0A, 0x0A, 0x18, 0x39, 0x18, 0x39, 0x18, 0x3B, 0x18, 0x3B, // row 0
    0x18, 0x38, 0x18, 0x28, 0x0A, 0x0A, 0x0A, 0x0A, 0x18, 0x39, 0x18, 0x39, 0x18, 0x3B, 0x18, 0x3B, // row 1
    0x2D, 0xD8, 0x38, 0x48, 0x0A, 0x0A, 0x0A, 0x0A, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, // row 2
    0x2D, 0x48, 0x38, 0x48, 0x0A, 0x0A, 0x0A, 0x0A, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, 0x28, 0x48, // row 3
    0xD8, 0xD8, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, // row 4
    0x58, 0x78, 0x58, 0x78, 0x0A, 0x0A, 0x0A, 0x0A, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, 0x58, 0x78, // row 5
    0xD8, 0xD8, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0x68, 0x08, 0x68, 0x88, 0x68, 0x08, 0x68, 0x88, // row 6
    0x68, 0x88, 0x68, 0x88, 0x0A, 0x0A, 0x0A, 0x0A, 0x68, 0x08, 0x68, 0x88, 0x68, 0x08, 0x68, 0x88, // row 7
    0xD8, 0xCD, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0x98, 0xB9, 0x98, 0xB9, 0x98, 0xBB, 0x98, 0xBB, // row 8
    0x98, 0xBD, 0x98, 0xB8, 0x0A, 0x0A, 0x0A, 0x0A, 0x98, 0xB9, 0x98, 0xB9, 0x98, 0xBB, 0x98, 0xBB, // row 9
    0xD8, 0xD9, 0xD8, 0xD8, 0x0A, 0x0A, 0x0A, 0x0A, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, // row A
    0x29, 0x59, 0xA8, 0xC8, 0x0A, 0x0A, 0x0A, 0x0A, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, 0xA8, 0xC8, // row B
    0xD9, 0xFD, 0xD8, 0xF8, 0x0A, 0x0A, 0x0A, 0x0A, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, // row C
    0xD9, 0xFD, 0xA0, 0xF8, 0x0A, 0x0A, 0x0A, 0x0A, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, 0xD8, 0xF8, // row D
    0xD8, 0xDD, 0xE8, 0xE0, 0x0A, 0x0A, 0x0A, 0x0A, 0xE8, 0x88, 0xE8, 0x08, 0xE8, 0x88, 0xE8, 0x08, // row E
    0x08, 0x4D, 0xE8, 0xE0, 0x0A, 0x0A, 0x0A, 0x0A, 0xE8, 0x88, 0xE8, 0x08, 0xE8, 0x88, 0xE8, 0x08, // row F
};

// Opt-in diagnostic — set POM2_DEBUG_DISK=1 to see one-shot lines marking
// each milestone of the Disk II boot sequence. Cheap when off (one bool
// check on hot-path reads, but only inside the diagnostic state struct's
// guard).
// Namespace-scope (not function-local) statics: a function-local static
// pays an initialisation-guard check on every call, and both of these sit
// on the per-LSS-sync path while the motor runs.
const bool g_debugDisk = []{
    const char* v = std::getenv("POM2_DEBUG_DISK");
    return v && *v && *v != '0';
}();
FILE* const g_lssTraceFile = [] {
    const char* p = std::getenv("POM2_TRACE_LSS");
    return p ? std::fopen(p, "w") : static_cast<FILE*>(nullptr);
}();
long g_lssTraceCalls = 0, g_lssTraceKept = 0;

bool debugEnabled() { return g_debugDisk; }

}  // namespace

DiskIICard::DiskIICard(int slot)
    : slot_(slot)
{
    // Pre-fill with the embedded Apple 341-0027-A boot PROM so the card
    // boots without a user-supplied `roms/disk2.rom`. `loadBootRom()`
    // overrides this with a verified dump if one is present. `bootRomLoaded`
    // is set so callers and the slot-bus accept the card immediately.
    std::memcpy(bootRom.data(), kBootPromDefault, sizeof(kBootPromDefault));
    bootRomLoaded = true;
    // Pre-fill with the published 16-sector P6 PROM so the LSS path
    // works out-of-the-box. `loadLssRom()` can override this with a
    // verified dump from `roms/diskii_p6.rom`. `p6RomLoaded` stays
    // false until an explicit load — when false, `useBitLss` also
    // stays false (legacy gate path) so cycle accounting and test
    // expectations match the pre-LSS behaviour.
    std::memcpy(p6Rom.data(), kP6RomDefault, sizeof(kP6RomDefault));
}

bool DiskIICard::loadBootRom(const std::string& path)
{
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        pom2::log().warn("Disk II", "Cannot open boot PROM: " + path);
        return false;
    }
    f.seekg(0, std::ios::end);
    const auto size = static_cast<size_t>(f.tellg());
    f.seekg(0, std::ios::beg);
    if (size != 256) {
        pom2::log().warn("Disk II",
            "Boot PROM must be 256 bytes, got " + std::to_string(size));
        return false;
    }
    f.read(reinterpret_cast<char*>(bootRom.data()), 256);
    if (!f) {
        pom2::log().warn("Disk II", "Short read on " + path);
        return false;
    }
    bootRomLoaded = true;
    pom2::log().info("Disk II", "Boot PROM loaded: " + path);
    return true;
}

bool DiskIICard::loadLssRom(const std::string& path)
{
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        pom2::log().info("Disk II",
            "P6 LSS PROM not found at " + path +
            " — using legacy 32-cycle gate");
        return false;
    }
    f.seekg(0, std::ios::end);
    const auto size = static_cast<size_t>(f.tellg());
    f.seekg(0, std::ios::beg);
    if (size != 256) {
        pom2::log().warn("Disk II",
            "P6 LSS PROM must be 256 bytes, got " + std::to_string(size) +
            " — using legacy 32-cycle gate");
        return false;
    }
    f.read(reinterpret_cast<char*>(p6Rom.data()), 256);
    if (!f) {
        pom2::log().warn("Disk II", "Short read on " + path);
        return false;
    }
    p6RomLoaded = true;
    pom2::log().info("Disk II", "P6 LSS PROM loaded: " + path);
    return true;
}

bool DiskIICard::loadBootRom13(const std::string& path)
{
    std::ifstream f(path, std::ios::binary);
    if (!f) return false;                      // optional — silent when absent
    f.seekg(0, std::ios::end);
    const auto size = static_cast<size_t>(f.tellg());
    f.seekg(0, std::ios::beg);
    if (size != 256) {
        pom2::log().warn("Disk II",
            "13-sector boot PROM must be 256 bytes, got " + std::to_string(size));
        return false;
    }
    f.read(reinterpret_cast<char*>(bootRom13.data()), 256);
    if (!f) return false;
    bootRom13Loaded = true;
    pom2::log().info("Disk II", "13-sector boot PROM loaded: " + path);
    return true;
}

bool DiskIICard::loadLssRom13(const std::string& path)
{
    std::ifstream f(path, std::ios::binary);
    if (!f) return false;                      // optional — silent when absent
    f.seekg(0, std::ios::end);
    const auto size = static_cast<size_t>(f.tellg());
    f.seekg(0, std::ios::beg);
    if (size != 256) {
        pom2::log().warn("Disk II",
            "13-sector LSS PROM must be 256 bytes, got " + std::to_string(size));
        return false;
    }
    f.read(reinterpret_cast<char*>(p6Rom13.data()), 256);
    if (!f) return false;
    p6Rom13Loaded = true;
    pom2::log().info("Disk II", "13-sector LSS PROM loaded: " + path);
    return true;
}

// Recompute every card-wide latch that is a function of WHICH media are
// currently mounted. Called from both insertDisk and ejectDisk: these are
// properties of the mounted set, not one-way switches. Leaving them latched
// across an eject made the card keep serving the 341-0009 13-sector boot
// PROM after the 13-sector disk that selected it was removed — a 16-sector
// disk left in the other drive (or inserted into a `bootFromSlot` that
// re-reads $Cn00 before any insert) then booted against the wrong PROM.
void DiskIICard::refreshMediaDerivedState(bool warnMissing13Rom)
{
    // Active iff P6 PROM file was loaded explicitly via loadLssRom.
    // The embedded default is also valid (and MAME-layout) but the
    // gating keeps the legacy 32-cycle gate available for tests that
    // pin pre-LSS behaviour until they're updated. Plus: any drive
    // holding a .woz image *forces* the LSS path. WOZ stores raw bit
    // cells, the legacy 32-cycle nibble gate cannot decode them, and
    // the embedded default P6 PROM in p6Rom is sufficient — so this
    // override works even without roms/diskii_p6.rom on disk.
    const bool wasBitLss = useBitLss;
    useBitLss = p6RomLoaded;
    for (int d = 0; d < kDriveCount; ++d) {
        if (images[d].isWoz()) { useBitLss = true; break; }
    }
    // 13-sector controller selection. A Disk II controller is physically
    // either 13- or 16-sector (different P5/P6 PROMs); you can't mix them
    // on one card. So any mounted 13-sector disk flips the whole card to
    // the 341-0009 boot PROM + 341-0010 LSS — provided both were loaded
    // (loadBootRom13 / loadLssRom13). slotRomRead / lssSync index the 13s
    // pair while serving13_ is set; otherwise nothing changes for 16s.
    bool any13 = false;
    for (int d = 0; d < kDriveCount; ++d)
        if (images[d].isLoaded() && images[d].is13Sector()) { any13 = true; break; }
    // A 13-sector disk flips the card to the 341-0009 boot PROM at $Cn00.
    // The READ sequencer stays the 16-sector P6 (341-0028): the LSS is
    // bit-level and encoding-agnostic — it recovers the 5-and-3 nibble
    // stream (D5 AA B5 / translate5 bytes) just as well, and the 5-and-3
    // *decode* is done in software by the 341-0009 boot / DOS 3.2 RWTS.
    // (The raw 341-0010 dump doesn't drive POM2's wozfdc-port lssSync —
    // it yields zero byte-ready — whereas the 16s P6 reads 13s correctly;
    // verified by tests/dos32_boot_trace.cpp phase 0.) We force the
    // bit-level LSS on because the 341-0009 read loop is tighter than the
    // 16s-tuned legacy 32-cycle gate (which mis-frames the 5-and-3 read).
    serving13_ = any13 && bootRom13Loaded;
    if (warnMissing13Rom && any13 && !serving13_)
        pom2::log().warn("Disk II",
            "13-sector disk mounted but the 341-0009 boot PROM "
            "(roms/disk2_13.rom) is missing — it won't boot");
    if (serving13_) useBitLss = true;

    // Demoting to the legacy 32-cycle gate mid-spin (ejecting the only WOZ
    // when no P6 dump was loaded) hands motor control to a path that has no
    // notion of `active`: `$C0n8` would then clear `motorOn` while `active`
    // stayed MODE_ACTIVE, and a later WOZ insert would resume the LSS on a
    // drive whose motor is supposedly off. Park the sequencer instead — the
    // next motor-on re-anchors it from scratch.
    if (wasBitLss && !useBitLss && active != MODE_IDLE) {
        active          = MODE_IDLE;
        motorOffDelay   = 0;
        writePosition   = 0;
        writeLineActive = false;
        for (int d = 0; d < kDriveCount; ++d)
            revolutionStartLssCycle[d] = kNeverRev;
    }
}

// Splice the write burst the controller is part-way through into the ACTIVE
// drive's image. selectDrive() already does this when a drive swap abandons
// a write (see its `mon_w(true) → commit_image` block); the other paths that
// abandon one outside the normal Q7 falling edge — insertDisk,
// flushPendingWrites — used to just zero the cursor, losing the sector.
void DiskIICard::commitInFlightWrite()
{
    if (active == MODE_IDLE || !writeMode || !writeBackEnabled) return;
    if (writePosition <= 0) return;
    DiskImage& img = images[activeDrive];
    if (!img.isLoaded()) return;
    // Same call, same anchors as the drive-swap splice in selectDrive():
    // the burst is timed against the drive's own revolution start.
    img.writeFlux(headQuarterTrack[activeDrive],
                  writeStartTime,
                  static_cast<int64_t>(lssCycle),
                  writePosition, writeBuffer,
                  revolutionStartLssCycle[activeDrive]);
    ++writeFlushCount;
    writePosition   = 0;
    writeLineActive = false;
}

// Flush every drive's pending write-back without ejecting. The eject and
// swap paths already do this, but process shutdown / profile switch tears
// the card down without either — a session's DOS SAVEs then died with the
// process even though the user had opted in to write-back. Guarded twice
// over inside DiskImage::saveDirty (write-back off, or a physically
// write-protected medium, is a no-op returning success).
bool DiskIICard::flushPendingWrites()
{
    // Fold the burst the controller is part-way through into its image
    // first, so a shutdown / profile switch mid-`SAVE` persists it like a
    // completed sector rather than dropping it on the floor.
    commitInFlightWrite();
    bool ok = true;
    for (int d = 0; d < kDriveCount; ++d) {
        DiskImage& img = images[d];
        if (!img.isLoaded() || !img.hasUnsavedChanges()) continue;
        if (!img.saveDirty()) {
            ok = false;
            mediaErrors[d] = img.getLastError();
            pom2::log().warn("Disk II",
                "Flush failed for drive " + std::to_string(d + 1) + ": " +
                img.getLastError());
        }
    }
    return ok;
}

DiskIICard::~DiskIICard()
{
    (void)flushPendingWrites();
}

// Phase 1 of the two-phase mount — see the header. Pure file I/O against a
// detached image: no card state is read or written, so this needs no lock.
bool DiskIICard::prepareDisk(const std::string& path, bool writeBackEnabled,
                             DiskImage& out, std::string& error)
{
    // Heap, not stack: a DiskImage is ~242 KB and this sits mid-chain on the
    // insert path (insertDisk → here → loadFile, one temporary per frame) —
    // three on a 512 KB macOS std::thread stack is a SIGBUS. The AI control
    // server's HTTP thread reaches insertDisk directly.
    auto staged = std::make_unique<DiskImage>();
    staged->setWriteBackEnabled(writeBackEnabled);
    if (!staged->loadFile(path)) {
        error = staged->getLastError();
        pom2::log().warn("Disk II", "Insert failed: " + error);
        return false;
    }
    error.clear();
    out = std::move(*staged);
    return true;
}

bool DiskIICard::insertDisk(int drive, const std::string& path)
{
    if (drive < 0 || drive >= kDriveCount) {
        pom2::log().warn("Disk II",
            "insertDisk: invalid drive index " + std::to_string(drive));
        return false;
    }
    // Inline form: keep the historical ORDER — flush the outgoing medium
    // first, then read the new one. It matters when both are the same file
    // (re-inserting a disk the guest has written to): loading first would
    // read the pre-flush bytes and then overwrite them. installDisk() below
    // detects that collision for the two-phase callers.
    commitInFlightWrite();
    if (!flushOutgoingForSwap(drive)) return false;

    // Heap for the same stack-size reason as prepareDisk below.
    auto replacement = std::make_unique<DiskImage>();
    std::string error;
    if (!prepareDisk(path, writeBackEnabled, *replacement, error)) {
        mediaErrors[drive] = error;
        return false;
    }
    return installPreparedLocked(drive, std::move(*replacement));
}

// Flush a drive's medium before it is dropped. Returns false — and records the
// error — if the write-back could not be committed, which refuses the swap and
// leaves the dirty medium in the drive for the user to retry.
bool DiskIICard::flushOutgoingForSwap(int drive)
{
    DiskImage& img = images[drive];
    if (img.isLoaded() && img.hasUnsavedChanges()) {
        if (!img.saveDirty()) {
            mediaErrors[drive] = img.getLastError();
            pom2::log().warn("Disk II",
                "Save-on-swap failed: " + img.getLastError());
            return false;
        }
    }
    return true;
}

// Phase 2 of the two-phase mount — see the header.
bool DiskIICard::installDisk(int drive, DiskImage&& prepared)
{
    if (drive < 0 || drive >= kDriveCount) {
        pom2::log().warn("Disk II",
            "installDisk: invalid drive index " + std::to_string(drive));
        return false;
    }
    if (!prepared.isLoaded()) {
        pom2::log().warn("Disk II", "installDisk: image was not prepared");
        return false;
    }
    commitInFlightWrite();

    // Same file, and the outgoing copy has unsaved changes: the prepared image
    // was read BEFORE that flush, so installing it would silently roll the
    // guest's writes back. Flush, then re-read under the lock. This is the one
    // path where the two-phase form degrades to the inline cost, and it is the
    // rare one — write-back is opt-in and the paths have to match exactly.
    DiskImage& img = images[drive];
    const bool sameFileStillDirty =
        img.isLoaded() && img.hasUnsavedChanges() &&
        !img.getPath().empty() && img.getPath() == prepared.getPath();

    if (!flushOutgoingForSwap(drive)) return false;

    if (sameFileStillDirty) {
        const std::string path = prepared.getPath();
        // Heap for the same stack-size reason as prepareDisk above.
        auto reread = std::make_unique<DiskImage>();
        std::string error;
        if (!prepareDisk(path, writeBackEnabled, *reread, error)) {
            mediaErrors[drive] = error;
            return false;
        }
        prepared = std::move(*reread);
    }
    return installPreparedLocked(drive, std::move(prepared));
}

// The state mutation shared by both entry points: adopt the image and re-anchor
// every piece of controller state that depends on the medium.
bool DiskIICard::installPreparedLocked(int drive, DiskImage&& replacement)
{
    DiskImage& img = images[drive];
    img = std::move(replacement);
    mediaErrors[drive].clear();
    trackPos[drive] = 0;
    cycleAccum      = 0;
    writeLatch      = 0xFF;
    // Reset MAME wozfdc state. The default P6 ROM is in p6Rom (see
    // constructor) so the LSS path works without the optional
    // roms/diskii_p6.rom override. We still gate on `p6RomLoaded` so
    // the user can opt out by removing the file. (Done unconditionally
    // here so a drive-2 insert mid-session also resyncs the LSS rather
    // than carrying over flux state from the prior drive-1 image.)
    address         = 0x10;          // !PULSE high (no pulse), state=0
    lssData         = 0;
    writePosition   = 0;
    writeLineActive = false;
    writeStartTime  = 0;
    refreshMediaDerivedState(/*warnMissing13Rom=*/true);
    // Re-anchor the bit-level LSS clock to "now". If the controller was
    // already spinning (active != MODE_IDLE) over an empty drive, lssCycle
    // has been frozen — lssStart()/lssSync() only run with a disk present —
    // while cpuCycleTotal kept growing. Without this resync the first $C0EC
    // read after insertion runs the lssSync catch-up `while (lssCycle <
    // cyclesLimit)` loop for millions of PROM-lookup iterations, freezing
    // the emulator for seconds. Mirrors what lssStart() does on motor-on.
    if (active != MODE_IDLE) {
        lssCycle = cpuCycleTotal * 2;
    } else if (useBitLss && motorOn) {
        // Legacy-spun motor promoted into the LSS state machine: before
        // the FIRST insert useBitLss is false, so a guest $C0E9 went
        // through the legacy branch — motorOn=true but active stays
        // MODE_IDLE. insertDisk then flips useBitLss on (P6 PROM present)
        // and the two machines disagree: the boot PROM polls $C0EC while
        // the LSS never runs, and the legacy motor can no longer be
        // switched off through the LSS path. Mirror control() case 0x9's
        // MODE_IDLE branch instead of stranding the state.
        active = MODE_ACTIVE;
        lssStart();
    }
    // No click here — fires at user-initiated insert via UI / CLI only.
    // Auto-restore of the previous-session disk path calls insertDisk
    // during MainWindow construction; firing the click there would
    // surprise the user with a mechanical thunk on every startup.
    pushIwmFloppy();
    return true;
}

std::unique_ptr<DiskImage> DiskIICard::takeEjectWriteBack(int drive)
{
    if (drive < 0 || drive >= kDriveCount) return nullptr;
    // Same reason insertDisk and flushPendingWrites do it: fold the burst the
    // controller is part-way through into the image BEFORE lifting it out, or
    // `img.eject()` below wipes tracks[] and writeFraming[] and takes the
    // sector the guest was writing with it. Clicking Eject during a `SAVE`
    // dropped ~30 buffered transitions plus the partly framed nibble, and the
    // truncated data field then failed to decode — so the sector silently
    // reverted to its old contents while the save reported success.
    commitInFlightWrite();
    DiskImage& img = images[drive];
    std::unique_ptr<DiskImage> pending;
    if (img.isLoaded() && img.hasUnsavedChanges()) {
        // Move-ASSIGN into an already-heap-allocated image. A `DiskImage` is
        // ~242 KB and macOS gives a std::thread a 512 KB stack, so neither the
        // temporary `make_unique(std::move(img))` would materialise nor a
        // `std::swap` (which builds one) may appear on this path — same rule
        // as `prepareDisk`. Element-wise array move is a memcpy done in
        // place: microseconds, and no syscall, which is the whole point of
        // doing this half under the lock.
        pending = std::make_unique<DiskImage>();
        *pending = std::move(img);
    }
    img.eject();
    mediaErrors[drive].clear();
    trackPos[drive] = 0;
    writeLatch      = 0xFF;
    // The 13-sector PROM selection and the WOZ-forced LSS path are functions
    // of what is mounted RIGHT NOW — removing the disk that selected them has
    // to un-select them, or the card keeps answering $Cn00 out of the
    // 341-0009 13-sector boot PROM with no 13-sector disk in sight.
    refreshMediaDerivedState(/*warnMissing13Rom=*/false);
    // No click here — symmetric with insertDisk; UI / CLI sites fire
    // their own click when the user triggers the eject.
    pushIwmFloppy();
    return pending;
}

bool DiskIICard::commitEjectWriteBack(DiskImage& pending, std::string& error)
{
    if (pending.saveDirty()) return true;
    error = pending.getLastError();
    if (error.empty()) error = "save-on-eject failed";
    pom2::log().warn("Disk II", "Save-on-eject failed: " + error);
    return false;
}

bool DiskIICard::restoreEjected(int drive, std::unique_ptr<DiskImage> pending)
{
    if (drive < 0 || drive >= kDriveCount || !pending) return false;
    if (images[drive].isLoaded()) return false;   // bay refilled meanwhile
    const std::string err = pending->getLastError();
    // installPreparedLocked re-anchors the LSS exactly as an insert does, and
    // clears mediaErrors — so the error that caused the retry is re-applied
    // after it, or the panel would show a silently reverted disk and no
    // explanation of why the eject did not take.
    if (!installPreparedLocked(drive, std::move(*pending))) return false;
    mediaErrors[drive] = err;
    return true;
}

bool DiskIICard::ejectDisk(int drive)
{
    if (drive < 0 || drive >= kDriveCount) return false;
    // Composed from the three-step form so there is ONE copy of the eject
    // logic — the same shape `Block512Backing::saveDirty` has. The phases are
    // simply not separated in time here.
    std::unique_ptr<DiskImage> pending = takeEjectWriteBack(drive);
    if (!pending) return true;             // empty bay, or nothing to save
    std::string error;
    if (commitEjectWriteBack(*pending, error)) return true;
    // Preserve dirty media so the user can retry — what the pre-split inline
    // path did by never ejecting on a failed save.
    (void)restoreEjected(drive, std::move(pending));
    mediaErrors[drive] = error;
    return false;
}

uint8_t DiskIICard::slotRomRead(uint8_t low8)
{
    if (debugEnabled() && !trace.sawSlotRom) {
        trace.sawSlotRom = true;
        char buf[64];
        std::snprintf(buf, sizeof(buf),
            "PROM entered (first slot ROM read at offset $%02X)", low8);
        pom2::log().info("Disk II", buf);
    }
    return (serving13_ ? bootRom13 : bootRom)[low8];
}

void DiskIICard::dumpRecentReads(size_t maxEntries) const
{
    const size_t n = std::min(readLog_.size(), maxEntries);
    if (n == 0) {
        std::fprintf(stderr, "DiskII read log: empty (set POM2_DEBUG_DISK_READS=1)\n");
        return;
    }
    std::fprintf(stderr, "DiskII recent $C0EC reads (last %zu of %zu):\n",
                 n, readLog_.size());
    const size_t start = (readLog_.size() > n) ? (readLog_.size() - n) : 0;
    for (size_t i = start; i < readLog_.size(); ++i) {
        const auto& e = readLog_[i];
        std::fprintf(stderr, "  [%4zu] cycle=%llu qt=%2u data=$%02X\n",
                     i,
                     static_cast<unsigned long long>(e.cycle),
                     unsigned(e.qt), unsigned(e.data));
    }
}

void DiskIICard::onReset()
{
    // The drive really does stop, so the mechanical-sound source has to be
    // told. It only silences its spin loop on an explicit motor(false)
    // command; a Ctrl-Reset (F11) mid-read used to clear `motorOn` behind
    // its back and leave the motor hum looping for the rest of the session
    // — nothing else would ever emit the matching motor-off.
    if (motorOn && sound_)
        sound_->motor(false, images[activeDrive].isLoaded());
    motorOn   = false;
    motorOffDelay = 0;
    writeMode = false;
    loadMode  = false;
    phaseOn   = {};
    cycleAccum = 0;
    dataLatch  = 0;
    byteReady  = false;
    active    = MODE_IDLE;
    // LSS state. Real Disk II hardware does NOT lose the head's bit-
    // stream alignment on a soft (Ctrl-Reset) — the disk keeps spinning
    // and the LSS shift register settles back to a stable value within
    // the next sync gap. We zero the address (state=0, QA=0) and data
    // register to start from a clean PROM state, with bit 4 of address
    // (!PULSE) high — no pulse pending. lssCycle survives (the PROM
    // re-syncs naturally on the next sync run).
    address          = 0x10;
    lssData          = 0;
    writePosition    = 0;
    writeLineActive  = false;
    // Active is now MODE_IDLE on both drives — the equivalent of MAME
    // `floppy_image_device::mon_w(true)`, which sets
    // `m_revolution_start_time = attotime::never`. The next lssStart
    // re-anchors the active drive's `revolutionStartLssCycle` to "now".
    revolutionStartLssCycle[0] = kNeverRev;
    revolutionStartLssCycle[1] = kNeverRev;
    trace = {};
    // Head position and trackPos are intentionally NOT reset — a real
    // Disk II loses neither when the host CPU is reset; the boot PROM
    // re-recalibrates by stepping phase 0 a bunch of times anyway.
}

void DiskIICard::seekPhaseW(int phases)
{
    // Verbatim port of MAME `floppy_image_device::seek_phase_w` — looks
    // at the *full* 4-bit phase mask and drops the head into the well
    // of whichever 1- or 2-magnet pattern is energized, with motion
    // capped at ±4 quarter-tracks per call. This replaces the prior
    // edge-detection model, which only stepped on rising edges and
    // missed sub-half-track positions used by Copy II Plus's analyzer
    // and by quarter-track copy protection schemes.
    //
    // Phase-mask -> well position (8 wells per "phase cycle"; each cycle
    // covers 2 tracks of head travel — 4 quarter-tracks per track):
    //   0x1 -> 0   0x3 -> 1   0x2 -> 2   0x6 -> 3
    //   0x4 -> 4   0xC -> 5   0x8 -> 6   0x9 -> 7
    // Anything else (no magnet, opposing magnets like 0x5 / 0xA, or 3+
    // simultaneously) leaves the head where it was.
    static constexpr int reqPosTable[16] = {
        -1, /*0x0 idle*/
         0, /*0x1*/
         2, /*0x2*/
         1, /*0x3*/
         4, /*0x4*/
        -1, /*0x5 opposing 0+2*/
         3, /*0x6*/
        -1, /*0x7 three magnets*/
         6, /*0x8*/
         7, /*0x9*/
        -1, /*0xA opposing 1+3*/
        -1, /*0xB three magnets*/
         5, /*0xC*/
        -1, /*0xD three magnets*/
        -1, /*0xE three magnets*/
        -1, /*0xF all four*/
    };
    const int req = reqPosTable[phases & 0xF];
    if (req < 0) return;

    // Move only the active drive's head. The phase magnets are wired to
    // the controller; only the selected drive's stepper responds.
    int& head = headQuarterTrack[activeDrive];
    const int cur = head;
    // Opposite-phase pattern (e.g. cur in well 0 and req=4): head sits
    // between two opposing magnets and doesn't move.
    if (((cur ^ req) & 7) == 4) return;

    int next = (cur & ~7) | req;
    if (next < cur - 4) next += 8;
    else if (next > cur + 4) next -= 8;
    next = std::clamp(next, 0, kQuarterTrackMax);
    const bool moved = (next != cur);
    head = next;
    // One mechanical "click" per quarter-track of head travel. DOS 3.3
    // does a 4-phase sweep (~4 step pulses per track); fast-seeking
    // utilities issue these back-to-back, which trips the audio source's
    // gap-< 100 ms classifier into seek mode automatically. We pass
    // `cpuCycleTotal` (emulated cycles) so the audio thread can measure
    // step cadence in emulated time — wall-clock measurement breaks
    // under disk turbo (all 80 phase-sweep steps land in one audio
    // buffer when the CPU runs ~60× real-time).
    if (moved && sound_) sound_->step(head / 4, cpuCycleTotal);
    if (moved) pushIwmFloppy();
}

void DiskIICard::pushIwmFloppy()
{
    // Mirror the active drive's image + quarter-track into the //c+
    // on-board IWM (when wired). MAME `apple2e.cpp:1180-1185` calls
    // `m_iwm->set_floppy(...)` whenever the controller's notion of
    // "currently spinning drive" changes; on POM2's slot-6 card that
    // surface is `insertDisk` / `ejectDisk` / `selectDrive` /
    // `seekPhaseW`. Keeping the IWM in sync via a single helper means
    // we route every entry point through the same MAME-faithful hook.
    if (!iwm_) return;
    DiskImage* img = images[activeDrive].isLoaded()
        ? &images[activeDrive] : nullptr;
    iwm_->setFloppy(img, headQuarterTrack[activeDrive]);
}

// ─── Rewind / snapshot ──────────────────────────────────────────────────────
// Serialize the controller's volatile runtime state: the head position and
// motion magnets, the motor, the selected drive, the LSS sequencer + data
// register, and the rotational timing anchors. The PROMs are excluded (same
// on the restored machine).
//
// v4 also carries the mid-write splice buffer (`writeBuffer`/`writePosition`/
// `writeStartTime`/`writeLineActive`). `lssCycle` was already saved, so a
// rewind landing inside a sector write used to resume with the timing anchor
// restored but the accumulated flux edges gone: the burst flushed short and
// left a hole in the sector, which reached the .dsk once write-back committed.
//
// v2 also appends the writable media (nibble track buffers) for loaded,
// non-write-protected, non-WOZ disks, so disk WRITES are undone on a rewind.
// Read-only / WOZ / empty drives cost one flag byte; the rewind delta codec
// keeps the media near-zero until a track is actually written. Blob is
// self-describing (magic + version) so a foreign card on this slot ignores it.
namespace {
constexpr uint8_t kDiskIISnapVersion = 4;

// FNV-1a 64 of the image path — the media identity stamped next to each
// captured track buffer (v3). Restoring a media snapshot onto a drive
// that now holds a DIFFERENT image (user swapped disks after the ring
// frame was recorded) copied disk A's tracks + dirty flags into the
// DiskImage bound to disk B's path, and the next saveDirty() then wrote
// A's contents into B's file. The WOZ-swap case was already guarded; the
// non-WOZ↔non-WOZ swap needs the identity check.
uint64_t mediaIdentityHash(const std::string& path)
{
    uint64_t h = 14695981039346656037ULL;
    for (unsigned char c : path) {
        h ^= c;
        h *= 1099511628211ULL;
    }
    return h;
}
}

void DiskIICard::appendSnapshotState(std::vector<uint8_t>& out) const
{
    auto u8  = [&](uint8_t v)  { out.push_back(v); };
    auto u32 = [&](uint32_t v) { for (int i = 0; i < 4; ++i) out.push_back(static_cast<uint8_t>(v >> (8 * i))); };
    auto u64 = [&](uint64_t v) { for (int i = 0; i < 8; ++i) out.push_back(static_cast<uint8_t>(v >> (8 * i))); };

    u8('D'); u8('2'); u8('S'); u8('1'); u8(kDiskIISnapVersion);  // 'D2S1' magic + ver
    u32(static_cast<uint32_t>(activeDrive));
    u8(static_cast<uint8_t>(active));
    u8(motorOn ? 1 : 0);
    u32(static_cast<uint32_t>(motorOffDelay));
    u8(writeMode ? 1 : 0);
    u8(loadMode ? 1 : 0);
    u8(iwmMode);
    u8(iwmWhd);
    u8(writeBackEnabled ? 1 : 0);
    u8(writeLatch);
    for (bool ph : phaseOn) u8(ph ? 1 : 0);
    for (int d = 0; d < kDriveCount; ++d) u32(static_cast<uint32_t>(headQuarterTrack[d]));
    for (int d = 0; d < kDriveCount; ++d) u32(static_cast<uint32_t>(trackPos[d]));
    u32(static_cast<uint32_t>(cycleAccum));
    u8(dataLatch);
    u8(byteReady ? 1 : 0);
    u8(serving13_ ? 1 : 0);
    u8(useBitLss ? 1 : 0);
    u8(address);
    u8(lssData);
    u64(lssCycle);
    u64(cpuCycleTotal);
    for (int d = 0; d < kDriveCount; ++d) u64(static_cast<uint64_t>(revolutionStartLssCycle[d]));

    // v2: writable media — undoes disk writes on a rewind. Gated so read-only
    // / WOZ / empty drives append only the 1-byte present flag.
    for (int d = 0; d < kDriveCount; ++d) {
        // Physical WP (not the write-back toggle) is what inhibits the
        // in-memory track write — capture whenever the medium can actually be
        // mutated at runtime. WOZ keeps its writes in a different store.
        const bool cap = images[d].isLoaded() &&
                         !images[d].isFileWriteProtected() && !images[d].isWoz();
        u8(cap ? 1 : 0);
        if (cap) {
            u64(mediaIdentityHash(images[d].getPath()));   // v3 identity
            images[d].appendMediaSnapshot(out);
        }
    }

    // v4: the in-flight write burst. Variable-length — an idle controller
    // (the common case) costs 13 bytes, a full burst 269.
    const int wp = (writePosition < 0) ? 0
                 : (writePosition > kWriteBufferSize ? kWriteBufferSize : writePosition);
    u32(static_cast<uint32_t>(wp));
    u8(writeLineActive ? 1 : 0);
    u64(static_cast<uint64_t>(writeStartTime));
    for (int i = 0; i < wp; ++i) u64(static_cast<uint64_t>(writeBuffer[i]));
}

void DiskIICard::loadSnapshotState(const uint8_t* data, std::size_t len)
{
    // Fixed layout, so a single up-front length check guards every read.
    constexpr std::size_t kBody =
        4 + 1 +                 // activeDrive + active
        1 + 4 +                 // motorOn + motorOffDelay
        1 + 1 +                 // writeMode + loadMode
        1 + 1 +                 // iwmMode + iwmWhd
        1 + 1 +                 // writeBackEnabled + writeLatch
        4 +                     // phaseOn[4]
        kDriveCount * 4 +       // headQuarterTrack
        kDriveCount * 4 +       // trackPos
        4 +                     // cycleAccum
        1 + 1 +                 // dataLatch + byteReady
        1 + 1 +                 // serving13_ + useBitLss
        1 + 1 +                 // address + lssData
        8 + 8 +                 // lssCycle + cpuCycleTotal
        kDriveCount * 8;        // revolutionStartLssCycle
    constexpr std::size_t kTotal = 5 + kBody;   // + magic(4) + version(1)
    if (len < kTotal) return;
    if (data[0] != 'D' || data[1] != '2' || data[2] != 'S' || data[3] != '1') return;
    const uint8_t version = data[4];
    if (version < 1 || version > kDiskIISnapVersion) return;

    // v2 appends one capture flag per drive and, when set, a fixed-size
    // writable-media image. Validate the whole tail before restoring the
    // controller or drive 1; a torn drive-2 tail otherwise left a hybrid.
    if (version >= 2) {
        // v3 prefixes each captured media block with an 8-byte identity
        // hash of the image path it was taken from.
        const std::size_t perCap = DiskImage::kMediaSnapshotBytes +
                                   (version >= 3 ? 8 : 0);
        std::size_t q = kTotal;
        for (int d = 0; d < kDriveCount; ++d) {
            if (q >= len) return;
            const uint8_t cap = data[q++];
            if (cap) {
                if (perCap > len - q) return;
                q += perCap;
            }
        }
        // v4 write-burst tail: header, then `count` 8-byte flux stamps.
        if (version >= 4) {
            if (len - q < 4 + 1 + 8) return;
            uint32_t wp = 0;
            for (int i = 0; i < 4; ++i) wp |= static_cast<uint32_t>(data[q + i]) << (8 * i);
            if (wp > static_cast<uint32_t>(kWriteBufferSize)) return;
            q += 4 + 1 + 8;
            if (static_cast<std::size_t>(wp) * 8 > len - q) return;
        }
    }

    std::size_t p = 5;
    auto g8  = [&]() -> uint8_t  { return data[p++]; };
    auto g32 = [&]() -> uint32_t { uint32_t v = 0; for (int i = 0; i < 4; ++i) v |= static_cast<uint32_t>(data[p++]) << (8 * i); return v; };
    auto g64 = [&]() -> uint64_t { uint64_t v = 0; for (int i = 0; i < 8; ++i) v |= static_cast<uint64_t>(data[p++]) << (8 * i); return v; };

    activeDrive   = static_cast<int>(g32());
    if (activeDrive < 0 || activeDrive >= kDriveCount) activeDrive = 0;  // index guard
    active        = static_cast<ActiveMode>(g8());
    if (active < MODE_IDLE || active > MODE_DELAY) active = MODE_IDLE;
    motorOn       = g8() != 0;
    motorOffDelay = static_cast<int>(g32());
    writeMode     = g8() != 0;
    loadMode      = g8() != 0;
    iwmMode       = g8();
    iwmWhd        = g8();
    // Propagate through setWriteBackEnabled so the per-drive DiskImages
    // stay in lock-step with the card flag (their isWriteProtected()
    // folds the toggle into the WP sense the LSS feeds RWTS, and
    // saveDirty() gates on it). A raw member restore left the images on
    // their pre-restore setting — e.g. a snapshot taken with write-back
    // ON restored into a session that started with it OFF made every
    // disk read back write-protected until the user re-toggled.
    setWriteBackEnabled(g8() != 0);
    writeLatch    = g8();
    for (auto& ph : phaseOn) ph = g8() != 0;
    for (int d = 0; d < kDriveCount; ++d) headQuarterTrack[d] = static_cast<int>(g32());
    for (int d = 0; d < kDriveCount; ++d) trackPos[d] = static_cast<int>(g32());
    cycleAccum    = static_cast<int>(g32());
    for (int d = 0; d < kDriveCount; ++d) {
        if (headQuarterTrack[d] < 0 ||
            headQuarterTrack[d] >= DiskImage::kQuarterTracks)
            headQuarterTrack[d] = 0;
        if (trackPos[d] < 0 || trackPos[d] >= DiskImage::kNibblesPerTrack)
            trackPos[d] = 0;
    }
    if (cycleAccum < 0 || cycleAccum >= kCyclesPerNibble) cycleAccum = 0;
    dataLatch     = g8();
    byteReady     = g8() != 0;
    serving13_    = g8() != 0;
    useBitLss     = g8() != 0;
    address       = g8();
    lssData       = g8();
    lssCycle      = g64();
    cpuCycleTotal = g64();
    for (int d = 0; d < kDriveCount; ++d) revolutionStartLssCycle[d] = static_cast<int64_t>(g64());

    // v2: per-drive writable media (present-flag byte, then the track buffers
    // when set). Only applied if the live drive actually holds a disk.
    if (version >= 2) {
        for (int d = 0; d < kDriveCount; ++d) {
            const uint8_t cap = g8();
            if (cap) {
                // Mirror the CAPTURE predicate: media snapshots are taken
                // only for non-WOZ writable images, so applying one onto a
                // drive that NOW holds a WOZ (user swapped disks after the
                // ring frame was recorded) wiped the WOZ's canonical bit
                // streams with the old disk's decoded tracks.
                bool apply = images[d].isLoaded() && !images[d].isWoz();
                if (version >= 3) {
                    // v3: the media snapshot names the image it was taken
                    // from — never apply it to a different disk. Without
                    // this, swap A→B then rewind past the swap copied A's
                    // tracks into the image bound to B's path, and the
                    // next saveDirty() overwrote B's FILE with A's data.
                    const uint64_t want = g64();
                    if (apply &&
                        mediaIdentityHash(images[d].getPath()) != want) {
                        apply = false;
                        pom2::log().warn("DiskII",
                            "rewind media snapshot skipped: drive " +
                            std::to_string(d) +
                            " holds a different disk than the one recorded");
                    }
                }
                if (apply)
                    images[d].loadMediaSnapshot(data + p, DiskImage::kMediaSnapshotBytes);
                p += DiskImage::kMediaSnapshotBytes;
            }
        }
    }

    // v4: the in-flight write burst. Bounds were validated above.
    if (version >= 4) {
        const int wp = static_cast<int>(g32());
        writeLineActive = g8() != 0;
        writeStartTime  = static_cast<int64_t>(g64());
        writePosition   = (wp < 0 || wp > kWriteBufferSize) ? 0 : wp;
        for (int i = 0; i < writePosition; ++i)
            writeBuffer[i] = static_cast<int64_t>(g64());
    } else {
        // Pre-v4 blobs carry no burst; start the restored controller from a
        // clean splice rather than from whatever the live card had mid-write.
        writePosition   = 0;
        writeLineActive = false;
        writeStartTime  = writeMode ? static_cast<int64_t>(lssCycle) : 0;
    }

    // The motor flag is a member, but the floppy sound device holds its own
    // spin state — restoring `motorOn` silently left the spindle sample
    // running after a rewind onto a stopped drive (or mute on a spinning
    // one). Re-drive it through the same call the live transitions use.
    if (sound_) sound_->motor(motorOn, images[activeDrive].isLoaded());

    // Re-point the IWM at the restored head position so the //c+ data path
    // and the restored LSS agree on the current track.
    pushIwmFloppy();
}

void DiskIICard::advanceCycles(int cycles)
{
    cpuCycleTotal += static_cast<uint64_t>(cycles);

    // Idle drive on the bit-level path (motor off AND spin-down elapsed):
    // nothing below would do anything — lssSync() returns on MODE_IDLE, the
    // spin-down countdown is over — so skip straight out. A plugged Disk II
    // is the common case and its drive is idle most of the time, yet this is
    // called once per emulated instruction through the slot fan-out.
    if (useBitLss && active == MODE_IDLE && motorOffDelay <= 0) return;

    // The DATA path (nibble/LSS) only runs with media present. The motor
    // spin-down delay, however, must tick REGARDLESS of media: a motor-off on
    // an empty selected drive still has to time out and stop, otherwise
    // motorOn / active stay stuck on forever (drive LED never clears, the
    // spin-down sound never fires). The early `return` here used to skip the
    // countdown below whenever the active drive had no disk.
    if (images[activeDrive].isLoaded()) {
        if (!useBitLss) {
            if (motorOn) legacyAdvance(cycles);
        } else {
            // MAME wozfdc: catch up the LSS to the new CPU time. lss_sync
            // skips when active == MODE_IDLE so a stopped drive is cheap.
            lssSync();
        }
    }

    // Tick the spin-down delay. When it expires the motor truly stops
    // (active drops to MODE_IDLE).
    if (motorOffDelay > 0) {
        motorOffDelay -= cycles;
        if (motorOffDelay <= 0) {
            motorOffDelay = 0;
            motorOn       = false;
            if (active == MODE_DELAY) {
                active = MODE_IDLE;
                // Commit any in-flight write splice BEFORE invalidating
                // the revolution anchor: the transitions in writeBuffer
                // were captured under THIS spin's timeline, so they must
                // be reduced with THIS spin's anchor (MAME mon_w(true)
                // keeps writes and m_revolution_start_time coherent).
                // Deferring to the eventual Q7L flush would pair the
                // old-timeline buffer with kNeverRev — the exact
                // mixed-anchor corruption the writeFlux anchor exists
                // to eliminate.
                DiskImage& img = images[activeDrive];
                if (writeMode && writeBackEnabled && img.isLoaded()
                    && writePosition > 0) {
                    img.writeFlux(headQuarterTrack[activeDrive],
                                  writeStartTime,
                                  static_cast<int64_t>(lssCycle),
                                  writePosition, writeBuffer,
                                  revolutionStartLssCycle[activeDrive]);
                    ++writeFlushCount;
                    writePosition  = 0;
                    writeStartTime = static_cast<int64_t>(lssCycle);
                }
                // MAME `floppy_image_device::mon_w(true)`: when the
                // controller actually stops driving the spindle, the
                // drive's revolution timestamp becomes `attotime::never`.
                // POM2's equivalent: clear the anchor so a subsequent
                // motor-on event re-zeros it from the new spin-up.
                revolutionStartLssCycle[activeDrive] = kNeverRev;
            }
            if (sound_) sound_->motor(false, images[activeDrive].isLoaded());
        }
    }
}

void DiskIICard::legacyAdvance(int cycles)
{
    DiskImage& img = images[activeDrive];
    int& pos       = trackPos[activeDrive];
    // Legacy 32-cycle gate operates on whole-track nibble buffers
    // (.dsk/.do/.po/.nib formats only — WOZ disks force the LSS path
    // via `useBitLss=true` on insert). Quarter-track granularity isn't
    // meaningful on the legacy gate; snap to the containing whole
    // track.
    const int track = headQuarterTrack[activeDrive] / 4;
    cycleAccum += cycles;
    while (cycleAccum >= kCyclesPerNibble) {
        cycleAccum -= kCyclesPerNibble;
        pos = (pos + 1) % DiskImage::kNibblesPerTrack;
        if (writeMode && motorOffDelay <= 0) {
            // Write the most-recently-latched nibble onto the track.
            // Real hardware streams bits through the LSS shift register;
            // we model one nibble per ~32 CPU cycles, matching the read
            // pacing. The CPU latches the next nibble via a soft-switch
            // store (see deviceSelectWrite). Honour writeBackEnabled
            // symmetrically with the LSS path — the user toggle off
            // must keep host files intact regardless of which gate is
            // active. During the 556 motor-off COAST the gate serves
            // READS only (that is what RWTS's spin check needs): before
            // the coast existed a motor-off stopped everything at once,
            // and letting a stale write-mode flag spray nibbles through
            // the window regressed `iic_external_smartport` case E — the
            // //c+ IWM forwarding leaves the shadow Disk II in write
            // mode while the 3.5" boots, and its 5.25" must take ZERO
            // flux from that traffic.
            if (writeBackEnabled) {
                img.writeNibbleAt(track, pos, writeLatch);
                ++writeFlushCount;
            }
        } else {
            dataLatch = img.nibbleAt(track, pos);
            byteReady = true;
        }
    }
}

// MAME `wozfdc_device::lss_start` — called from control() when the motor
// transitions to MODE_ACTIVE. Resets the LSS bookkeeping so we don't
// carry stale state from the last spin-up. Note we explicitly do NOT
// re-pin the data register on a MODE_DELAY → MODE_ACTIVE transition
// (real hardware preserves it across the spin-down window).
//
// This also models MAME's `floppy_image_device::mon_w(false)` for the
// currently-selected drive: anchor its `revolution_start_time` to "now"
// so the disk's angular position reads as zero immediately after spin-up.
// The other drive (if any) keeps whatever `revolutionStartLssCycle` it
// had — MAME never touches an idle drive's revolution state from the
// controller side.
void DiskIICard::lssStart()
{
    DiskImage& img = images[activeDrive];
    lssCycle        = cpuCycleTotal * 2;
    lssData         = 0;
    address         = static_cast<uint8_t>(address & ~0x0E);
    writePosition   = 0;
    writeStartTime  = writeMode ? static_cast<int64_t>(lssCycle) : 0;
    writeLineActive = false;
    revolutionStartLssCycle[activeDrive] = static_cast<int64_t>(lssCycle);
    if (writeMode && img.isLoaded()) {
        img.setWriteSplice(headQuarterTrack[activeDrive], writeStartTime);
    }
}

// MAME `wozfdc_device::lss_sync(extra_cycles)` — verbatim port. The LSS
// runs at 2× CPU clock; one PROM lookup per LSS cycle. We catch up from
// the persistent `lssCycle` counter to a target derived from the CPU
// total, optionally with an `extra` LSS-cycle bump to model the read-
// pipe latency on $C0nC reads. PULSE is set for exactly one LSS cycle
// when the head crosses a flux transition, fed from
// DiskImage::getNextTransition (the flux model port).
void DiskIICard::lssSync(uint64_t extraCycles)
{
    if (active == MODE_IDLE) return;
    DiskImage& img = images[activeDrive];
    if (!img.isLoaded()) {
        // Empty drive — or, for drive 2 on a one-drive machine, an absent
        // one. Freezing `lssData` here HUNG THE MACHINE: the universal
        // "wait for a nibble" idiom is `LDA $C08C,X / BPL -3`, and a data
        // register that never changes keeps bit 7 clear forever, so the
        // guest never even reaches the timeout counter that follows its
        // own loop. Ultima V's "Save Music Configuration" does exactly
        // this at $D407 — it targets drive 2, where the BRITANNIA disk
        // belongs — and POM2 froze there on any WOZ. The legacy nibble
        // gate never had the bug: `deviceSelectRead` returns $FF for an
        // empty drive, which is why the same game errors out cleanly from
        // a .dsk and hangs from a .woz.
        //
        // Real hardware leaves the read amplifier on noise, so the latch
        // keeps shifting garbage, bit 7 comes up, and RWTS times out into
        // an I/O error. Model that: one pseudo-random byte per 8 bit cells
        // (4 us each → 64 LSS cycles), high bit set as on every byte the
        // LSS ever hands the CPU. Derived from the cycle cursor by hash
        // rather than from a PRNG member: no hidden generator state to
        // serialise, so REWIND reproduces the byte exactly (RewindBuffer
        // captures with includeSlots=true and restores this cursor). A FILE
        // save-state does NOT — it captures with includeSlots=false, so no
        // slot section is written and the cursor keeps its free-running value
        // across a load. Nothing here makes that worse (the rest of the LSS
        // timing is equally unrestored), but do not read the hash as a promise
        // of save-state determinism.
        // Pinned by tests/diskii_empty_drive_test.cpp.
        const uint64_t target = cpuCycleTotal * 2 + extraCycles;
        if (target > lssCycle) {
            uint64_t h = (target / 64) * 0x9E3779B97F4A7C15ull;
            h ^= h >> 29;
            h *= 0xBF58476D1CE4E5B9ull;
            h ^= h >> 32;
            lssData = static_cast<uint8_t>(static_cast<uint8_t>(h) | 0x80);
        }
        lssCycle = target;
        return;
    }

    // Quarter-track index drives every LSS-side image access — WOZ
    // images expose a distinct flux stream per quarter-track (Spiradisc
    // / RWTS18 / Locksmith protections rely on this); non-WOZ aliases
    // four quarter-tracks per whole-track inside DiskImage.
    const int qt = headQuarterTrack[activeDrive];

    // MAME passes `cycles_to_time(cycles - 1)` to `get_next_transition`, but
    // that's NOT a "look one cycle into the past" — it's compensating for
    // MAME's `cycles_to_time` ⇄ `time_to_cycles` round-trip having a +1
    // LSS-tick offset baked into both halves (see `time_to_cycles` body in
    // `wozfdc.cpp` line 331). In MAME's reference frame, `cycles_to_time(c)`
    // returns a time *strictly after* the floppy-stored time of the event at
    // MAME cycle c — so passing `c-1` finds the event at c (or later), never
    // at c-1.
    //
    // Our port stores flux events as raw LSS-cycle indexes (`cell*8 + 4` per
    // `expandTrackFlux`), so we don't need — and must not apply — the
    // compensation. Pass `lssCycle` directly: `getNextTransition` has
    // lower-bound semantics, returning the event at lssCycle if there is
    // one and the next one otherwise.
    //
    // Subtracting 1 here was a misapplied transcription of MAME's compensation.
    // It made `getNextTransition` return the *previous* event (the one we
    // just processed) whenever lssSync re-entered at `prev_nextFluxDown`.
    // The loop then computed `cyclesNextTrans = cyclesLimit` (since both
    // `lssCycle < nextFlux` and `lssCycle < nextFluxDown` were false for a
    // past event), ran the inner loop straight to cyclesLimit, and silently
    // skipped every flux event in the open interval (prev_event, cyclesLimit].
    // The skipped events were dropped permanently — the next call's
    // `getNextTransition` rolled past them too. With ~1.0227 MHz CPU and
    // ~125 KB/s read rate, that worked out to lost cells under sustained
    // reads, surfacing as DOS / ProDOS I/O errors and RWTS retries on real
    // disks even though the boot-prologue smoke test (which only validates
    // a single D5 AA 96 match in a 5-revolution scan) couldn't see it.
    //
    // Pinned by `tests/diskii_lss_smoke_test.cpp::testFullSectorReadback`
    // (added with this fix).
    const int64_t revStart = revolutionStartLssCycle[activeDrive];
    int64_t nextFlux = img.getNextTransition(qt,
                          static_cast<int64_t>(lssCycle), revStart);
    int64_t nextFluxDown = (nextFlux != DiskImage::kFluxNever)
                              ? nextFlux + 1
                              : DiskImage::kFluxNever;

    // DIAGNOSTIC (POM2_TRACE_LSS=path): sampled LSS state to see whether
    // lssCycle / nextFlux / qt advance during a stuck read. Every 80th
    // call, capped, so the window spans the whole boot.
    if (g_lssTraceFile) {
        FILE* const lf = g_lssTraceFile;
        long& lc = g_lssTraceCalls;
        long& kept = g_lssTraceKept;
        if ((lc++ % 80) == 0 && kept < 4000) {
            std::fprintf(lf,
                "cyc=%llu lss=%lld qt=%d rev=%lld nextFlux=%lld nflen=%d data=%02X\n",
                static_cast<unsigned long long>(cpuCycleTotal),
                static_cast<long long>(lssCycle), qt,
                static_cast<long long>(revStart),
                static_cast<long long>(nextFlux),
                static_cast<int>(img.fluxEvents(qt).size()), lssData);
            ++kept;
        }
    }

    // Initial PULSE state: address bit 4 low for the LSS-cycle range
    // [nextFlux, nextFluxDown), high otherwise. (MAME: `if(cycles >= cycles_next_flux && cycles < cycles_next_flux_down) address &= ~0x10; else address |= 0x10;`)
    if (static_cast<int64_t>(lssCycle) >= nextFlux
        && static_cast<int64_t>(lssCycle) < nextFluxDown) {
        address = static_cast<uint8_t>(address & ~0x10);
    } else {
        address = static_cast<uint8_t>(address | 0x10);
    }

    const uint64_t cyclesLimit = cpuCycleTotal * 2 + extraCycles;
    if (lssCycle > cyclesLimit) return;        // safety: never go back

    while (lssCycle < cyclesLimit) {
        // Advance to the next "transition" — either the catch-up limit,
        // the next flux rising edge, or the falling edge after it.
        int64_t cyclesNextTrans = static_cast<int64_t>(cyclesLimit);
        if (cyclesNextTrans > nextFlux
            && static_cast<int64_t>(lssCycle) < nextFlux) {
            cyclesNextTrans = nextFlux;
        }
        if (cyclesNextTrans > nextFluxDown
            && static_cast<int64_t>(lssCycle) < nextFluxDown) {
            cyclesNextTrans = nextFluxDown;
        }

        while (static_cast<int64_t>(lssCycle) < cyclesNextTrans) {
            const uint8_t op = p6Rom[address];

            // Write side: edge-detect on WRITE_DATA (= address bit 7).
            // Each toggle becomes one flux event in the splice buffer,
            // timestamped at the current LSS cycle. When the buffer
            // approaches its 32-entry capacity, pre-emptively flush via
            // image.writeFlux so we never miss a transition.
            if (writeMode) {
                const bool prev = writeLineActive;
                const bool curr = (address & 0x80) != 0;
                if (prev != curr) {
                    writeLineActive = curr;
                    if (writePosition < kWriteBufferSize) {
                        writeBuffer[writePosition++] =
                            static_cast<int64_t>(lssCycle);
                    }
                } else if (writePosition >= 30) {
                    const int64_t now = static_cast<int64_t>(lssCycle);
                    if (writeBackEnabled) {
                        // Pass the drive's revolution anchor — MAME's
                        // write_flux maps the window through the same
                        // find_position(m_revolution_start_time) the
                        // read side uses (floppy.cpp ~:1050-1125), so
                        // the splice must share getNextTransition's
                        // anchor or it lands at the wrong angle.
                        img.writeFlux(qt, writeStartTime, now,
                                      writePosition, writeBuffer, revStart);
                        ++writeFlushCount;
                    }
                    writeStartTime = now;
                    writePosition  = 0;
                }
            }

            // Update state bits of address (7,6,5,0) from opcode bits
            // (7,6,4,5) using MAME's exact PROM-pin pack.
            address = static_cast<uint8_t>((address & 0x1E)
                    | (op & 0xC0)
                    | ((op & 0x20) >> 5)
                    | ((op & 0x10) << 1));

            // ALU dispatch — MAME's full opcode range, no fall-through.
            switch (op & 0x0F) {
                case 0x0: case 0x1: case 0x2: case 0x3:
                case 0x4: case 0x5: case 0x6: case 0x7:
                    lssData = 0;
                    break;
                case 0x8: case 0xC:
                    break;
                case 0x9:
                    lssData = static_cast<uint8_t>(lssData << 1);
                    break;
                case 0xA: case 0xE:
                    lssData = static_cast<uint8_t>((lssData >> 1)
                        | (img.isWriteProtected() ? 0x80 : 0x00));
                    break;
                case 0xB: case 0xF:
                    lssData = writeLatch;
                    break;
                case 0xD:
                    lssData = static_cast<uint8_t>((lssData << 1) | 0x01);
                    break;
            }

            // QA = data MSB.
            if (lssData & 0x80) address |= 0x02; else address &= ~0x02;
            ++lssCycle;
        }

        // Cross the flux transition. PULSE goes low at nextFlux and
        // high again at nextFluxDown; advance the flux cursor when we
        // exit the high region.
        if (static_cast<int64_t>(lssCycle) == nextFlux) {
            address = static_cast<uint8_t>(address & ~0x10);
        } else if (static_cast<int64_t>(lssCycle) == nextFluxDown) {
            address = static_cast<uint8_t>(address | 0x10);
            nextFlux = img.getNextTransition(qt,
                          static_cast<int64_t>(lssCycle), revStart);
            nextFluxDown = (nextFlux != DiskImage::kFluxNever)
                               ? nextFlux + 1
                               : DiskImage::kFluxNever;
        }
    }

    if (debugEnabled() && (lssData & 0x80) && !trace.sawFirstNibble) {
        trace.sawFirstNibble = true;
        char buf[96];
        std::snprintf(buf, sizeof(buf),
            "first GCR nibble served: $%02X (LSS, qt %d / track %d)",
            lssData, qt, qt / 4);
        pom2::log().info("Disk II", buf);
    }
}

// MAME `wozfdc_device::control()` cases 0xa/0xb — drive_select switch.
// When motor is active, mon_w(true) is sent to the old drive (commits
// in-flight writes, freezes the flux cursor; sets
// `revolution_start_time = attotime::never`) and mon_w(false) to the
// new drive (revolution_start_time = now, restart spin). The equivalent
// in POM2's model:
//   1. If `writeMode` and there are pending events in the write buffer,
//      flush them to the OLD drive's track at the current LSS cycle.
//      (Real silicon: the write head stops driving the surface; any
//      flux events captured since the last splice land in the track.)
//   2. Mark the OLD drive's `revolutionStartLssCycle` as `kNeverRev`
//      (MAME's `attotime::never`) — its disk stops contributing to flux
//      reads. Leave the controller's `lssCycle` alone; MAME keeps
//      `cycles` running across drive swaps.
//   3. Anchor the NEW drive's `revolutionStartLssCycle` to the current
//      `lssCycle`. MAME `floppy_image_device::mon_w(false)` sets
//      `m_revolution_start_time = machine().time()`; the new spin-up
//      conceptually starts now. (For a single-drive system this is
//      academic — the only motor-on transition came from `lssStart`
//      itself, which already set the anchor — but the multi-drive
//      $C0EA / $C0EB swap path must do it explicitly.)
//   4. Re-init the write-state cursor for the new drive so a write that
//      survives the drive swap (rare but legal: WRITE mode + drive swap
//      mid-burst) splices into the right track at the right LSS cycle.
//   5. Clear PULSE in the LSS address — the new drive's flux stream is
//      fresh, the previous-drive's pending pulse no longer applies.
//
// Reference: MAME `wozfdc.cpp:219-241`,
// `floppy.cpp:809-839` (mon_w).
void DiskIICard::selectDrive(int newDrive)
{
    if (newDrive == activeDrive) return;
    const int oldDrive = activeDrive;
    if (active != MODE_IDLE) {
        // Flush in-flight writes to OLD drive (mon_w(true) → commit_image).
        DiskImage& oldImg = images[oldDrive];
        if (writeMode && oldImg.isLoaded() && writeBackEnabled
            && writePosition > 0) {
            // Anchored on the OLD drive's revolution start (read before
            // it's reset to kNeverRev below) — same anchor its reads used.
            oldImg.writeFlux(headQuarterTrack[oldDrive],
                             writeStartTime,
                             static_cast<int64_t>(lssCycle),
                             writePosition, writeBuffer,
                             revolutionStartLssCycle[oldDrive]);
            ++writeFlushCount;
        }
        writePosition   = 0;
        writeLineActive = false;

        // OLD drive: mon_w(true). Disk angular position is now undefined
        // — flux reads against it would return nothing. MAME uses
        // `attotime::never` for the same effect.
        revolutionStartLssCycle[oldDrive] = kNeverRev;

        // Switch drives. Do NOT reset `lssCycle` — MAME's `cycles` keeps
        // running continuously across the swap (`a3_update_drive_sel`
        // calls `lss_sync()` but never touches the controller's clock).
        activeDrive = newDrive;
        // NEW drive: mon_w(false). Anchor angular position to "now".
        revolutionStartLssCycle[newDrive] = static_cast<int64_t>(lssCycle);
        address  = static_cast<uint8_t>(address | 0x10);   // PULSE = no pulse
        writeStartTime = writeMode ? static_cast<int64_t>(lssCycle) : 0;
        if (writeMode && images[newDrive].isLoaded()) {
            images[newDrive].setWriteSplice(
                headQuarterTrack[newDrive], writeStartTime);
        }
    } else {
        // Motor off — no mon_w transition to model. Just remember the
        // selection for the next motor-on event.
        activeDrive = newDrive;
    }
    pushIwmFloppy();
}

// MAME `wozfdc_device::control(offset)` — verbatim port. Only POM2-
// specific bits: we lack the F9334 phaselatch device, so we expand the
// `m_phaselatch->write_bit(phase, on)` path inline (sets phaseOn[i] and
// invokes seekPhaseW with the resulting 4-bit mask).
void DiskIICard::control(int offset)
{
    if (offset < 8) {
        const int  phase = offset >> 1;
        const bool on    = (offset & 1) != 0;
        phaseOn[phase]   = on;
        int mask = 0;
        for (int i = 0; i < 4; ++i) if (phaseOn[i]) mask |= (1 << i);
        if (active) seekPhaseW(mask);
        return;
    }

    switch (offset) {
        case 0x8:
            if (active == MODE_ACTIVE) {
                motorOffDelay = 1'022'727;   // 1 sec @ 1.0227 MHz
                active = MODE_DELAY;
            }
            break;
        case 0x9:
            switch (active) {
                case MODE_IDLE:
                    motorOn = true;
                    active  = MODE_ACTIVE;
                    if (images[activeDrive].isLoaded()) lssStart();
                    if (sound_) sound_->motor(true, images[activeDrive].isLoaded());
                    if (debugEnabled() && !trace.sawMotorOn) {
                        trace.sawMotorOn = true;
                        char buf[96];
                        std::snprintf(buf, sizeof(buf),
                            "motor ON (drive %d, head at quarter-track %d, disk %s)",
                            activeDrive + 1,
                            headQuarterTrack[activeDrive],
                            images[activeDrive].isLoaded() ? "loaded" : "MISSING");
                        pom2::log().info("Disk II", buf);
                    }
                    break;
                case MODE_DELAY:
                    active        = MODE_ACTIVE;
                    motorOffDelay = 0;
                    motorOn       = true;
                    break;
                case MODE_ACTIVE:
                    break;
            }
            break;
        case 0xa:
            // Drive 1 select. MAME `wozfdc.cpp:219-227`: when active,
            // mon_w(true) on the old drive (commit writes, freeze flux)
            // + mon_w(false) on the new drive (revolution_start_time =
            // now). `selectDrive()` models both halves of the swap.
            selectDrive(0);
            break;
        case 0xb:
            // Drive 2 select. MAME `wozfdc.cpp:229-241`. Same as 0xa
            // but onto images[1]. The TODO regression we fix here: the
            // previous `activeDrive = 1` direct assignment left the LSS
            // cycle base unchanged, so drive 2 was reading flux at the
            // shared lssCycle modulo its track period — not from
            // position 0 of its current track the way MAME models it.
            // Multi-drive copy protections (Locksmith, Copy II Plus)
            // that switch drive mid-spin depend on this.
            selectDrive(1);
            break;
        case 0xc:
            if (loadMode) {
                if (active) address = static_cast<uint8_t>(address & ~0x04);
                loadMode = false;
            }
            break;
        case 0xd:
            if (!loadMode) {
                if (active) address = static_cast<uint8_t>(address | 0x04);
                loadMode = true;
            }
            break;
        case 0xe:
            if (writeMode) {
                if (active) address = static_cast<uint8_t>(address & ~0x08);
                writeMode = false;
                // MAME: `floppy->write_flux(write_start_time, now,
                // write_position, write_buffer);` — splice the in-flight
                // events into the track on Q7 falling edge.
                DiskImage& img = images[activeDrive];
                if (img.isLoaded() && writeBackEnabled
                    && writePosition > 0) {
                    // Same revolution anchor as the read path (MAME
                    // write_flux → find_position, floppy.cpp ~:1050-1125).
                    img.writeFlux(headQuarterTrack[activeDrive],
                                  writeStartTime,
                                  static_cast<int64_t>(lssCycle),
                                  writePosition, writeBuffer,
                                  revolutionStartLssCycle[activeDrive]);
                    ++writeFlushCount;
                }
                writePosition = 0;
            }
            break;
        case 0xf:
            if (!writeMode) {
                if (active) {
                    address = static_cast<uint8_t>(address | 0x08);
                    writeStartTime = static_cast<int64_t>(lssCycle);
                    writePosition  = 0;
                    DiskImage& img = images[activeDrive];
                    if (img.isLoaded()) {
                        img.setWriteSplice(headQuarterTrack[activeDrive],
                                           writeStartTime);
                    }
                }
                writeMode = true;
            }
            break;
        default: break;
    }
}

void DiskIICard::handleSwitchAccess(uint8_t low4)
{
    if (debugEnabled() && !trace.sawDevSelect) {
        trace.sawDevSelect = true;
        char buf[64];
        std::snprintf(buf, sizeof(buf),
            "first soft switch hit (low4=$%X)", low4);
        pom2::log().info("Disk II", buf);
    }

    if (!useBitLss) {
        // Legacy gate behaviour — preserved verbatim from pre-MAME-port
        // code so disk_boot_smoke / dos33_save_smoke / prodos_save tests
        // (which don't load the P6 ROM) keep their pinned semantics.
        if (low4 < 8) {
            const int  phase = low4 >> 1;
            const bool on    = (low4 & 1) != 0;
            phaseOn[phase]   = on;
            int mask = 0;
            for (int i = 0; i < 4; ++i) if (phaseOn[i]) mask |= (1 << i);
            seekPhaseW(mask);
            return;
        }
        switch (low4) {
            case 0x8:
                // The controller's 556 one-shot keeps the spindle driven for
                // ~1 s after a motor-off — the same MODE_DELAY the bit-LSS
                // path ports from MAME (`control()` case 0x8). The legacy
                // gate used to stop the drive INSTANTLY, and that is what
                // made every headless RWTS call pay the full one-second
                // motor-on wait: RWTS decides "the disk is spinning" by
                // reading $C08C repeatedly BEFORE it re-asserts $C0E9, and a
                // frozen $FF latch fails the check on every sector (DOS 3.3
                // took ~115 s of machine time to boot to the prompt).
                // `motorOn` stays true through the window — the nibble gate
                // keeps turning — and the countdown in advanceCycles() stops
                // the drive (and fires the spin-down sound) when it expires.
                if (motorOn && motorOffDelay <= 0)
                    motorOffDelay = 1'022'727;   // 1 sec @ 1.0227 MHz
                break;
            case 0x9:
                if (!motorOn) {
                    cycleAccum = 0;
                    if (sound_) sound_->motor(true, images[activeDrive].isLoaded());
                    if (debugEnabled() && !trace.sawMotorOn) {
                        trace.sawMotorOn = true;
                        char buf[96];
                        std::snprintf(buf, sizeof(buf),
                            "motor ON (drive %d, head at quarter-track %d, disk %s)",
                            activeDrive + 1,
                            headQuarterTrack[activeDrive],
                            images[activeDrive].isLoaded() ? "loaded" : "MISSING");
                        pom2::log().info("Disk II", buf);
                    }
                }
                motorOn = true;
                motorOffDelay = 0;
                break;
            // $C0nA / $C0nB: drive_select. Both code paths (LSS and
            // legacy gate) honour the same activeDrive so the legacy
            // tests can exercise drive 2 too. The legacy 32-cycle gate
            // doesn't model a per-drive flux phase, so the mon_w
            // transition is a near-no-op here — selectDrive() still
            // flushes any pending write buffer (defence in depth, even
            // though the legacy path doesn't populate it).
            case 0xA: selectDrive(0); break;
            case 0xB: selectDrive(1); break;
            case 0xC: loadMode  = false; break;
            case 0xD: loadMode  = true;  break;
            case 0xE: writeMode = false; break;
            case 0xF: writeMode = true;  break;
            default: break;
        }
        return;
    }

    // MAME path: control() handles every soft-switch effect.
    control(low4);
}

// ─── Sub-instruction cycle accuracy ────────────────────────────────────
//
// MMIO accesses from the 6502 happen at a specific cycle within the
// instruction (e.g. `LDA $C0EC`'s data fetch is the 4th of 4 cycles).
// MAME's `m6502.cpp` is a per-cycle state machine — its `wozfdc_device`
// observes each access at the precise sub-instruction time.
//
// POM2's M6502 batches the whole instruction's cycles into a single
// `memory->advanceCycles(N)` after `executeOpcode` returns; during
// execution, `cpuCycleTotal` reflects the START of the instruction. For
// stock DOS / ProDOS RWTS the difference is invisible — the LSS lands
// the same nibbles either way. But cycle-precise copy protections that
// time their reads against the LSS state ARE off by a few cycles.
//
// The fix is to query `cpu->getCurrentInstructionCycles()` at the
// access point: that's the count of cycles already elapsed within the
// current instruction (e.g. 3 at the data fetch of `LDA abs`). We
// temporarily inflate `cpuCycleTotal` by this delta during the access,
// run `lssSync` against the inflated value, and restore on the way out
// (so the post-instruction `advanceCycles(N)` accounts for the right
// total). The RAII guard below makes this exception-safe and keeps the
// save/restore out of every code path of `deviceSelectRead/Write`.
//
// Mid-instruction inflation pattern:
//   cpuCycleTotal_before_inst = X
//   in deviceSelectRead: cpuCycleTotal += subCycles  (X + 3 for LDA $C0EC)
//                        lssSync(0) catches LSS to 2*(X+3)
//                        lssSync(1) catches to 2*(X+3) + 1
//                        cpuCycleTotal restored to X (RAII dtor)
//   after instruction: advanceCycles(4) → cpuCycleTotal = X + 4
//                      lssSync(0) catches LSS to 2*(X+4) = 2*(X+3) + 2
//
// Net: LSS runs 8 cycles per instruction (same as before), but the data
// register is sampled at the correct sub-cycle within the instruction.
struct SubInstructionScope
{
    uint64_t& target;
    uint64_t saved;
    SubInstructionScope(uint64_t& counter, uint64_t add)
        : target(counter), saved(counter) { target += add; }
    ~SubInstructionScope() { target = saved; }
};

uint8_t DiskIICard::deviceSelectRead(uint8_t low4)
{
    if (useBitLss) {
        // MAME `wozfdc_device::read(offset)`:
        //   lss_sync();
        //   control(offset);
        //   if(!(offset & 1)) { lss_sync(1); return data_reg; }
        //   return 0xff;
        SubInstructionScope sub(cpuCycleTotal,
            cpu_ ? static_cast<uint64_t>(cpu_->getCurrentInstructionCycles()) : 0);
        lssSync(0);
        const bool wasQ6 = loadMode;
        handleSwitchAccess(low4);
        // IWM status read hook (MAME `iwm.cpp:107-109`, case 0x40):
        //   read $C0nE with Q6 high + Q7 low (this access clears Q7 but
        //   Q6 was already on) → return (status & 0x7F) | (wpt ? 0x80 : 0).
        //   status low 5 = mode low 5 (MAME `iwm.cpp:259`). The Apple //c+
        //   alt firmware probes this; without it the boot loop at $E51B
        //   (BEQ on `Y EOR status & $1F`) never falls through and the
        //   Monitor hangs before clearing the text page.
        if (low4 == 0xE && wasQ6) {
            DiskImage& img = images[activeDrive];
            const uint8_t wpt = (!img.isLoaded() || img.isWriteProtected()) ? 0x80 : 0x00;
            return static_cast<uint8_t>(wpt | (iwmMode & 0x1F));
        }
        // IWM write-handshake read hook (MAME `iwm.cpp:107-110`, case
        // 0x80): read $C0nC with Q7 high + Q6 low → return m_whd.
        // POM2 doesn't run an IWM bit-shift timer in parallel with
        // the CPU, so we model whd at its idle resting value (0xBF):
        // bit 7 ("not-underrun" — 1 = ready) high, bit 6 ("write
        // request pending") low. The transient bit-6-set state that
        // a real IWM enters on entering MODE_WRITE only matters for
        // software with bit-cell-accurate timing requirements; the
        // //c+ alt firmware's `$C8A6: BIT $C0EC / BPL` ready loop and
        // its `$C960` companion both pass with bit-6-clear.
        if (low4 == 0xC && writeMode) {
            return iwmWhd;
        }
        if (!(low4 & 1)) {
            lssSync(1);
            // Debug log: capture (cycle, byte, qt) for hero_probe to dump.
            static const bool kLogReads = std::getenv("POM2_DEBUG_DISK_READS") != nullptr;
            if (kLogReads && low4 == 0xC) {
                if (readLog_.size() < kReadLogCap) {
                    readLog_.push_back({cpuCycleTotal, lssData,
                        static_cast<uint8_t>(headQuarterTrack[activeDrive])});
                } else {
                    readLog_[readLogCursor_++ % kReadLogCap] =
                        {cpuCycleTotal, lssData,
                         static_cast<uint8_t>(headQuarterTrack[activeDrive])};
                }
            }
            // Optional CSV stream log for post-mortem LSS analysis. Open
            // once on first hit when `POM2_DEBUG_DISK_STREAM=path` is set;
            // each $C0EC read appends `cycle,qt,data` so a Python pass can
            // reconstruct exactly what the controller delivered to the
            // CPU. Lifetime tied to process exit (FILE leaked
            // intentionally — flush-on-exit via stdio shutdown handler).
            static FILE* g_streamLog = []() -> FILE* {
                const char* path = std::getenv("POM2_DEBUG_DISK_STREAM");
                if (!path) return nullptr;
                FILE* f = std::fopen(path, "w");
                if (f) std::fprintf(f, "cycle,qt,data\n");
                return f;
            }();
            if (g_streamLog && low4 == 0xC) {
                std::fprintf(g_streamLog, "%llu,%d,%02x\n",
                    static_cast<unsigned long long>(cpuCycleTotal),
                    headQuarterTrack[activeDrive],
                    lssData);
            }
            return lssData;
        }
        // For odd offsets MAME returns 0xFF (open bus), but POM2 still
        // needs the write-protect probe at $C0nD (low4=0xD, !writeMode).
        //
        // An EMPTY drive reads as WRITE-PROTECTED, same as the $C0nE answer
        // above. That is what the hardware does — the sense is a phototransistor
        // watching the notch, and with no disk in the way the light reaches it,
        // which is the protected state — and it is what this card already told
        // anyone who asked through $C0nE. Answering 0x00 here said "writable"
        // about a drive with nothing in it, so the two probes for one wire
        // disagreed depending on which idiom the guest happened to use.
        if (low4 == 0xD && !writeMode) {
            DiskImage& img = images[activeDrive];
            return (!img.isLoaded() || img.isWriteProtected()) ? 0x80 : 0x00;
        }
        return 0xFF;
    }

    // Legacy gate path.
    const bool wasQ6Legacy = loadMode;
    handleSwitchAccess(low4);
    // IWM status read hook (same as the bit-LSS path above). Mirrored
    // here because POM2's test-rig and pre-disk-insert state both pin
    // `useBitLss = false` until a WOZ image or P6 PROM is in flight —
    // and the //c+ alt firmware probes $C0EE *before* the user clicks
    // a disk in the library.
    if (low4 == 0xE && wasQ6Legacy) {
        DiskImage& img = images[activeDrive];
        const uint8_t wpt = (!img.isLoaded() || img.isWriteProtected()) ? 0x80 : 0x00;
        return static_cast<uint8_t>(wpt | (iwmMode & 0x1F));
    }
    if (low4 == 0xC && writeMode) {
        return iwmWhd;
    }
    DiskImage& img = images[activeDrive];
    if (low4 == 0xC && !writeMode && !loadMode) {
        if (!img.isLoaded() || !motorOn) return 0xFF;
        const uint8_t out = byteReady ? dataLatch : (dataLatch & 0x7F);
        if (debugEnabled() && byteReady && !trace.sawFirstNibble) {
            trace.sawFirstNibble = true;
            char buf[96];
            std::snprintf(buf, sizeof(buf),
                "first GCR nibble served: $%02X (drive %d, track %d, pos %d)",
                dataLatch, activeDrive + 1,
                headQuarterTrack[activeDrive] / 4,
                trackPos[activeDrive]);
            pom2::log().info("Disk II", buf);
        }
        byteReady = false;
        return out;
    }
    // Same wire, same answer as the bit-LSS path and as $C0nE: no disk reads
    // as write-protected.
    if (low4 == 0xD && !writeMode) {
        return (!img.isLoaded() || img.isWriteProtected()) ? 0x80 : 0x00;
    }
    return 0;
}

void DiskIICard::deviceSelectWrite(uint8_t low4, uint8_t v)
{
    if (useBitLss) {
        // MAME `wozfdc_device::write(offset, data)`:
        //   lss_sync();
        //   control(offset);
        //   last_6502_write = data;
        SubInstructionScope sub(cpuCycleTotal,
            cpu_ ? static_cast<uint64_t>(cpu_->getCurrentInstructionCycles()) : 0);
        lssSync(0);
        const bool wasQ6 = loadMode;
        handleSwitchAccess(low4);
        // IWM mode_w hook (MAME `iwm.cpp:248-253`): writes to $C0nF when
        // Q6 was already high latch the mode register. Real wozfdc has
        // no such register so the //c+ alt-firmware probe at $E512-$E522
        // (in bank 1) spins forever without this.
        if (low4 == 0xF && wasQ6) {
            iwmMode = v;
        }
        writeLatch = v;
        return;
    }

    // Legacy gate path. Mirror MAME wozfdc's `last_6502_write = data` —
    // latch every $C0Ex write regardless of low nibble, so a write to
    // any switch in the range (Q6 toggle, drive select, …) refreshes
    // the byte the next nibble flush will emit. The legacy advance
    // still consumes `writeLatch` only when `writeMode` is on, so
    // unconditional latching is harmless in read mode.
    const bool wasQ6LegacyW = loadMode;
    handleSwitchAccess(low4);
    // IWM mode_w shadow (matches the bit-LSS branch above). Required
    // for the //c+ alt-firmware probe before any disk is mounted.
    if (low4 == 0xF && wasQ6LegacyW) {
        iwmMode = v;
    }
    writeLatch = v;
    if (writeMode && low4 == 0xD) {
        cycleAccum = 0;
    }
}
